   SET DEFINE OFF;
Insert into TQC_SYSTEM_REPORTS
   (RPT_CODE, RPT_SYS_CODE, RPT_NAME, RPT_DESCRIPTION, RPT_DATA_FILE, 
    RPT_APPLCTN_LEVEL, RPT_ACTIVE, RPT_RSM_CODE)
 Values
   (327653, 0, 'KNOW_YOUR_CLIENT_REPORT', NULL, 'KYC_RPT.xml', 
    NULL, 'A', NULL);
COMMIT;
SET DEFINE OFF;
Insert into TQC_SYS_RPT_TEMPLATES
   (RPT_TMPL_CODE, RPT_TMPL_RPT_CODE, RPT_TMPL_FILE, RPT_TMPL_NAME, RPT_TMPL_DESCRIPTION, 
    RPT_TMPL_STYLE_FILE, RPT_TMPL_ORG_CODE, RPT_TMPL_ACTIVE)
 Values
   (327691, 327653, 'KYC_RPT.rtf', 'KNOW_YOUR_CLIENT_REPORT', 'KNOW_YOUR_CLIENT_REPORT', 
    'KYC_RPT.xsl', NULL, 'A');
COMMIT;