--
-- TQC_UTILITIES_CURSOR  (Package Body) 
--
CREATE OR REPLACE PACKAGE BODY TQ_CRM.TQC_UTILITIES_CURSOR
AS
FUNCTION search_loaded_clients(CLN_LOADED in varchar) RETURN loaded_clients_ref IS
v_cursor loaded_clients_ref;
BEGIN
 IF CLN_LOADED='N'
  THEN
      OPEN v_cursor FOR
     SELECT CLN_CODE, CLN_CLNT_SHT_DESC, CLN_CLNT_TWN_CODE, 
            CLN_CLNT_NAME, CLN_CLNT_OTHER_NAMES, CLN_CLNT_POSTAL_ADDRS,
             CLN_CLNT_PHYSICAL_ADDRS, CLN_CLNT_TEL, CLN_CLNT_TEL2, 
             CLN_CLNT_FAX, CLN_CLNT_CNTCT_EMAIL_1, CLN_CLNT_ID_REG_NO, 
             CLN_CLNT_DOB,CLN_REMARKS
     FROM TQC_CLIENT_TEMP;
    -- WHERE CLN_LOADED='N';
 ELSIF NVL(CLN_LOADED,'N')='Y'
  THEN
      OPEN v_cursor FOR
     SELECT CLN_CODE, CLN_CLNT_SHT_DESC, CLN_CLNT_TWN_CODE, 
            CLN_CLNT_NAME, CLN_CLNT_OTHER_NAMES, CLN_CLNT_POSTAL_ADDRS,
             CLN_CLNT_PHYSICAL_ADDRS, CLN_CLNT_TEL, CLN_CLNT_TEL2, 
             CLN_CLNT_FAX, CLN_CLNT_CNTCT_EMAIL_1, CLN_CLNT_ID_REG_NO, 
             CLN_CLNT_DOB,CLN_REMARKS
     FROM TQC_CLIENT_TEMP
     WHERE NVL(CLN_LOADED,'Y')='N';
 ELSE
     OPEN v_cursor FOR
     SELECT CLN_CODE, CLN_CLNT_SHT_DESC, CLN_CLNT_TWN_CODE, 
            CLN_CLNT_NAME, CLN_CLNT_OTHER_NAMES, CLN_CLNT_POSTAL_ADDRS,
             CLN_CLNT_PHYSICAL_ADDRS, CLN_CLNT_TEL, CLN_CLNT_TEL2, 
             CLN_CLNT_FAX, CLN_CLNT_CNTCT_EMAIL_1, CLN_CLNT_ID_REG_NO, 
             CLN_CLNT_DOB,CLN_REMARKS
     FROM TQC_CLIENT_TEMP;
   END IF;
    RETURN(v_cursor);
END;
FUNCTION search_loaded_agents(options IN VARCHAR2)  RETURN loaded_agents_ref IS
v_cursor loaded_agents_ref;
BEGIN
  IF options='L'
  THEN
  OPEN v_cursor FOR
     SELECT AGNL_CODE, AGNL_AGN_ACT_CODE,
      AGNL_ACCOUNT_TYPE, AGNL_AGN_ACC_NAME, 
      AGNL_AGN_PHYSICAL_ADDRESS, AGNL_AGN_POSTAL_ADDRESS, 
      AGNL_AGN_TWN_NAME, AGNL_AGN_REG_CODE, 
      AGNL_AGN_CONTACT_PERSON, AGNL_AGN_TEL1, 
      AGNL_AGN_FAX, AGNL_AGN_EMAIL_ADDRESS, 
      AGNL_AGN_DATE_CREATED, AGNL_AGN_CHECK_DATE,AGNL_AGN_BRANCH_NAME
     FROM TQC_AGENCIES_TEMP
     WHERE AGNL_LOADED='L';
  ELSIF options='N'
  THEN
  OPEN v_cursor FOR
     SELECT AGNL_CODE, AGNL_AGN_ACT_CODE,
      AGNL_ACCOUNT_TYPE, AGNL_AGN_ACC_NAME, 
      AGNL_AGN_PHYSICAL_ADDRESS, AGNL_AGN_POSTAL_ADDRESS, 
      AGNL_AGN_TWN_NAME, AGNL_AGN_REG_CODE, 
      AGNL_AGN_CONTACT_PERSON, AGNL_AGN_TEL1, 
      AGNL_AGN_FAX, AGNL_AGN_EMAIL_ADDRESS, 
      AGNL_AGN_DATE_CREATED,AGNL_AGN_CHECK_DATE,AGNL_AGN_BRANCH_NAME
     FROM TQC_AGENCIES_TEMP;
     --WHERE AGNL_LOADED='N';
  ELSIF options='A'
     THEN
       OPEN v_cursor FOR
      SELECT AGNL_CODE, AGNL_AGN_ACT_CODE,
      AGNL_ACCOUNT_TYPE, AGNL_AGN_ACC_NAME, 
      AGNL_AGN_PHYSICAL_ADDRESS, AGNL_AGN_POSTAL_ADDRESS, 
      AGNL_AGN_TWN_NAME, AGNL_AGN_REG_CODE, 
      AGNL_AGN_CONTACT_PERSON, AGNL_AGN_TEL1, 
      AGNL_AGN_FAX, AGNL_AGN_EMAIL_ADDRESS, 
      AGNL_AGN_DATE_CREATED, AGNL_AGN_CHECK_DATE,AGNL_AGN_BRANCH_NAME
     FROM TQC_AGENCIES_TEMP;
  END IF;
    RETURN(v_cursor);
END;
FUNCTION selectAllBranches  RETURN tqc_branches_ref IS
v_cursor tqc_branches_ref;
BEGIN
  OPEN v_cursor FOR
     SELECT BRN_CODE, BRN_SHT_DESC, BRN_REG_CODE, BRN_NAME
     FROM tqc_branches;
    RETURN(v_cursor);
END;
END TQC_UTILITIES_CURSOR; 
/