--
-- TQC_INCIDENTS_WEB_CURSOR  (Package) 
--
CREATE OR REPLACE PACKAGE TQ_CRM.TQC_INCIDENTS_WEB_CURSOR AS
  TYPE branchesLOV IS RECORD(
    BRN_CODE     TQC_BRANCHES.BRN_CODE%TYPE,
    BRN_SHT_DESC TQC_BRANCHES.BRN_SHT_DESC%TYPE,
    BRN_NAME     TQC_BRANCHES.BRN_NAME%TYPE);
  TYPE incidencesLOV IS RECORD(
    IDEP_CODE     TQC_INC_DEPARTMENTS.IDEP_CODE%TYPE,
    IDEP_DESC     TQC_INC_DEPARTMENTS.IDEP_DESC%TYPE,
    IDEP_SHT_DESC TQC_INC_DEPARTMENTS.IDEP_SHT_DESC%TYPE);

  TYPE incidentTypeLOV IS RECORD(
    DEPICT_code          TQC_DEP_INCIDENT_TYPES.DEPICT_code%TYPE,
    DEPICT_INCT_CODE     TQC_DEP_INCIDENT_TYPES.DEPICT_INCT_CODE%TYPE,
    DEPICT_IDEP_CODE     TQC_DEP_INCIDENT_TYPES.DEPICT_IDEP_CODE%TYPE,
    DEPICT_INCT_SHT_DESC TQC_DEP_INCIDENT_TYPES.DEPICT_INCT_SHT_DESC%TYPE,
    DEPICT_SEND_EMAIL    TQC_DEP_INCIDENT_TYPES.DEPICT_SEND_EMAIL%TYPE,
    DEPICT_PRIORITY_LVL  TQC_DEP_INCIDENT_TYPES.DEPICT_PRIORITY_LVL%TYPE,
    DEPICT_ESCALATE      TQC_DEP_INCIDENT_TYPES.DEPICT_ESCALATE%TYPE,
    DEPICT_ESC_DAYS      TQC_DEP_INCIDENT_TYPES.DEPICT_ESC_DAYS%TYPE,
    DEPICT_CLOSE_DAYS    TQC_DEP_INCIDENT_TYPES.DEPICT_CLOSE_DAYS%TYPE,
    INCT_DESC            VARCHAR2(100));

  TYPE usersLOV IS RECORD(
    USR_USERNAME TQC_USERS.USR_USERNAME%TYPE,
    USR_NAME     TQC_USERS.USR_NAME%TYPE);
  TYPE policyLOV IS RECORD(
    pol_policy_no VARCHAR2(50),
    code          VARCHAR2(20),
    NAME          VARCHAR2(200),
    brn_name      VARCHAR2(20));
  TYPE claimsLOV IS RECORD(
    cmb_claim_no      VARCHAR2(100),
    cmb_pol_policy_no VARCHAR2(30),
    pol_batch_no      NUMBER,
    NAME              VARCHAR2(200),
    brn_name          VARCHAR2(20));
  TYPE quotationLOV IS RECORD(
    QUOT_NO GIN_QUOTATIONS.QUOT_NO%TYPE);
  TYPE incidents IS RECORD(
    INC_CODE          NUMBER,
    INC_BRN_CODE      number,
    brn_name          varchar2(100),
    INC_INCT_CODE     number,
    INC_INCT_SHT_DESC varchar2(20),
    INC_DATE          date,
    INC_ORIGIN        varchar2(30),
    INC_ADDRESSED_TO  varchar2(50),
    INC_RECEIVED_BY   varchar2(50),
    INC_REMARKS       varchar2(100),
    INC_POL_POLICY_NO varchar2(50),
    INC_CLM_NO        varchar2(50),
    INC_IDEP_CODE     number,
    INC_SHT_DESC      varchar2(30),
    INC_IDEP_SHT_DESC varchar2(30),
    INC_QUOT_NO       varchar2(30),
    INCC_MAILED       VARCHAR2(30));
  TYPE incidentStatus IS RECORD(
    INCS_CODE            TQC_INCIDENT_STATUS.INCS_CODE%TYPE,
    INCS_ALLOC_TO        TQC_INCIDENT_STATUS.INCS_ALLOC_TO%TYPE,
    INCS_PRIORITY        TQC_INCIDENT_STATUS.INCS_PRIORITY%TYPE,
    INCS_EXP_ACT_DATE    TQC_INCIDENT_STATUS.INCS_EXP_ACT_DATE%TYPE,
    INCS_ESCALATION_DATE TQC_INCIDENT_STATUS.INCS_ESCALATION_DATE%TYPE,
    INCS_COMMENTS        TQC_INCIDENT_STATUS.INCS_COMMENTS%TYPE,
    INCS_ICTY_DATE       TQC_INCIDENT_STATUS.INCS_ICTY_DATE%TYPE,
    INCS_ALLOC_DATE      TQC_INCIDENT_STATUS.INCS_ALLOC_DATE%TYPE,
    INCS_STATUS          TQC_INCIDENT_STATUS.INCS_STATUS%TYPE,
    INCS_INC_CODE        TQC_INCIDENT_STATUS.INCS_INC_CODE%TYPE,
    INCS_ICTY_SHT_DESC   TQC_INCIDENT_STATUS.INCS_ICTY_SHT_DESC%TYPE,
    INCS_ICTY_BY         TQC_INCIDENT_STATUS.INCS_ICTY_BY%TYPE,
    INCS_ACKNOWLEDGED    TQC_INCIDENT_STATUS.INCS_ACKNOWLEDGED%TYPE);
  TYPE incidentActions IS RECORD(
    ICTY_CODE     TQC_INCI_ACTION_TYPES.ICTY_CODE%TYPE,
    ICTY_SHT_DESC TQC_INCI_ACTION_TYPES.ICTY_SHT_DESC%TYPE,
    ICTY_DESC     TQC_INCI_ACTION_TYPES.ICTY_DESC%TYPE,
    ICTY_DATE     TQC_INCI_ACTION_TYPES.ICTY_DATE%TYPE);
  TYPE incActionsRec IS REF CURSOR RETURN incidentActions;
  TYPE incidentStatusRec IS REF CURSOR RETURN incidentStatus;
  TYPE incidentsRec IS REF CURSOR RETURN incidents;
  TYPE quotationLOVRec IS REF CURSOR RETURN quotationLOV;
  TYPE claimsLOVRec IS REF CURSOR RETURN claimsLOV;
  TYPE policLOVRec IS REF CURSOR RETURN policyLOV;
  TYPE usersLOVRec IS REF CURSOR RETURN usersLOV;
  TYPE incidentTypeLOVRec IS REF CURSOR RETURN incidentTypeLOV;
  TYPE incidencesLovRec IS REF CURSOR RETURN incidencesLOV;
  TYPE branchesLOvRec IS REF CURSOR RETURN branchesLOV;
  PROCEDURE FindIncBranches(v_branches OUT branchesLOvRec,
                            v_sys_code NUMBER);
  PROCEDURE FindIncDepartments(v_incidences OUT incidencesLovRec,
                               v_brn_code   NUMBER);
  PROCEDURE FindIncTypes(v_inc_types OUT incidentTypeLOVRec,
                         v_idep_code NUMBER);
  PROCEDURE FindUsers(v_user OUT usersLOVRec);
  PROCEDURE FindPolicies(v_policy OUT policLOVRec, v_sys_param NUMBER);
  PROCEDURE FindClaims(v_claims OUT claimsLOVRec);
  PROCEDURE FindQuotation(v_quotation OUT quotationLOVRec);
  PROCEDURE FindIncidents(v_incidents_rec OUT incidentsRec);
  PROCEDURE getIncidentStatus(v_inc_status_rec OUT incidentStatusRec,
                              v_inc_code       NUMBER,
                              v_view_mode      VARCHAR2);
  PROCEDURE getIncActions(v_inc_actions OUT incActionsRec);

  TYPE incidentTypes IS RECORD(
    INCT_CODE       TQC_INCIDENT_TYPES.INCT_CODE%TYPE,
    INCT_SHT_DESC   TQC_INCIDENT_TYPES.INCT_SHT_DESC%TYPE,
    INCT_DESC       TQC_INCIDENT_TYPES.INCT_DESC%TYPE,
    INCT_OWNER      TQC_INCIDENT_TYPES.INCT_OWNER%TYPE,
    INCT_OWNER_DESC VARCHAR2(100));
  TYPE incidentTypesRec IS REF CURSOR RETURN incidentTypes;
  PROCEDURE find_incidence_types(v_inc_types OUT incidentTypesRec);

  TYPE incidentDeps IS RECORD(
    IDEP_CODE     TQC_INC_DEPARTMENTS.IDEP_CODE%TYPE,
    IDEP_SHT_DESC TQC_INC_DEPARTMENTS.IDEP_SHT_DESC%TYPE,
    IDEP_DESC     TQC_INC_DEPARTMENTS.IDEP_DESC%TYPE,
    IDEP_BRN_CODE TQC_INC_DEPARTMENTS.IDEP_BRN_CODE%TYPE,
    BRN_SHT_DESC  VARCHAR2(100),
    BRN_NAME      VARCHAR2(100));
  TYPE incidentDepsRec IS REF CURSOR RETURN incidentDeps;
  PROCEDURE FindIncDepartmentsBySystem(v_incidences OUT incidentDepsRec,
                                       v_sys_code   NUMBER);

  TYPE branches IS RECORD(
    BRN_CODE     TQC_BRANCHES.BRN_CODE%TYPE,
    BRN_SHT_DESC TQC_BRANCHES.BRN_SHT_DESC%TYPE,
    BRN_NAME     TQC_BRANCHES.BRN_NAME%TYPE);
  TYPE branchesRec IS REF CURSOR RETURN branches;
  PROCEDURE find_system_branches(v_incidences OUT branchesRec,
                                 v_sys_code   NUMBER);

END TQC_INCIDENTS_WEB_CURSOR; 
/