--
-- TQC_ACTIVITIES_PKG  (Package) 
--
CREATE OR REPLACE PACKAGE TQ_CRM.TQC_ACTIVITIES_PKG AS
/******************************************************************************
   NAME:       TQC_ACTIVITIES_PKG
   PURPOSE:

   REVISIONS:
   Ver        Date        Author           Description
   ---------  ----------  ---------------  ------------------------------------
   1.0        3/17/2010             1. Created this package.
******************************************************************************/

    PROCEDURE raise_error (v_msg IN VARCHAR2, v_err_no IN NUMBER := NULL);

  PROCEDURE TQC_ACTIVITIES_PRC (
  v_add_edit         VARCHAR2,
  V_ACT_CODE           TQC_ACTIVITIES.ACT_CODE%TYPE,
  V_ACT_ACTY_CODE      TQC_ACTIVITIES.ACT_ACTY_CODE%TYPE,
  V_ACT_WEF            TQC_ACTIVITIES.ACT_WEF%TYPE DEFAULT NULL,
  V_ACT_WET            TQC_ACTIVITIES.ACT_WET%TYPE DEFAULT NULL,
  V_ACT_DURATION       TQC_ACTIVITIES.ACT_DURATION%TYPE DEFAULT NULL,
  V_ACT_SUBJECT        TQC_ACTIVITIES.ACT_SUBJECT%TYPE DEFAULT NULL,
  V_ACT_LOCATION       TQC_ACTIVITIES.ACT_LOCATION%TYPE DEFAULT NULL,
  V_ACT_ASSIGNED_TO    TQC_ACTIVITIES.ACT_ASSIGNED_TO%TYPE DEFAULT NULL,
  V_ACT_RELATED_TO     TQC_ACTIVITIES.ACT_RELATED_TO%TYPE DEFAULT NULL,
  V_ACT_STATUS_ID      TQC_ACTIVITIES.ACT_STATUS_ID%TYPE DEFAULT NULL,                        
  V_ACT_DESCRIPTION    TQC_ACTIVITIES.ACT_DESCRIPTION%TYPE DEFAULT NULL,
  V_ACT_REMINDER       TQC_ACTIVITIES.ACT_REMINDER%TYPE DEFAULT NULL,
  V_ACT_TEAM           TQC_ACTIVITIES.ACT_TEAM%TYPE DEFAULT NULL,
  V_ACT_REMINDER_TIME  TQC_ACTIVITIES.ACT_REMINDER_TIME%TYPE DEFAULT NULL,
  V_ACT_MSGT_CODE  TQC_ACTIVITIES.ACT_MSGT_CODE%TYPE DEFAULT NULL
  ) ;
     
  PROCEDURE TQC_PRIORITY_LEVEL_PRC(
  v_add_edit    varchar2,
  V_PRL_CODE            TQC_PRIORITY_LEVELS.PRL_CODE%TYPE,
  V_PRL_DESCRIPTION     TQC_PRIORITY_LEVELS.PRL_DESCRIPTION%TYPE DEFAULT NULL,
  V_PRL_SHT_DESCRIPTION TQC_PRIORITY_LEVELS.PRL_SHT_DESCRIPTION%TYPE DEFAULT NULL
  );
  
  PROCEDURE TQC_STATUSES_PRC(
    v_add_edit    varchar2,
    V_STATUS_ID     TQC_STATUSES.STATUS_ID%TYPE, 
    V_STATUS_CODE   TQC_STATUSES.STATUS_CODE%TYPE DEFAULT NULL, 
    V_STATUS_DESC   TQC_STATUSES.STATUS_DESC%TYPE DEFAULT NULL
    );
    
PROCEDURE TQC_ACTIVITY_NOTES_PRC(
    v_add_edit    varchar2,
    V_ANT_CODE                TQC_ACTIVITY_NOTES.ANT_CODE%TYPE,  
    V_ANT_ACC_CODE            TQC_ACTIVITY_NOTES.ANT_ACC_CODE%TYPE DEFAULT NULL, 
    V_ANT_CONTACT_CODE        TQC_ACTIVITY_NOTES.ANT_CONTACT_CODE%TYPE DEFAULT NULL, 
    V_ANT_SUBJECT             TQC_ACTIVITY_NOTES.ANT_SUBJECT%TYPE DEFAULT NULL, 
    V_ANT_NOTES               TQC_ACTIVITY_NOTES.ANT_NOTES%TYPE DEFAULT NULL, 
    V_ANT_ATTACHMENT          TQC_ACTIVITY_NOTES.ANT_ATTACHMENT%TYPE  DEFAULT NULL, 
    V_ANT_ACT_CODE            TQC_ACTIVITY_NOTES.ANT_CODE%TYPE DEFAULT NULL,
    V_ANT_ATTACHMENT_TYPE     TQC_ACTIVITY_NOTES.ANT_ATTACHMENT_TYPE%TYPE DEFAULT NULL,
    V_ANT_FILE_NAME         TQC_ACTIVITY_NOTES.ANT_FILE_NAME%TYPE DEFAULT NULL
    );   
    
 PROCEDURE TQC_ACTIVITY_TASKS_PRC(
      v_add_edit    varchar2,  
     V_AT_CODE            TQC_ACTIVITY_TASKS.AT_CODE%TYPE , 
     V_AT_ACT_CODE        TQC_ACTIVITY_TASKS.AT_ACT_CODE%TYPE,
     V_AT_DATE_FROM       TQC_ACTIVITY_TASKS.AT_DATE_FROM%TYPE DEFAULT NULL,
     V_AT_DATE_TO         TQC_ACTIVITY_TASKS.AT_DATE_TO%TYPE DEFAULT NULL,
     V_AT_SUBJECT         TQC_ACTIVITY_TASKS.AT_SUBJECT%TYPE DEFAULT NULL, 
     V_AT_STATUS_ID       TQC_ACTIVITY_TASKS.AT_STATUS_ID%TYPE DEFAULT NULL,
     V_AT_PRIORITY_CODE   TQC_ACTIVITY_TASKS.AT_PRIORITY_CODE%TYPE DEFAULT NULL,
     V_AT_ACC_CODE        TQC_ACTIVITY_TASKS.AT_ACC_CODE%TYPE DEFAULT NULL
     ); 
     
 PROCEDURE  TQC_ACTIVITY_PARTICIPANTS_PRC(
     v_add_edit    varchar2, 
    V_PARTICIP_ID        TQC_ACTIVITY_PARTICIPANTS.PARTICIP_ID%TYPE, 
    V_PARTICIP_ACT_CODE  TQC_ACTIVITY_PARTICIPANTS.PARTICIP_ACT_CODE%TYPE,
    V_PARTICIP_AAC_CODE  TQC_ACTIVITY_PARTICIPANTS.PARTICIP_AAC_CODE%TYPE
    );
    
 PROCEDURE send_activity_invites(
    v_ACT_CODE IN NUMBER,
     v_user IN number);
    
     
                    
 END TQC_ACTIVITIES_PKG; 
/