SET DEFINE OFF;
Insert into TQC_ACCOUNT_TYPES
   (ACT_CODE, ACT_ACCOUNT_TYPE, ACT_TYPE_SHT_DESC, ACT_WTHTX_RATE, ACT_TYPE_ID, 
    ACT_COMM_RESERVE_RATE, ACT_MAX_ADV_AMT, ACT_MAX_ADV_RPYMT_PRD, ACT_RCPTS_INCLUDE_COMM, ACT_OVERIDE_RATE, 
    ACT_ID_SERIAL_FORMAT, ACT_VAT_RATE, ACT_FORMAT, ACT_ODL_CODE, ACT_NO_GEN_CODE, 
    ACT_COMMISION_LEVY_RATE)
 Values
   (33, 'AGENCY MANAGER', 'BA', 10, 'BA', 
    0, NULL, NULL, 'N', 7, 
    'BA[SERIALNO]', NULL, 'BA[SERIALNO]', NULL, '99', 
    NULL);
COMMIT;
