--
-- AGENCY_PRINCIPLE_DIR_FK  (Index) 
--
CREATE UNIQUE INDEX TQ_CRM.AGENCY_PRINCIPLE_DIR_FK ON TQ_CRM.TQC_AGENCY_DIRECTORS
(ADIR_PRINCIPLE, ADIR_AGN_CODE)
TABLESPACE CRMDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );