--
-- PK_TQC_SYSTEM_ROLE_MENU  (Index) 
--
CREATE UNIQUE INDEX TQ_CRM.PK_TQC_SYSTEM_ROLE_MENU ON TQ_CRM.TQC_SYSTEM_ROLE_MENU
(SRM_SRL_CODE, SRM_MENU_CODE, SRM_GRANT_DATE)
TABLESPACE CRMDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          896K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );