--
-- TQC_QRTZ_BLOB_TRIG_PK  (Index) 
--
CREATE UNIQUE INDEX TQ_CRM.TQC_QRTZ_BLOB_TRIG_PK ON TQ_CRM.TQC_QRTZ_BLOB_TRIGGERS
(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
TABLESPACE CRMDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );