SET DEFINE OFF;
Insert into TQ_CRM.TQC_SYSTEM_REPORTS
   (RPT_CODE, RPT_SYS_CODE, RPT_NAME, RPT_DESCRIPTION, RPT_DATA_FILE, RPT_ACTIVE)
 Values
   (1945, 0, 'UPDATE_CLIENT_REASONS', 'REASONS FOR UPDATING CLIENTS', 'UpdateClientReasons.xml', 
    'A');
COMMIT;


SET DEFINE OFF;
Insert into TQ_CRM.TQC_SYS_RPT_TEMPLATES
   (RPT_TMPL_CODE, RPT_TMPL_RPT_CODE, RPT_TMPL_FILE, RPT_TMPL_NAME, RPT_TMPL_STYLE_FILE, RPT_TMPL_ACTIVE)
 Values
   (3262, 1945, 'UpdateClientReasons_template.rtf', 'UpdateClientReasons', 
    'UpdateClientReasons.xsl', 'A');
COMMIT;


ALTER TABLE TQ_CRM.TQC_CLIENTS_LOG
ADD (CLNT_REASON_UPDATED VARCHAR2(200 BYTE));

ALTER TABLE TQ_CRM.TQC_CLIENTS_LOG
ADD (CLNT_PREV_REASON_UPDATED VARCHAR2(200 BYTE));