TYPE agency_info_rec IS RECORD (
      agn_code                   tqc_agencies.agn_code%TYPE,
      agn_act_code               tqc_agencies.agn_act_code%TYPE,
      agn_sht_desc               tqc_agencies.agn_sht_desc%TYPE,
      agn_name                   tqc_agencies.agn_name%TYPE,
      agn_physical_address       tqc_agencies.agn_physical_address%TYPE,
      agn_postal_address         tqc_agencies.agn_postal_address%TYPE,
      agn_twn_code               tqc_agencies.agn_twn_code%TYPE,
      agn_cou_code               tqc_agencies.agn_cou_code%TYPE,
      agn_email_address          tqc_agencies.agn_email_address%TYPE,
      agn_web_address            tqc_agencies.agn_web_address%TYPE,
      agn_zip                    tqc_agencies.agn_zip%TYPE,
      agn_contact_person         tqc_agencies.agn_contact_person%TYPE,
      agn_contact_title          tqc_agencies.agn_contact_title%TYPE,
      agn_tel1                   tqc_agencies.agn_tel1%TYPE,
      agn_tel2                   tqc_agencies.agn_tel2%TYPE,
      agn_fax                    tqc_agencies.agn_fax%TYPE,
      agn_acc_no                 tqc_agencies.agn_acc_no%TYPE,
      agn_pin                    tqc_agencies.agn_pin%TYPE,
      agn_agent_commission       tqc_agencies.agn_agent_commission%TYPE,
      agn_credit_allowed         tqc_agencies.agn_credit_allowed%TYPE,
      agn_agent_wht_tax          tqc_agencies.agn_agent_wht_tax%TYPE,
      agn_print_dbnote           tqc_agencies.agn_print_dbnote%TYPE,
      agn_status                 tqc_agencies.agn_status%TYPE,
      agn_date_created           tqc_agencies.agn_date_created%TYPE,
      agn_created_by             tqc_agencies.agn_created_by%TYPE,
      agn_reg_code               tqc_agencies.agn_reg_code%TYPE,
      agn_comm_reserve_rate      tqc_agencies.agn_comm_reserve_rate%TYPE,
      agn_annual_budget          tqc_agencies.agn_annual_budget%TYPE,
      agn_status_eff_date        tqc_agencies.agn_status_eff_date%TYPE,
      agn_credit_period          tqc_agencies.agn_credit_period%TYPE,
      agn_comm_stat_eff_dt       tqc_agencies.agn_comm_stat_eff_dt%TYPE,
      agn_comm_status_dt         tqc_agencies.agn_comm_status_dt%TYPE,
      agn_comm_allowed           tqc_agencies.agn_comm_allowed%TYPE,
      agn_checked                tqc_agencies.agn_checked%TYPE,
      agn_checked_by             tqc_agencies.agn_checked_by%TYPE,
      agn_check_date             tqc_agencies.agn_check_date%TYPE,
      agn_comp_comm_arrears      tqc_agencies.agn_comp_comm_arrears%TYPE,
      agn_reinsurer              tqc_agencies.agn_reinsurer%TYPE,
      agn_brn_code               tqc_agencies.agn_brn_code%TYPE,
      agn_town                   tqc_agencies.agn_town%TYPE,
      agn_country                tqc_agencies.agn_country%TYPE,
      agn_status_desc            tqc_agencies.agn_status_desc%TYPE,
      agn_id_no                  tqc_agencies.agn_id_no%TYPE,
      agn_con_code               tqc_agencies.agn_con_code%TYPE,
      agn_agn_code               tqc_agencies.agn_agn_code%TYPE,
      agn_sms_tel                tqc_agencies.agn_sms_tel%TYPE,
      agn_ahc_code               tqc_agencies.agn_ahc_code%TYPE,
      agn_sec_code               tqc_agencies.agn_sec_code%TYPE,
      agn_agnc_class_code        tqc_agencies.agn_agnc_class_code%TYPE,
      agn_expiry_date            tqc_agencies.agn_expiry_date%TYPE,
      agn_license_no             tqc_agencies.agn_license_no%TYPE,
      agn_runoff                 tqc_agencies.agn_runoff%TYPE,
      agn_licensed               tqc_agencies.agn_licensed%TYPE,
      agn_license_grace_pr       tqc_agencies.agn_license_grace_pr%TYPE,
      agn_old_acc_no             tqc_agencies.agn_old_acc_no%TYPE,
      agn_status_remarks         tqc_agencies.agn_status_remarks%TYPE,
      bnk_code                   tqc_banks.bnk_code%TYPE,
      bnk_bank_name              tqc_banks.bnk_bank_name%TYPE,
      bbr_code                   tqc_bank_branches.bbr_code%TYPE,
      bbr_branch_name            tqc_bank_branches.bbr_branch_name%TYPE,
      agn_bank_acc_no            tqc_agencies.agn_bank_acc_no%TYPE,
      agn_unique_prefix          tqc_agencies.agn_unique_prefix%TYPE,
      cou_admin_reg_type         tqc_countries.cou_admin_reg_type%TYPE,
      agn_state_code             tqc_agencies.agn_state_code%TYPE,
      sts_name                   tqc_states.sts_name%TYPE,
      agn_crdt_rting             VARCHAR2 (20),
      clnt_name                  tqc_clients.clnt_name%TYPE,
      accountmanager             VARCHAR2 (200),
      prom_transaction_date      lms_agent_promotion.prom_transaction_date%TYPE,
      prom_transaction_type      lms_agent_promotion.prom_transaction_type%TYPE,
      prom_demo_promo_type       lms_agent_promotion.prom_demo_promo_type%TYPE,
      brn_name                   tqc_branches.brn_name%TYPE,
      bra_name                   tqc_branch_agencies.bra_name%TYPE,
      brn_code                   tqc_branches.brn_code%TYPE,
      bra_unt_sht_desc_prefix    tqc_branch_agencies.bra_unt_sht_desc_prefix%TYPE,
      bru_unt_sht_desc_prefix    tqc_branch_units.bru_unt_sht_desc_prefix%TYPE,
      bru_agn_seq_no             tqc_branch_units.bru_agn_seq_no%TYPE,
      prom_precontract_agn_seq   lms_agent_promotion.prom_precontract_agn_seq%TYPE,
      cou_zip_code               tqc_countries.cou_zip_code%TYPE,
      agn_account_manager        tqc_agencies.agn_account_manager%TYPE,
      agn_credit_limit           tqc_agencies.agn_credit_limit%TYPE,
      bru_code                   tqc_branch_units.bru_code%TYPE,
      bru_name                   tqc_branch_units.bru_name%TYPE,
      agn_local_international    tqc_agencies.agn_local_international%TYPE,
      agn_regulator_number       tqc_agencies.agn_regulator_number%TYPE,
      agn_authorised             tqc_agencies.agn_authorised%TYPE,
      agn_rorg_code              tqc_agencies.agn_rorg_code%TYPE,
      agn_ors_code               tqc_agencies.agn_ors_code%TYPE,
      rorg_desc                  tqc_rating_organizations.rorg_desc%TYPE,
      ors_desc                   tqc_org_rating_starndards.ors_desc%TYPE,
      agn_allocate_cert          tqc_agencies.agn_allocate_cert%TYPE,
      holding_companies          VARCHAR2 (200),
      agn_bounced_chq            tqc_agencies.agn_bounced_chq%TYPE,
      agn_default_comm_mode      tqc_agencies.agn_default_comm_mode%TYPE,
      agn_bpn_code               tqc_agencies.agn_bpn_code%TYPE,
      bpn_name                   tqc_business_persons.bpn_name%TYPE,
      agn_agent_type             tqc_agencies.agn_agent_type%TYPE,
      agn_group                  tqc_agencies.agn_group%TYPE,
      agn_main_agn_code          tqc_agencies.agn_main_agn_code%TYPE,
      main_agency_name           tqc_agencies.agn_name%TYPE,
      agn_vat_applicable         tqc_agencies.agn_vat_applicable%TYPE,
      agn_whtax_applicable       tqc_agencies.agn_whtax_applicable%TYPE,
      agn_tel_pay                tqc_agencies.agn_tel_pay%TYPE,
      agn_payment_freq           tqc_agencies.agn_payment_freq%TYPE,
      agn_default_cpm_mode       tqc_agencies.agn_default_cpm_mode%TYPE,
      agn_cpm_mode_desc          VARCHAR2(50)
   );
   
   PROCEDURE get_agency_info (
      v_agn_act_code      IN       tqc_agencies.agn_act_code%TYPE,
      v_agency_info_ref   OUT      agency_info_ref
   )
   IS
   BEGIN
      --RAISE_ERROR('v_agn_act_code'||v_agn_act_code);
      OPEN v_agency_info_ref FOR
         SELECT   a.agn_code, a.agn_act_code, a.agn_sht_desc, a.agn_name,
                  a.agn_physical_address, a.agn_postal_address,
                  a.agn_twn_code, a.agn_cou_code, a.agn_email_address,
                  a.agn_web_address, a.agn_zip, a.agn_contact_person,
                  a.agn_contact_title, a.agn_tel1, a.agn_tel2, a.agn_fax,
                  a.agn_acc_no, a.agn_pin, a.agn_agent_commission,
                  a.agn_credit_allowed, a.agn_agent_wht_tax,
                  a.agn_print_dbnote, a.agn_status, a.agn_date_created,
                  a.agn_created_by, a.agn_reg_code, a.agn_comm_reserve_rate,
                  a.agn_annual_budget, a.agn_status_eff_date,
                  a.agn_credit_period, a.agn_comm_stat_eff_dt,
                  a.agn_comm_status_dt, a.agn_comm_allowed, a.agn_checked,
                  a.agn_checked_by, a.agn_check_date,
                  a.agn_comp_comm_arrears, a.agn_reinsurer, a.agn_brn_code,
                  a.agn_town, a.agn_country, a.agn_status_desc, a.agn_id_no,
                  a.agn_con_code, a.agn_agn_code, a.agn_sms_tel,
                  a.agn_ahc_code, a.agn_sec_code, a.agn_agnc_class_code,
                  a.agn_expiry_date, a.agn_license_no, a.agn_runoff,
                  a.agn_licensed, a.agn_license_grace_pr, a.agn_old_acc_no,
                  a.agn_status_remarks, bnk_code, bnk_bank_name, bbr_code,
                  bbr_branch_name, a.agn_bank_acc_no, a.agn_unique_prefix,
                  cou_admin_reg_type, a.agn_state_code, sts_name,
                  a.agn_crdt_rting, clnt_name, b.agn_name accountmanager,
                  prom_transaction_date, prom_transaction_type,
                  prom_demo_promo_type, brn_name, bra_name, brn_code,
                  prom_bra_unt_sht_desc_prefix, prom_bru_unt_sht_desc_prefix,
                  prom_bru_agn_seq_no, prom_precontract_agn_seq,
                  cou_zip_code, b.agn_code, a.agn_credit_limit, bru_code,
                  bru_name, a.agn_local_international,
                  a.agn_regulator_number, a.agn_authorised, a.agn_rorg_code,
                  a.agn_ors_code, rorg_desc, ors_desc, a.agn_allocate_cert,
                  c.agn_name, a.agn_bounced_chq, a.agn_default_comm_mode,
                  a.agn_bpn_code, bpn_name, a.agn_agent_type, a.agn_group,
                  a.agn_main_agn_code, d.agn_name, a.agn_vat_applicable,
                  a.agn_whtax_applicable,a.agn_tel_pay,a.agn_payment_freq,a.agn_default_cpm_mode,
                  (select cpm_desc from tqc_clm_payment_modes where cpm_code = a.agn_default_cpm_mode) agn_cpm_mode_desc
             FROM tqc_agencies a,
                  tqc_agencies b,
                  tqc_agencies c,
                  tqc_agencies d,
                  tqc_bank_branches,
                  tqc_banks,
                  tqc_countries,
                  tqc_states,
                  tqc_clients,
                  lms_agent_promotion,
                  tqc_branches,
                  tqc_branch_agencies,
                  tqc_branch_units,
                  tqc_rating_organizations,
                  tqc_org_rating_starndards,
                  tqc_business_persons
            WHERE a.agn_bbr_code = bbr_code(+)
              AND a.agn_cou_code = cou_code(+)
              AND bbr_bnk_code = bnk_code(+)
              AND a.agn_state_code = sts_code(+)
              AND a.agn_clnt_code = clnt_code(+)
              AND c.agn_code(+) = a.agn_agn_code
              AND d.agn_code(+) = a.agn_main_agn_code
              AND a.agn_account_manager = b.agn_code(+)
              AND a.agn_act_code = NVL (v_agn_act_code, a.agn_act_code)
              AND prom_agn_code(+) = a.agn_code
              AND brn_code(+) = prom_brn_code
              AND bru_code(+) = a.agn_bru_code
              AND bra_code(+) = prom_bra_code
              AND rorg_code(+) = a.agn_rorg_code
              AND a.agn_ors_code = ors_code(+)
              AND bpn_code(+) = a.agn_bpn_code
         -- AND BRU_BRN_CODE(+)=BRN_CODE
         ORDER BY a.agn_name;
   END get_agency_info;