--
-- DT_DROPUSEROBJECTBYID  (Procedure) 
--
CREATE OR REPLACE PROCEDURE TQ_CRM.DT_DROPUSEROBJECTBYID ( PARAM_ID IN NUMBER ) AS BEGIN DELETE FROM MICROSOFTDTPROPERTIES WHERE OBJECTID = PARAM_ID; END DT_DROPUSEROBJECTBYID; 
 
/