-- 
-- Non Foreign Key Constraints for Table AUTHORIZATION_ROLES 
-- 
ALTER TABLE TQ_CRM.AUTHORIZATION_ROLES ADD (
  CONSTRAINT AROL_PK
  PRIMARY KEY
  (AROL_ID)
  USING INDEX TQ_CRM.AROL_PK
  ENABLE VALIDATE);