-- 
-- Foreign Key Constraints for Table JBPM4_HIST_DETAIL 
-- 
ALTER TABLE TQ_CRM.JBPM4_HIST_DETAIL ADD (
  CONSTRAINT FK_HDETAIL_HVAR 
  FOREIGN KEY (HVAR_) 
  REFERENCES TQ_CRM.JBPM4_HIST_VAR (DBID_)
  ENABLE VALIDATE);