-- 
-- Foreign Key Constraints for Table JBPM4_ID_MEMBERSHIP 
-- 
ALTER TABLE TQ_CRM.JBPM4_ID_MEMBERSHIP ADD (
  CONSTRAINT FK_MEM_GROUP 
  FOREIGN KEY (GROUP_) 
  REFERENCES TQ_CRM.JBPM4_ID_GROUP (DBID_)
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.JBPM4_ID_MEMBERSHIP ADD (
  CONSTRAINT FK_MEM_USER 
  FOREIGN KEY (USER_) 
  REFERENCES TQ_CRM.JBPM4_ID_USER (DBID_)
  ENABLE VALIDATE);