-- 
-- Non Foreign Key Constraints for Table LMS_PRODUCTS 
-- 
ALTER TABLE TQ_CRM.LMS_PRODUCTS ADD (
  CONSTRAINT PENS_VALUES
  CHECK (PROD_PENS_TYPE IN ('PENS', 'PROV', 'INV'))
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.LMS_PRODUCTS ADD (
  CONSTRAINT LMS_PRODUCTS_U01
  UNIQUE (PROD_SHT_DESC, PROD_DESC)
  USING INDEX TQ_CRM.LMS_PRODUCTS_U01
  ENABLE VALIDATE);