-- 
-- Non Foreign Key Constraints for Table TQC_HOLIDAYS_DEFINITIONS 
-- 
ALTER TABLE TQ_CRM.TQC_HOLIDAYS_DEFINITIONS ADD (
  CONSTRAINT TQC_HOLIDAYS_DEFINITIONS_PK
  PRIMARY KEY
  (THD_DESC, THD_DAY, THD_MON, THD_COU_CODE)
  USING INDEX TQ_CRM.TQC_HOLIDAYS_DEFINITIONS_PK
  ENABLE VALIDATE);