-- 
-- Non Foreign Key Constraints for Table TQC_GROUP_CLNT_DTLS 
-- 
ALTER TABLE TQ_CRM.TQC_GROUP_CLNT_DTLS ADD (
  CONSTRAINT TQC_GROUP_CLNT_DTLS_PK
  PRIMARY KEY
  (GRPD_CODE)
  USING INDEX TQ_CRM.TQC_GROUP_CLNT_DTLS_PK
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_GROUP_CLNT_DTLS ADD (
  CONSTRAINT GRPD_UNIQUE
  UNIQUE (GRPD_CLNT_CODE, GRPD_GRP_CODE)
  USING INDEX TQ_CRM.GRPD_UNIQUE
  ENABLE VALIDATE);