-- 
-- Non Foreign Key Constraints for Table TQC_BANK_REGIONS 
-- 
ALTER TABLE TQ_CRM.TQC_BANK_REGIONS ADD (
  CONSTRAINT BNKR_CODE_PK
  PRIMARY KEY
  (BNKR_CODE)
  USING INDEX TQ_CRM.BNKR_CODE_PK
  ENABLE VALIDATE);