-- 
-- Non Foreign Key Constraints for Table TQC_COMPANY_MEMOS 
-- 
ALTER TABLE TQ_CRM.TQC_COMPANY_MEMOS ADD (
  CONSTRAINT COMEM_AUTHORIZED_CHK
  CHECK (COMEM_AUTHORIZED IN ('Y','N'))
  ENABLE VALIDATE);