-- 
-- Foreign Key Constraints for Table TQC_SYS_POSTS 
-- 
ALTER TABLE TQ_CRM.TQC_SYS_POSTS ADD (
  CONSTRAINT SPOST_PARENT_SPOST_FK 
  FOREIGN KEY (SPOST_PARENT_SPOST_CODE) 
  REFERENCES TQ_CRM.TQC_SYS_POSTS (SPOST_CODE)
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_SYS_POSTS ADD (
  CONSTRAINT SPOST_SYSPL_FK 
  FOREIGN KEY (SPOST_SYSPL_CODE) 
  REFERENCES TQ_CRM.TQC_SYS_POST_LEVELS (SYSPL_CODE)
  ENABLE VALIDATE);