-- 
-- Non Foreign Key Constraints for Table TQC_AGENCIES_CLASSES 
-- 
ALTER TABLE TQ_CRM.TQC_AGENCIES_CLASSES ADD (
  CONSTRAINT AGNC_CLASS_CODEPK
  PRIMARY KEY
  (AGNC_CLASS_CODE)
  USING INDEX TQ_CRM.AGNC_CLASS_CODEPK
  ENABLE VALIDATE);