-- 
-- Foreign Key Constraints for Table TQC_SYS_MOD_SUBUNITS_INPUTS 
-- 
ALTER TABLE TQ_CRM.TQC_SYS_MOD_SUBUNITS_INPUTS ADD (
  CONSTRAINT TQC_SYS_MOD_SUBUNITS_INPUTSR01 
  FOREIGN KEY (TSMSI_TSMSD_CODE) 
  REFERENCES TQ_CRM.TQC_SYS_MOD_SUBUNITS_DETAILS (TSMSD_CODE)
  ENABLE VALIDATE);