-- 
-- Non Foreign Key Constraints for Table TQC_SYSTEM_BPM_TICKETS 
-- 
ALTER TABLE TQ_CRM.TQC_SYSTEM_BPM_TICKETS ADD (
  CONSTRAINT TQC_SYSTEM_BPM_TICKETS_PK
  PRIMARY KEY
  (TQSBT_ID)
  USING INDEX TQ_CRM.TQC_SYSTEM_BPM_TICKETS_PK
  ENABLE VALIDATE);