-- 
-- Non Foreign Key Constraints for Table TQC_AGENT_TYPES 
-- 
ALTER TABLE TQ_CRM.TQC_AGENT_TYPES ADD (
  CONSTRAINT AGNTY_CODE_PK
  PRIMARY KEY
  (AGNTY_CODE)
  USING INDEX TQ_CRM.AGNTY_CODE_PK
  ENABLE VALIDATE);