-- 
-- Non Foreign Key Constraints for Table TQC_LOG 
-- 
ALTER TABLE TQ_CRM.TQC_LOG ADD (
  CONSTRAINT PK_TQC_LOG
  PRIMARY KEY
  (LOG_SYS, LOG_TYPE, LOG_DATE)
  USING INDEX TQ_CRM.PK_TQC_LOG
  ENABLE VALIDATE);