-- 
-- Non Foreign Key Constraints for Table TQC_ACTIVITY_TYPES 
-- 
ALTER TABLE TQ_CRM.TQC_ACTIVITY_TYPES ADD (
  CONSTRAINT ACTY_PK
  PRIMARY KEY
  (ACTY_CODE)
  USING INDEX TQ_CRM.ACTY_PK
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_ACTIVITY_TYPES ADD (
  CONSTRAINT ACTY_DESC_UQC
  UNIQUE (ACTY_DESC)
  USING INDEX TQ_CRM.ACTY_DESC_UQC
  ENABLE VALIDATE);