-- 
-- Non Foreign Key Constraints for Table TQC_SERV_REQ_COMMENTS 
-- 
ALTER TABLE TQ_CRM.TQC_SERV_REQ_COMMENTS ADD (
  CONSTRAINT TQC_SERV_REQ_COMMENTS_PK
  PRIMARY KEY
  (SRC_CODE)
  USING INDEX TQ_CRM.TQC_SERV_REQ_COMMENTS_PK
  ENABLE VALIDATE);