-- 
-- Non Foreign Key Constraints for Table TQC_PRODUCT_CLIENT_ATTRIBUTES 
-- 
ALTER TABLE TQ_CRM.TQC_PRODUCT_CLIENT_ATTRIBUTES ADD (
  CONSTRAINT TQC_PRODUCT_CLIENT_ATTRIBUT_PK
  PRIMARY KEY
  (PCA_CODE)
  USING INDEX TQ_CRM.TQC_PRODUCT_CLIENT_ATTRIBUT_PK
  ENABLE VALIDATE);