-- 
-- Non Foreign Key Constraints for Table TQC_TASK_ESCALATIONS 
-- 
ALTER TABLE TQ_CRM.TQC_TASK_ESCALATIONS ADD (
  CONSTRAINT TQC_TASK_ESCALATIONS_PK
  PRIMARY KEY
  (TTE_TASK_ID, TTE_LEVEL)
  USING INDEX TQ_CRM.TQC_TASK_ESCALATIONS_PK
  ENABLE VALIDATE);