-- 
-- Non Foreign Key Constraints for Table TQC_ACC_CONTACTS_PWD_HIST 
-- 
ALTER TABLE TQ_CRM.TQC_ACC_CONTACTS_PWD_HIST ADD (
  CONSTRAINT ACCPH_PK
  PRIMARY KEY
  (ACCPH_CODE)
  USING INDEX TQ_CRM.ACCPH_PK
  ENABLE VALIDATE);