-- 
-- Foreign Key Constraints for Table TQC_AGENCY_ACTIVITIES 
-- 
ALTER TABLE TQ_CRM.TQC_AGENCY_ACTIVITIES ADD (
  CONSTRAINT AAC_ACTY_FK 
  FOREIGN KEY (AAC_ACTY_CODE) 
  REFERENCES TQ_CRM.TQC_ACTIVITY_TYPES (ACTY_CODE)
  ENABLE VALIDATE);