-- 
-- Non Foreign Key Constraints for Table TQC_CLIENT_CONTACTS 
-- 
ALTER TABLE TQ_CRM.TQC_CLIENT_CONTACTS ADD (
  CONSTRAINT TQC_CLIENT_CONTACTS_PK
  PRIMARY KEY
  (CLCO_CODE)
  USING INDEX TQ_CRM.TQC_CLIENT_CONTACTS_PK
  ENABLE VALIDATE);