-- 
-- Non Foreign Key Constraints for Table TQC_CURRENCY_DENOMINATIONS 
-- 
ALTER TABLE TQ_CRM.TQC_CURRENCY_DENOMINATIONS ADD (
  CONSTRAINT TQC_CURR_DENOMINATION_PK
  PRIMARY KEY
  (CUD_CODE)
  USING INDEX TQ_CRM.TQC_CURR_DENOMINATION_PK
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_CURRENCY_DENOMINATIONS ADD (
  CONSTRAINT TQC_CURR_DENOMINATION_UK
  UNIQUE (CUD_CUR_CODE, CUD_VALUE, CUD_WEF)
  USING INDEX TQ_CRM.TQC_CURR_DENOMINATION_UK
  ENABLE VALIDATE);