-- 
-- Non Foreign Key Constraints for Table TQC_BRANCH_DEPARTMENTS 
-- 
ALTER TABLE TQ_CRM.TQC_BRANCH_DEPARTMENTS ADD (
  CONSTRAINT TQC_BRANCH_DEPARTMENT_PK
  PRIMARY KEY
  (BDEP_CODE)
  USING INDEX TQ_CRM.TQC_BRANCH_DEPARTMENT_PK
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_BRANCH_DEPARTMENTS ADD (
  CONSTRAINT TQC_BRANCH_DEPARTMENT_UK
  UNIQUE (BDEP_BRN_CODE, BDEP_DEP_CODE, BDEP_WEF)
  USING INDEX TQ_CRM.TQC_BRANCH_DEPARTMENT_UK
  ENABLE VALIDATE);