-- 
-- Non Foreign Key Constraints for Table TQC_WEB_SYSTEMS 
-- 
ALTER TABLE TQ_CRM.TQC_WEB_SYSTEMS ADD (
  CONSTRAINT TQC_WEB_SYSTEM_PK
  PRIMARY KEY
  (SYS_CODE)
  USING INDEX TQ_CRM.TQC_WEB_SYSTEM_PK
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_WEB_SYSTEMS ADD (
  CONSTRAINT TQC_WEB_SYSTEM_UK
  UNIQUE (SYS_SHT_DESC)
  USING INDEX TQ_CRM.TQC_WEB_SYSTEM_UK
  ENABLE VALIDATE);