-- 
-- Non Foreign Key Constraints for Table TQC_SYSTEM_OBJECTS 
-- 
ALTER TABLE TQ_CRM.TQC_SYSTEM_OBJECTS ADD (
  CONSTRAINT OBJ_PK
  PRIMARY KEY
  (OBJ_CODE)
  USING INDEX TQ_CRM.OBJ_PK
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_SYSTEM_OBJECTS ADD (
  CONSTRAINT OBJ_UK
  UNIQUE (OBJ_NAME)
  USING INDEX TQ_CRM.OBJ_UK
  ENABLE VALIDATE);