-- 
-- Non Foreign Key Constraints for Table TQC_CAMPAIGNS 
-- 
ALTER TABLE TQ_CRM.TQC_CAMPAIGNS ADD (
  CONSTRAINT TQC_CAMPAIGNS_PK
  PRIMARY KEY
  (CMP_CODE)
  USING INDEX TQ_CRM.TQC_CAMPAIGNS_PK
  ENABLE VALIDATE);