-- 
-- Non Foreign Key Constraints for Table TQC_SYSTEM_ROUTINES 
-- 
ALTER TABLE TQ_CRM.TQC_SYSTEM_ROUTINES ADD (
  CONSTRAINT TQC_SYSTEM_ROUTINES_PK
  PRIMARY KEY
  (TSR_CODE)
  USING INDEX TQ_CRM.TQC_SYSTEM_ROUTINES_PK
  ENABLE VALIDATE);