-- 
-- Foreign Key Constraints for Table TQC_EMAIL_DMS_REPORTS 
-- 
ALTER TABLE TQ_CRM.TQC_EMAIL_DMS_REPORTS ADD (
  CONSTRAINT TQC_EMAIL_DMS_REPORTS_R01 
  FOREIGN KEY (EMRPT_SPRR_CODE) 
  REFERENCES TQ_CRM.TQC_SYS_PROCESS_REPORTS (SPRR_CODE)
  ENABLE VALIDATE);