-- 
-- Foreign Key Constraints for Table TQC_ACTIVITY_PARTICIPANTS 
-- 
ALTER TABLE TQ_CRM.TQC_ACTIVITY_PARTICIPANTS ADD (
  CONSTRAINT PARTICIP_ACT_CODE_FK 
  FOREIGN KEY (PARTICIP_ACT_CODE) 
  REFERENCES TQ_CRM.TQC_ACTIVITIES (ACT_CODE)
  ENABLE VALIDATE);