-- 
-- Non Foreign Key Constraints for Table TQC_ACTIVITY_TASKS 
-- 
ALTER TABLE TQ_CRM.TQC_ACTIVITY_TASKS ADD (
  CONSTRAINT TQC_ACTIVITY_TASKS_PK
  PRIMARY KEY
  (AT_CODE)
  USING INDEX TQ_CRM.TQC_ACTIVITY_TASKS_PK
  ENABLE VALIDATE);