-- 
-- Non Foreign Key Constraints for Table TQC_CLIENT_TEMP 
-- 
ALTER TABLE TQ_CRM.TQC_CLIENT_TEMP ADD (
  CONSTRAINT CLN_PK
  PRIMARY KEY
  (CLN_CODE)
  USING INDEX TQ_CRM.CLNAGN_PK
  ENABLE VALIDATE);