-- 
-- Non Foreign Key Constraints for Table TQC_DOCUMENTS_REGISTER 
-- 
ALTER TABLE TQ_CRM.TQC_DOCUMENTS_REGISTER ADD (
  CONSTRAINT PK_TQC_DOCR_PK
  PRIMARY KEY
  (DOCR_ID)
  USING INDEX TQ_CRM.PK_TQC_DOCR_PK
  ENABLE VALIDATE);