-- 
-- Non Foreign Key Constraints for Table TQC_LEADS_STATUSES 
-- 
ALTER TABLE TQ_CRM.TQC_LEADS_STATUSES ADD (
  CONSTRAINT LSTS_PK
  PRIMARY KEY
  (LSTS_CODE)
  USING INDEX TQ_CRM.LSTS_PK
  ENABLE VALIDATE);