-- 
-- Non Foreign Key Constraints for Table TQC_DISTRICTS 
-- 
ALTER TABLE TQ_CRM.TQC_DISTRICTS ADD (
  CONSTRAINT TQC_DISTRICTS_PK
  PRIMARY KEY
  (DIST_CODE)
  USING INDEX TQ_CRM.TQC_DISTRICTS_PK
  ENABLE VALIDATE);