-- 
-- Non Foreign Key Constraints for Table TQC_QRTZ_LOCKS 
-- 
ALTER TABLE TQ_CRM.TQC_QRTZ_LOCKS ADD (
  CONSTRAINT TQC_QRTZ_LOCKS_PK
  PRIMARY KEY
  (SCHED_NAME, LOCK_NAME)
  USING INDEX TQ_CRM.TQC_QRTZ_LOCKS_PK
  ENABLE VALIDATE);