-- 
-- Non Foreign Key Constraints for Table TQC_COURTS_NAME 
-- 
ALTER TABLE TQ_CRM.TQC_COURTS_NAME ADD (
  CONSTRAINT TQC_COURTS_NAME_PK
  PRIMARY KEY
  (CTN_CODE)
  USING INDEX TQ_CRM.TQC_COURTS_NAME_PK
  ENABLE VALIDATE);