-- 
-- Non Foreign Key Constraints for Table TQC_SYSTEM_ROLES 
-- 
ALTER TABLE TQ_CRM.TQC_SYSTEM_ROLES ADD (
  CONSTRAINT SRL_PK
  PRIMARY KEY
  (SRL_CODE)
  USING INDEX TQ_CRM.SRL_PK
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_SYSTEM_ROLES ADD (
  CONSTRAINT TQC_SRL_UK
  UNIQUE (SRL_SHT_DESC, SRL_SYS_CODE)
  USING INDEX TQ_CRM.TQC_SRL_UK
  ENABLE VALIDATE);