-- 
-- Non Foreign Key Constraints for Table TQC_ERROR_LOG 
-- 
ALTER TABLE TQ_CRM.TQC_ERROR_LOG ADD (
  CONSTRAINT TQC_ERROR_LOG_PK
  PRIMARY KEY
  (ERRL_ID)
  USING INDEX TQ_CRM.TQC_LOG_PK
  ENABLE VALIDATE);