-- 
-- Non Foreign Key Constraints for Table TQC_QRTZ_CALENDARS 
-- 
ALTER TABLE TQ_CRM.TQC_QRTZ_CALENDARS ADD (
  CONSTRAINT TQC_QRTZ_CALENDARS_PK
  PRIMARY KEY
  (SCHED_NAME, CALENDAR_NAME)
  USING INDEX TQ_CRM.TQC_QRTZ_CALENDARS_PK
  ENABLE VALIDATE);