-- 
-- Non Foreign Key Constraints for Table TQC_AGENCY_DIRECTORS 
-- 
ALTER TABLE TQ_CRM.TQC_AGENCY_DIRECTORS ADD (
  CONSTRAINT PK_TQC_AGENCY_DIRECTORS
  PRIMARY KEY
  (ADIR_CODE)
  USING INDEX TQ_CRM.PK_TQC_AGENCY_DIRECTORS
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_AGENCY_DIRECTORS ADD (
  CONSTRAINT AGENCY_PRINCIPLE_DIR_FK
  UNIQUE (ADIR_PRINCIPLE, ADIR_AGN_CODE)
  USING INDEX TQ_CRM.AGENCY_PRINCIPLE_DIR_FK
  ENABLE VALIDATE);