-- 
-- Non Foreign Key Constraints for Table TQC_SERV_REQUESTS 
-- 
ALTER TABLE TQ_CRM.TQC_SERV_REQUESTS ADD (
  CONSTRAINT TQC_SERV_REQUESTS_C01
  CHECK (TSR_COMM_MODE IN ('SMS','EMAIL','LETTER','PHONE-CALL'))
  ENABLE VALIDATE);