-- 
-- Foreign Key Constraints for Table TQC_EFT_DETAIL 
-- 
ALTER TABLE TQ_CRM.TQC_EFT_DETAIL ADD (
  CONSTRAINT FK_ED_01 
  FOREIGN KEY (ED_EH_CODE) 
  REFERENCES TQ_CRM.TQC_EFT_HEADER (EH_CODE)
  ENABLE VALIDATE);