-- 
-- Non Foreign Key Constraints for Table TQC_REQUIRED_DOCS 
-- 
ALTER TABLE TQ_CRM.TQC_REQUIRED_DOCS ADD (
  CONSTRAINT TQC_REQUIRED_DOCS_PK
  PRIMARY KEY
  (RQD_CODE)
  USING INDEX TQ_CRM.TQC_REQUIRED_DOCS_PK
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_REQUIRED_DOCS ADD (
  CONSTRAINT RQD_UNIQUE
  UNIQUE (RQD_SYS_CODE, RQD_SPTA_CODE, RQD_SPT_CODE, RQC_RDOC_ID)
  USING INDEX TQ_CRM.RQD_UNIQUE
  ENABLE VALIDATE);