-- 
-- Non Foreign Key Constraints for Table TQC_DOC_REQRD_SUBMTD 
-- 
ALTER TABLE TQ_CRM.TQC_DOC_REQRD_SUBMTD ADD (
  CONSTRAINT TQC_DOC_REQRD_SUBMTD_PK
  PRIMARY KEY
  (TQDOCR_CODE)
  USING INDEX TQ_CRM.TQC_DOC_REQRD_SUBMTD_PK
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_DOC_REQRD_SUBMTD ADD (
  UNIQUE (TQDOCR_DOCR_CODE, TQDOCR_CLNT_CODE, TQDOCR_DATE_S)
  USING INDEX
    TABLESPACE CRMDATA
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MAXSIZE          UNLIMITED
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                FREELISTS        1
                FREELIST GROUPS  1
                BUFFER_POOL      DEFAULT
               )
  ENABLE VALIDATE);