-- 
-- Foreign Key Constraints for Table TQC_SYS_SUBUNITS_OPTIONS 
-- 
ALTER TABLE TQ_CRM.TQC_SYS_SUBUNITS_OPTIONS ADD (
  CONSTRAINT TQC_SYS_SUBUNITS_OPTIONS_R01 
  FOREIGN KEY (TSSO_TSMSD_CODE) 
  REFERENCES TQ_CRM.TQC_SYS_MOD_SUBUNITS_DETAILS (TSMSD_CODE)
  ENABLE VALIDATE);