-- 
-- Non Foreign Key Constraints for Table TQC_KB_CONTENT 
-- 
ALTER TABLE TQ_CRM.TQC_KB_CONTENT ADD (
  CONSTRAINT TQC_KB_CONTENT_PK
  PRIMARY KEY
  (TKBC_ID)
  USING INDEX TQ_CRM.TQC_KB_CONTENT_PK
  ENABLE VALIDATE);