-- 
-- Foreign Key Constraints for Table TQC_ACTIVITY_NOTES 
-- 
ALTER TABLE TQ_CRM.TQC_ACTIVITY_NOTES ADD (
  CONSTRAINT ANT_ACT_CODE_FK 
  FOREIGN KEY (ANT_ACT_CODE) 
  REFERENCES TQ_CRM.TQC_ACTIVITIES (ACT_CODE)
  ENABLE VALIDATE);