-- 
-- Non Foreign Key Constraints for Table TQC_QRTZ_SIMPLE_TRIGGERS 
-- 
ALTER TABLE TQ_CRM.TQC_QRTZ_SIMPLE_TRIGGERS ADD (
  CONSTRAINT TQC_QRTZ_SIMPLE_TRIG_PK
  PRIMARY KEY
  (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
  USING INDEX TQ_CRM.TQC_QRTZ_SIMPLE_TRIG_PK
  ENABLE VALIDATE);