-- 
-- Non Foreign Key Constraints for Table TQC_LEADS_ACTIVITIES 
-- 
ALTER TABLE TQ_CRM.TQC_LEADS_ACTIVITIES ADD (
  CONSTRAINT TQC_LEADS_ACTIVITIES_PK
  PRIMARY KEY
  (LACTS_CODE)
  USING INDEX TQ_CRM.TQC_LEADS_ACTIVITIES_PK
  ENABLE VALIDATE);