-- 
-- Non Foreign Key Constraints for Table TQC_USER_WEB_SYSTEM_AUTH_ROLES 
-- 
ALTER TABLE TQ_CRM.TQC_USER_WEB_SYSTEM_AUTH_ROLES ADD (
  CONSTRAINT UAR_WEB_PK
  PRIMARY KEY
  (USAR_USR_CODE, USAR_SAR_CODE, USAR_GRANT_DATE)
  USING INDEX TQ_CRM.UAR_WEB_PK
  ENABLE VALIDATE);