-- 
-- Non Foreign Key Constraints for Table TQC_BANK_BRANCHES 
-- 
ALTER TABLE TQ_CRM.TQC_BANK_BRANCHES ADD (
  CHECK (BBR_EFT_SUPPORTED IN ('Y', 'N'))
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_BANK_BRANCHES ADD (
  CHECK (BBR_EFT_SUPPORTED IN ('Y', 'N'))
  ENABLE VALIDATE);