-- 
-- Non Foreign Key Constraints for Table TQC_BUSINESS_PERSONS 
-- 
ALTER TABLE TQ_CRM.TQC_BUSINESS_PERSONS ADD (
  CONSTRAINT BPN_CODE_PK
  PRIMARY KEY
  (BPN_CODE)
  USING INDEX TQ_CRM.BPN_CODE_PK
  ENABLE VALIDATE);