-- 
-- Non Foreign Key Constraints for Table TQC_AGENCY_HOLDING_COMPANY 
-- 
ALTER TABLE TQ_CRM.TQC_AGENCY_HOLDING_COMPANY ADD (
  CONSTRAINT PK_TQC_AGENCY_HOLDING_COMPANY
  PRIMARY KEY
  (AHC_CODE)
  USING INDEX TQ_CRM.PK_TQC_AGENCY_HOLDING_COMPANY
  ENABLE VALIDATE);