-- 
-- Foreign Key Constraints for Table TQC_SUBDIVISIONS 
-- 
ALTER TABLE TQ_CRM.TQC_SUBDIVISIONS ADD (
  CONSTRAINT DIV_CODE_FK 
  FOREIGN KEY (SDIV_DIV_CODE) 
  REFERENCES TQ_CRM.TQC_DIVISIONS (DIV_CODE)
  ENABLE VALIDATE);