-- 
-- Non Foreign Key Constraints for Table TQC_SYSTEM_AUTH_AREAS 
-- 
ALTER TABLE TQ_CRM.TQC_SYSTEM_AUTH_AREAS ADD (
  CONSTRAINT PK_TQC_SYSTEM_AUTH_AREAS
  PRIMARY KEY
  (SAA_CODE)
  USING INDEX TQ_CRM.PK_TQC_SYSTEM_AUTH_AREAS
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_SYSTEM_AUTH_AREAS ADD (
  CONSTRAINT TQC_SAA_UK
  UNIQUE (SAA_CODE, SAA_SYS_CODE)
  USING INDEX TQ_CRM.TQC_SAA_UK
  ENABLE VALIDATE);