-- 
-- Non Foreign Key Constraints for Table TQC_ACTIVITY_NOTES 
-- 
ALTER TABLE TQ_CRM.TQC_ACTIVITY_NOTES ADD (
  CONSTRAINT TQC_ACTIVITY_NOTES_AND_ATTA_PK
  PRIMARY KEY
  (ANT_CODE)
  USING INDEX TQ_CRM.TQC_ACTIVITY_NOTES_AND_ATTA_PK
  ENABLE VALIDATE);