-- 
-- Non Foreign Key Constraints for Table TQC_AGENCY_REFEREES 
-- 
ALTER TABLE TQ_CRM.TQC_AGENCY_REFEREES ADD (
  CONSTRAINT TQC_AGENCY_REFEREES_PK
  PRIMARY KEY
  (AREF_CODE)
  USING INDEX TQ_CRM.TQC_AGENCY_REFEREES_PK
  ENABLE VALIDATE);