-- 
-- Non Foreign Key Constraints for Table TQC_PRIORITY_LEVELS 
-- 
ALTER TABLE TQ_CRM.TQC_PRIORITY_LEVELS ADD (
  CONSTRAINT TQC_PRIORITY_LEVELS_PK
  PRIMARY KEY
  (PRL_CODE)
  USING INDEX TQ_CRM.TQC_PRIORITY_LEVELS_PK
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_PRIORITY_LEVELS ADD (
  CONSTRAINT TQC_PRIORITY_LEVELS_U01
  UNIQUE (PRL_SHT_DESCRIPTION)
  USING INDEX TQ_CRM.TQC_PRIORITY_LEVELS_U01
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_PRIORITY_LEVELS ADD (
  CONSTRAINT TQC_PRIORITY_LEVELS_U02
  UNIQUE (PRL_DESCRIPTION)
  USING INDEX TQ_CRM.TQC_PRIORITY_LEVELS_U02
  ENABLE VALIDATE);