-- 
-- Non Foreign Key Constraints for Table TQC_DEP_INCIDENT_TYPES 
-- 
ALTER TABLE TQ_CRM.TQC_DEP_INCIDENT_TYPES ADD (
  CONSTRAINT DEPICT_PK
  PRIMARY KEY
  (DEPICT_CODE)
  USING INDEX TQ_CRM.DEPICT_PK
  ENABLE VALIDATE);