-- 
-- Non Foreign Key Constraints for Table TQC_ADMIN_REGIONS 
-- 
ALTER TABLE TQ_CRM.TQC_ADMIN_REGIONS ADD (
  CONSTRAINT TQC_ADMIN_REGIONS_PK
  PRIMARY KEY
  (ADM_REG_CODE)
  USING INDEX TQ_CRM.TQC_ADMIN_REGIONS_PK
  ENABLE VALIDATE);