-- 
-- Non Foreign Key Constraints for Table TQC_HOUSEHOLDS 
-- 
ALTER TABLE TQ_CRM.TQC_HOUSEHOLDS ADD (
  CONSTRAINT TQC_HOUSEHOLDS_PK
  PRIMARY KEY
  (HH_ID)
  USING INDEX TQ_CRM.TQC_HOUSEHOLDS_PK
  ENABLE VALIDATE);