-- 
-- Foreign Key Constraints for Table TQC_LEAD_COMMENTS 
-- 
ALTER TABLE TQ_CRM.TQC_LEAD_COMMENTS ADD (
  CONSTRAINT LCMNT_LDS_FK 
  FOREIGN KEY (LCMNT_LDS_CODE) 
  REFERENCES TQ_CRM.TQC_LEADS (LDS_CODE)
  ENABLE VALIDATE);