-- 
-- Non Foreign Key Constraints for Table TQC_DIRECT_DEBIT_REPORTS 
-- 
ALTER TABLE TQ_CRM.TQC_DIRECT_DEBIT_REPORTS ADD (
  CONSTRAINT TQC_DIRECT_DEBIT_REPORTS_PK
  PRIMARY KEY
  (DDR_CODE)
  USING INDEX TQ_CRM.TQC_DIRECT_DEBIT_REPORTS_PK
  ENABLE VALIDATE);