-- 
-- Non Foreign Key Constraints for Table TQC_SPR_CONTACT_PERSONS 
-- 
ALTER TABLE TQ_CRM.TQC_SPR_CONTACT_PERSONS ADD (
  CONSTRAINT TQC_SPR_CONTACT_PERSONS_PK
  PRIMARY KEY
  (SPR_CNT_CODE)
  USING INDEX TQ_CRM.TQC_SPR_CONTACT_PERSONS_PK
  ENABLE VALIDATE);