-- 
-- Foreign Key Constraints for Table TQC_USER_SUB_DIVISIONS 
-- 
ALTER TABLE TQ_CRM.TQC_USER_SUB_DIVISIONS ADD (
  FOREIGN KEY (USSD_SDIV_CODE) 
  REFERENCES TQ_CRM.TQC_SUBDIVISIONS (SDIV_CODE)
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_USER_SUB_DIVISIONS ADD (
  FOREIGN KEY (USSD_USD_CODE) 
  REFERENCES TQ_CRM.TQC_USER_DIVISIONS (USD_CODE)
  ENABLE VALIDATE);