-- 
-- Non Foreign Key Constraints for Table TQC_DIRECT_DEBIT_DETAIL 
-- 
ALTER TABLE TQ_CRM.TQC_DIRECT_DEBIT_DETAIL ADD (
  CONSTRAINT DDD_RECEIPTED_CHK
  CHECK (DDD_RECEIPTED IN ('N','Y'))
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_DIRECT_DEBIT_DETAIL ADD (
  CONSTRAINT DDD_STATUS_CHK
  CHECK (DDD_STATUS IN ('D','A','F','R'))
  ENABLE VALIDATE);