-- 
-- Foreign Key Constraints for Table TQC_BRANCH_PRINTERS 
-- 
ALTER TABLE TQ_CRM.TQC_BRANCH_PRINTERS ADD (
  CONSTRAINT TQC_BRANCH_PRINTERS_FK 
  FOREIGN KEY (BRP_DIV_CODE) 
  REFERENCES TQ_CRM.TQC_DIVISIONS (DIV_CODE)
  ENABLE VALIDATE);