-- 
-- Non Foreign Key Constraints for Table TQC_USERS 
-- 
ALTER TABLE TQ_CRM.TQC_USERS ADD (
  CONSTRAINT CHK_USR_SIGN
  CHECK (USR_SIGN IN ('Y','N'))
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_USERS ADD (
  CONSTRAINT USR_TYPE_CHK
  CHECK (USR_TYPE IN ('U','G'))
  ENABLE VALIDATE);