-- 
-- Non Foreign Key Constraints for Table TQC_MENU 
-- 
ALTER TABLE TQ_CRM.TQC_MENU ADD (
  CONSTRAINT MENU_ORG_TYPE_SHOW_CHK
  CHECK (MENU_ORG_TYPE_SHOW IN ('INS','BNK','BRK','ALL'))
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_MENU ADD (
  CONSTRAINT PK_TQC_MENU
  PRIMARY KEY
  (MENU_CODE)
  USING INDEX TQ_CRM.PK_TQC_MENU
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_MENU ADD (
  CONSTRAINT TQC_MENU_UK
  UNIQUE (MENU_MENU_CODE, MENU_NAME, MENU_SYS_CODE)
  USING INDEX TQ_CRM.TQC_MENU_UK
  ENABLE VALIDATE);