-- 
-- Non Foreign Key Constraints for Table TQC_ORG_SUBDIVISIONS 
-- 
ALTER TABLE TQ_CRM.TQC_ORG_SUBDIVISIONS ADD (
  CONSTRAINT TQC_ORG_SUBDIVISIONS_U01
  UNIQUE (OSD_ID)
  USING INDEX TQ_CRM.TQC_ORG_SUBDIVISIONS_U01
  ENABLE VALIDATE);