-- 
-- Non Foreign Key Constraints for Table TQC_ORG_RATING_STARNDARDS 
-- 
ALTER TABLE TQ_CRM.TQC_ORG_RATING_STARNDARDS ADD (
  CONSTRAINT TQC_ORG_RATING_STARNDARDS_PK
  PRIMARY KEY
  (ORS_CODE)
  USING INDEX TQ_CRM.TQC_ORG_RATING_STARNDARDS_PK
  ENABLE VALIDATE);