-- 
-- Foreign Key Constraints for Table TQC_CAMPAIGN_PRODUCTS 
-- 
ALTER TABLE TQ_CRM.TQC_CAMPAIGN_PRODUCTS ADD (
  CONSTRAINT TQC_CAMPAIGNS_FK 
  FOREIGN KEY (CPRO_CODE) 
  REFERENCES TQ_CRM.TQC_CAMPAIGNS (CMP_CODE)
  DISABLE NOVALIDATE);