-- 
-- Non Foreign Key Constraints for Table TQC_SERVICE_PROVIDER_REG 
-- 
ALTER TABLE TQ_CRM.TQC_SERVICE_PROVIDER_REG ADD (
  CONSTRAINT PK_TQC_SERVICE_PROVIDER_REG
  PRIMARY KEY
  (SREG_CODE)
  USING INDEX TQ_CRM.PK_TQC_SERVICE_PROVIDER_REG
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_SERVICE_PROVIDER_REG ADD (
  CONSTRAINT TQC_SREG_UK
  UNIQUE (SREG_YEAR, SREG_SPR_CODE)
  USING INDEX TQ_CRM.TQC_SREG_UK
  ENABLE VALIDATE);