-- 
-- Non Foreign Key Constraints for Table TQC_SYS_POSTS 
-- 
ALTER TABLE TQ_CRM.TQC_SYS_POSTS ADD (
  CONSTRAINT SPOST_PK
  PRIMARY KEY
  (SPOST_CODE)
  USING INDEX TQ_CRM.SPOST_PK
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_SYS_POSTS ADD (
  CONSTRAINT SPOST_UK
  UNIQUE (SPOST_SYS_CODE, SPOST_SHT_DESC)
  USING INDEX TQ_CRM.SPOST_UK
  ENABLE VALIDATE);