-- 
-- Non Foreign Key Constraints for Table TQC_QRTZ_SCHEDULER_STATE 
-- 
ALTER TABLE TQ_CRM.TQC_QRTZ_SCHEDULER_STATE ADD (
  CONSTRAINT TQC_QRTZ_SCHEDULER_STATE_PK
  PRIMARY KEY
  (SCHED_NAME, INSTANCE_NAME)
  USING INDEX TQ_CRM.TQC_QRTZ_SCHEDULER_STATE_PK
  ENABLE VALIDATE);