-- 
-- Non Foreign Key Constraints for Table TQC_ACTIVITY_PARTICIPANTS 
-- 
ALTER TABLE TQ_CRM.TQC_ACTIVITY_PARTICIPANTS ADD (
  CONSTRAINT TQC_ACTIVITY_PARTICIPANTS_PK
  PRIMARY KEY
  (PARTICIP_ID)
  USING INDEX TQ_CRM.TQC_ACTIVITY_PARTICIPANTS_PK
  ENABLE VALIDATE);