-- 
-- Non Foreign Key Constraints for Table TQC_SYS_MOD_SUBUNITS 
-- 
ALTER TABLE TQ_CRM.TQC_SYS_MOD_SUBUNITS ADD (
  CONSTRAINT TQC_SYS_MOD_SUBUNITS_PK
  PRIMARY KEY
  (TSMS_CODE)
  USING INDEX TQ_CRM.TQC_SYS_MOD_SUBUNITS_PK
  ENABLE VALIDATE);