-- 
-- Non Foreign Key Constraints for Table TQC_BANCASSURANCE_BRANCHES 
-- 
ALTER TABLE TQ_CRM.TQC_BANCASSURANCE_BRANCHES ADD (
  CONSTRAINT BBB_CODE_PK
  PRIMARY KEY
  (BBB_CODE)
  USING INDEX TQ_CRM.BBB_CODE_PK
  ENABLE VALIDATE);