-- 
-- Non Foreign Key Constraints for Table TQC_SYS_PRCSS_SUBAREA_LMTS 
-- 
ALTER TABLE TQ_CRM.TQC_SYS_PRCSS_SUBAREA_LMTS ADD (
  CONSTRAINT SPSAT_LEVEL_CHK
  CHECK (SPSAT_NO_OF_LEVEL >= 1  )
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_SYS_PRCSS_SUBAREA_LMTS ADD (
  CONSTRAINT SPSAT_PK
  PRIMARY KEY
  (SPSAT_CODE)
  USING INDEX TQ_CRM.SPSAT_PK
  ENABLE VALIDATE);