-- 
-- Foreign Key Constraints for Table TQC_USER_DIVISIONS 
-- 
ALTER TABLE TQ_CRM.TQC_USER_DIVISIONS ADD (
  FOREIGN KEY (USD_DIV_CODE) 
  REFERENCES TQ_CRM.TQC_DIVISIONS (DIV_CODE)
  ENABLE VALIDATE);