-- 
-- Foreign Key Constraints for Table TQC_KB_CONTENT 
-- 
ALTER TABLE TQ_CRM.TQC_KB_CONTENT ADD (
  CONSTRAINT TQC_KB_CONTENT_R01 
  FOREIGN KEY (TKBC_TKBT_ID) 
  REFERENCES TQ_CRM.TQC_KB_TOPICS (TKBT_ID)
  ENABLE VALIDATE);