-- 
-- Non Foreign Key Constraints for Table TQC_PRODUCT_ATTRIBUTES 
-- 
ALTER TABLE TQ_CRM.TQC_PRODUCT_ATTRIBUTES ADD (
  CONSTRAINT TQC_PRODUCT_ATTRIBUTES_PK
  PRIMARY KEY
  (TPA_CODE)
  USING INDEX TQ_CRM.TQC_PRODUCT_ATTRIBUTES_PK
  ENABLE VALIDATE);