-- 
-- Non Foreign Key Constraints for Table TQC_BRNCH_DIVISIONS 
-- 
ALTER TABLE TQ_CRM.TQC_BRNCH_DIVISIONS ADD (
  CONSTRAINT TQC_BRNCH_DIVISIONS_PK
  PRIMARY KEY
  (BDIV_CODE)
  USING INDEX TQ_CRM.TQC_BRNCH_DIVISIONS_PK
  ENABLE VALIDATE);