-- 
-- Non Foreign Key Constraints for Table TQC_LANGUAGES 
-- 
ALTER TABLE TQ_CRM.TQC_LANGUAGES ADD (
  CONSTRAINT LANG_PKID_CONSTR
  PRIMARY KEY
  (LANG_CODE)
  USING INDEX TQ_CRM.LANG_PKID_CONSTR
  ENABLE VALIDATE);