-- 
-- Non Foreign Key Constraints for Table TQC_EMAIL_ATTACHMENTS 
-- 
ALTER TABLE TQ_CRM.TQC_EMAIL_ATTACHMENTS ADD (
  CONSTRAINT EATT_PK
  PRIMARY KEY
  (EATT_CODE)
  USING INDEX TQ_CRM.EATT_PK
  ENABLE VALIDATE);