-- 
-- Foreign Key Constraints for Table TQC_ACTIVITY_TASKS 
-- 
ALTER TABLE TQ_CRM.TQC_ACTIVITY_TASKS ADD (
  CONSTRAINT AT_ACT_CODE_FK 
  FOREIGN KEY (AT_ACT_CODE) 
  REFERENCES TQ_CRM.TQC_ACTIVITIES (ACT_CODE)
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_ACTIVITY_TASKS ADD (
  CONSTRAINT AT_PRIORITY_CODE_FK 
  FOREIGN KEY (AT_PRIORITY_CODE) 
  REFERENCES TQ_CRM.TQC_PRIORITY_LEVELS (PRL_CODE)
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_ACTIVITY_TASKS ADD (
  CONSTRAINT AT_STATUS_ID_FK 
  FOREIGN KEY (AT_STATUS_ID) 
  REFERENCES TQ_CRM.TQC_STATUSES (STATUS_ID)
  ENABLE VALIDATE);