-- 
-- Non Foreign Key Constraints for Table TQC_CLIENTS 
-- 
ALTER TABLE TQ_CRM.TQC_CLIENTS ADD (
  CONSTRAINT CHK_CLNT_AGNT_STATUS
  CHECK (CLNT_AGNT_STATUS IN ('Y','N'))
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_CLIENTS ADD (
  CONSTRAINT CLNT_UK
  UNIQUE (CLNT_SHT_DESC)
  DISABLE NOVALIDATE);