-- 
-- Non Foreign Key Constraints for Table TQC_SYSTEM_ROLE_MENU 
-- 
ALTER TABLE TQ_CRM.TQC_SYSTEM_ROLE_MENU ADD (
  CONSTRAINT PK_TQC_SYSTEM_ROLE_MENU
  PRIMARY KEY
  (SRM_SRL_CODE, SRM_MENU_CODE, SRM_GRANT_DATE)
  USING INDEX TQ_CRM.PK_TQC_SYSTEM_ROLE_MENU
  ENABLE VALIDATE);