-- 
-- Foreign Key Constraints for Table TQC_AGENCY_SYSTEMS 
-- 
ALTER TABLE TQ_CRM.TQC_AGENCY_SYSTEMS ADD (
  CONSTRAINT TQC_AGENCY_SYSTEMS_R02 
  FOREIGN KEY (ASYS_OSD_ID) 
  REFERENCES TQ_CRM.TQC_ORG_SUBDIVISIONS (OSD_ID)
  ENABLE VALIDATE);