-- 
-- Non Foreign Key Constraints for Table TQC_SMS_RESPONSES 
-- 
ALTER TABLE TQ_CRM.TQC_SMS_RESPONSES ADD (
  CONSTRAINT TQC_SMS_RESPONSES_PK
  PRIMARY KEY
  (SMSR_CODE)
  USING INDEX TQ_CRM.TQC_SMS_RESPONSES_PK
  ENABLE VALIDATE);