-- 
-- Non Foreign Key Constraints for Table TQC_CAMP_ACTIVITIES 
-- 
ALTER TABLE TQ_CRM.TQC_CAMP_ACTIVITIES ADD (
  CONSTRAINT TQC_CMA_PK
  PRIMARY KEY
  (CMA_CODE)
  USING INDEX TQ_CRM.TQC_CMA_PK
  ENABLE VALIDATE);