-- 
-- Non Foreign Key Constraints for Table TQC_DD_FAILED_REMARKS 
-- 
ALTER TABLE TQ_CRM.TQC_DD_FAILED_REMARKS ADD (
  CONSTRAINT TQC_DD_FAILED_REMARKS_PK
  PRIMARY KEY
  (DFR_CODE)
  USING INDEX TQ_CRM.TQC_DD_FAILED_REMARKS_PK
  ENABLE VALIDATE);