-- 
-- Foreign Key Constraints for Table TQC_ORG_RATING_STARNDARDS 
-- 
ALTER TABLE TQ_CRM.TQC_ORG_RATING_STARNDARDS ADD (
  CONSTRAINT RATING_ORGANIZATION_FK 
  FOREIGN KEY (ORS_RORG_CODE) 
  REFERENCES TQ_CRM.TQC_RATING_ORGANIZATIONS (RORG_CODE)
  ENABLE VALIDATE);