-- 
-- Non Foreign Key Constraints for Table TQC_CAMP_CONTACT 
-- 
ALTER TABLE TQ_CRM.TQC_CAMP_CONTACT ADD (
  CONSTRAINT TQC_CAMP_CONTACT_PK
  PRIMARY KEY
  (CMC_CODE)
  USING INDEX TQ_CRM.TQC_CAMP_CONTACT_PK
  ENABLE VALIDATE);