-- 
-- Non Foreign Key Constraints for Table TQC_SEQUENCES 
-- 
ALTER TABLE TQ_CRM.TQC_SEQUENCES ADD (
  CHECK (TSEQ_TYPE IN ('C'))
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_SEQUENCES ADD (
  CHECK (TSEQ_TYPE IN ('C'))
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_SEQUENCES ADD (
  CONSTRAINT TSEQ_NO_TYPE_CHK
  CHECK (TSEQ_NO_TYPE IN ('YBC','YBA','YAA','YAC','PBC','PBA','PAC','PAA'))
  ENABLE VALIDATE);