-- 
-- Non Foreign Key Constraints for Table TQC_TRANSFERS 
-- 
ALTER TABLE TQ_CRM.TQC_TRANSFERS ADD (
  CONSTRAINT TT_CODE_PK
  PRIMARY KEY
  (TT_CODE)
  USING INDEX TQ_CRM.TT_CODE_PK
  ENABLE VALIDATE);