-- 
-- Non Foreign Key Constraints for Table TQC_SYS_SUBUNITS_OPTIONS 
-- 
ALTER TABLE TQ_CRM.TQC_SYS_SUBUNITS_OPTIONS ADD (
  CONSTRAINT TQC_SYS_SUBUNITS_OPTIONS_PK
  PRIMARY KEY
  (TSSO_CODE)
  USING INDEX TQ_CRM.TQC_SYS_SUBUNITS_OPTIONS_PK
  ENABLE VALIDATE);