-- 
-- Foreign Key Constraints for Table TQC_ESCALATION_LEVELS 
-- 
ALTER TABLE TQ_CRM.TQC_ESCALATION_LEVELS ADD (
  CONSTRAINT TQEL_TQES_ID_FK 
  FOREIGN KEY (TQEL_TQES_ID) 
  REFERENCES TQ_CRM.TQC_ESCALATION_SETUPS (TQES_ID)
  ENABLE VALIDATE);