-- 
-- Non Foreign Key Constraints for Table TQC_BRANCH_DEPT_UNITS 
-- 
ALTER TABLE TQ_CRM.TQC_BRANCH_DEPT_UNITS ADD (
  CONSTRAINT TQC_BRANCH_UNIT_PK
  PRIMARY KEY
  (BDU_CODE)
  USING INDEX TQ_CRM.TQC_BRANCH_UNIT_PK
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_BRANCH_DEPT_UNITS ADD (
  CONSTRAINT TQC_BRANCH_UNIT_UK
  UNIQUE (BDU_SHT_DESC)
  USING INDEX TQ_CRM.TQC_BRANCH_UNIT_UK
  ENABLE VALIDATE);