-- 
-- Non Foreign Key Constraints for Table TQC_WEB_PRODUCT_CATEGORIES 
-- 
ALTER TABLE TQ_CRM.TQC_WEB_PRODUCT_CATEGORIES ADD (
  CONSTRAINT TQC_WEB_PRODUCT_CATEGORIES_PK
  PRIMARY KEY
  (TWPC_CODE)
  USING INDEX TQ_CRM.TQC_WEB_PRODUCT_CATEGORIES_PK
  ENABLE VALIDATE);