-- 
-- Non Foreign Key Constraints for Table TQC_CLIENT_ACCOUNTS_AUDIT 
-- 
ALTER TABLE TQ_CRM.TQC_CLIENT_ACCOUNTS_AUDIT ADD (
  CONSTRAINT TQC_CLIENT_ACCOUNTS_AUDIT_PK
  PRIMARY KEY
  (CLNAA_CODE)
  USING INDEX TQ_CRM.TQC_CLIENT_ACCOUNTS_AUDIT_PK
  ENABLE VALIDATE);