-- 
-- Non Foreign Key Constraints for Table TQC_DIVISIONS 
-- 
ALTER TABLE TQ_CRM.TQC_DIVISIONS ADD (
  CONSTRAINT TQC_DIVISIONS_PK
  PRIMARY KEY
  (DIV_CODE)
  USING INDEX TQ_CRM.TQC_DIVISIONS_PK
  ENABLE VALIDATE);