-- 
-- Foreign Key Constraints for Table TQC_AGENCIES 
-- 
ALTER TABLE TQ_CRM.TQC_AGENCIES ADD (
  CONSTRAINT TQC_AGN_AHC_CODE_FK 
  FOREIGN KEY (AGN_AHC_CODE) 
  REFERENCES TQ_CRM.TQC_AGENCY_HOLDING_COMPANY (AHC_CODE)
  ENABLE VALIDATE);