-- 
-- Non Foreign Key Constraints for Table TQC_BRANCH_UNITS 
-- 
ALTER TABLE TQ_CRM.TQC_BRANCH_UNITS ADD (
  CONSTRAINT TQC_BRU_CODE_PK
  PRIMARY KEY
  (BRU_CODE)
  USING INDEX TQ_CRM.TQC_BRU_CODE_PK
  ENABLE VALIDATE);