-- 
-- Non Foreign Key Constraints for Table TQC_SYS_ERR_MODULES 
-- 
ALTER TABLE TQ_CRM.TQC_SYS_ERR_MODULES ADD (
  CONSTRAINT SERRM_PK
  PRIMARY KEY
  (SERRM_CODE)
  USING INDEX TQ_CRM.SERRM_PK
  ENABLE VALIDATE);