-- 
-- Foreign Key Constraints for Table TQC_LEADS_ACTIVITIES 
-- 
ALTER TABLE TQ_CRM.TQC_LEADS_ACTIVITIES ADD (
  CONSTRAINT LACTS_ACT_FK 
  FOREIGN KEY (LACTS_ACT_CODE) 
  REFERENCES TQ_CRM.TQC_ACTIVITIES (ACT_CODE)
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_LEADS_ACTIVITIES ADD (
  CONSTRAINT LACTS_LDS_FK 
  FOREIGN KEY (LACTS_LDS_CODE) 
  REFERENCES TQ_CRM.TQC_LEADS (LDS_CODE)
  ENABLE VALIDATE);