-- 
-- Foreign Key Constraints for Table TQC_CAMP_TARGETS 
-- 
ALTER TABLE TQ_CRM.TQC_CAMP_TARGETS ADD (
  CONSTRAINT CMT_CMP_CODE_FK 
  FOREIGN KEY (CMT_CMP_CODE) 
  REFERENCES TQ_CRM.TQC_CAMPAIGNS (CMP_CODE)
  ENABLE VALIDATE);