-- 
-- Non Foreign Key Constraints for Table TQC_IPRS_DATA 
-- 
ALTER TABLE TQ_CRM.TQC_IPRS_DATA ADD (
  CONSTRAINT TQC_IPRS_PINNO_PK
  UNIQUE (IPRS_PINNO)
  USING INDEX TQ_CRM.TQC_IPRS_PINNO_PK
  ENABLE VALIDATE);