-- 
-- Non Foreign Key Constraints for Table TQC_HOUSEHOLD_DTLS 
-- 
ALTER TABLE TQ_CRM.TQC_HOUSEHOLD_DTLS ADD (
  CONSTRAINT TQC_HOUSEHOLD_DTLS_PK
  PRIMARY KEY
  (HHD_ID)
  USING INDEX TQ_CRM.TQC_HOUSEHOLD_DTLS_PK
  ENABLE VALIDATE);