-- 
-- Foreign Key Constraints for Table TQC_INCIDENTS 
-- 
ALTER TABLE TQ_CRM.TQC_INCIDENTS ADD (
  CONSTRAINT INC_DEPICT_FK 
  FOREIGN KEY (INC_DEPICT_CODE) 
  REFERENCES TQ_CRM.TQC_DEP_INCIDENT_TYPES (DEPICT_CODE)
  ENABLE VALIDATE);