-- 
-- Non Foreign Key Constraints for Table TQC_SPECIALIZATIONS 
-- 
ALTER TABLE TQ_CRM.TQC_SPECIALIZATIONS ADD (
  CONSTRAINT SPZ_CODE_PK
  PRIMARY KEY
  (SPZ_CODE)
  USING INDEX TQ_CRM.SPZ_CODE_PK
  ENABLE VALIDATE);