-- 
-- Non Foreign Key Constraints for Table TQC_KB_TOPICS 
-- 
ALTER TABLE TQ_CRM.TQC_KB_TOPICS ADD (
  CONSTRAINT TQC_KB_TOPICS_PK
  PRIMARY KEY
  (TKBT_ID)
  USING INDEX TQ_CRM.TQC_KB_TOPICS_PK
  ENABLE VALIDATE);