-- 
-- Foreign Key Constraints for Table TQC_DIVISIONS_AUDIT_TRL 
-- 
ALTER TABLE TQ_CRM.TQC_DIVISIONS_AUDIT_TRL ADD (
  FOREIGN KEY (DAUDT_DIV_CODE) 
  REFERENCES TQ_CRM.TQC_DIVISIONS (DIV_CODE)
  ENABLE VALIDATE);