-- 
-- Foreign Key Constraints for Table TQC_PRODUCT_CLIENT_ATTRIBUTES 
-- 
ALTER TABLE TQ_CRM.TQC_PRODUCT_CLIENT_ATTRIBUTES ADD (
  CONSTRAINT PCA_TCA_CODE_FK 
  FOREIGN KEY (PCA_TCA_CODE) 
  REFERENCES TQ_CRM.TQC_CLIENT_ATTRIBUTES (TCA_CODE)
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_PRODUCT_CLIENT_ATTRIBUTES ADD (
  CONSTRAINT PCA_TPA_CODE_FK 
  FOREIGN KEY (PCA_TPA_CODE) 
  REFERENCES TQ_CRM.TQC_PRODUCT_ATTRIBUTES (TPA_CODE)
  ENABLE VALIDATE);