-- 
-- Non Foreign Key Constraints for Table TQC_SYS_POST_LEVELS 
-- 
ALTER TABLE TQ_CRM.TQC_SYS_POST_LEVELS ADD (
  CONSTRAINT SYSPL_PK
  PRIMARY KEY
  (SYSPL_CODE)
  USING INDEX TQ_CRM.SYSPL_PK
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_SYS_POST_LEVELS ADD (
  CONSTRAINT SYSPL_UK
  UNIQUE (SYSPL_SYS_CODE, SYSPL_SHT_DESC)
  USING INDEX TQ_CRM.SYSPL_UK
  ENABLE VALIDATE);