-- 
-- Non Foreign Key Constraints for Table TQC_SUBDIVISIONS 
-- 
ALTER TABLE TQ_CRM.TQC_SUBDIVISIONS ADD (
  CONSTRAINT TQC_SUBDIVISIONS_PK
  PRIMARY KEY
  (SDIV_CODE)
  USING INDEX TQ_CRM.TQC_SUBDIVISIONS_PK
  ENABLE VALIDATE);