-- 
-- Non Foreign Key Constraints for Table TQC_SERV_REQ_ECALATIONS 
-- 
ALTER TABLE TQ_CRM.TQC_SERV_REQ_ECALATIONS ADD (
  CONSTRAINT TQC_SERV_REQ_ECALATIONS_PK
  PRIMARY KEY
  (SRE_CODE)
  USING INDEX TQ_CRM.TQC_SERV_REQ_ECALATIONS_PK
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_SERV_REQ_ECALATIONS ADD (
  CONSTRAINT UK_SRE_SRT_CODE
  UNIQUE (SRE_SRT_CODE)
  USING INDEX TQ_CRM.UK_SRE_SRT_CODE
  ENABLE VALIDATE);