-- 
-- Foreign Key Constraints for Table TQC_BRANCH_UNITS 
-- 
ALTER TABLE TQ_CRM.TQC_BRANCH_UNITS ADD (
  CONSTRAINT BRU_BRA_FK 
  FOREIGN KEY (BRU_BRA_CODE) 
  REFERENCES TQ_CRM.TQC_BRANCH_AGENCIES (BRA_CODE)
  ENABLE VALIDATE);