-- 
-- Foreign Key Constraints for Table TQC_LEADS 
-- 
ALTER TABLE TQ_CRM.TQC_LEADS ADD (
  CONSTRAINT LDS_CAMP_CODE_FK 
  FOREIGN KEY (LDS_CAMP_CODE) 
  REFERENCES TQ_CRM.TQC_CAMPAIGNS (CMP_CODE)
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_LEADS ADD (
  CONSTRAINT LDS_DIV_CODE_FK 
  FOREIGN KEY (LDS_DIV_CODE) 
  REFERENCES TQ_CRM.TQC_DIVISIONS (DIV_CODE)
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_LEADS ADD (
  CONSTRAINT LDS_LDSRC_FK 
  FOREIGN KEY (LDS_LDSRC_CODE) 
  REFERENCES TQ_CRM.TQC_LEADS_SOURCES (LDSRC_CODE)
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_LEADS ADD (
  CONSTRAINT LDS_LSTS_CODE_FK 
  FOREIGN KEY (LDS_LSTS_CODE) 
  REFERENCES TQ_CRM.TQC_LEADS_STATUSES (LSTS_CODE)
  ENABLE VALIDATE);