-- 
-- Non Foreign Key Constraints for Table TQC_SYS_RPT_PARAMETERS 
-- 
ALTER TABLE TQ_CRM.TQC_SYS_RPT_PARAMETERS ADD (
  CHECK (RPTP_PARAM_TYPE IN ('DATE','LOV','BOOL','NUMBER','TEXT','PLOV'))
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_SYS_RPT_PARAMETERS ADD (
  CHECK (RPTP_PARAM_TYPE IN ('DATE','LOV','BOOL','NUMBER','TEXT','PLOV'))
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_SYS_RPT_PARAMETERS ADD (
  CHECK (RPTP_PARAM_TYPE IN ('DATE','LOV','BOOL','NUMBER','TEXT','PLOV'))
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_SYS_RPT_PARAMETERS ADD (
  CHECK (RPTP_PARAM_TYPE IN ('DATE','LOV','BOOL','NUMBER','TEXT','PLOV'))
  ENABLE VALIDATE);