-- 
-- Non Foreign Key Constraints for Table TQC_LEADS 
-- 
ALTER TABLE TQ_CRM.TQC_LEADS ADD (
  CONSTRAINT TQC_LEADS_PK
  PRIMARY KEY
  (LDS_CODE)
  USING INDEX TQ_CRM.TQC_LEADS_PK
  ENABLE VALIDATE);