-- 
-- Non Foreign Key Constraints for Table TQC_BANK_BRANCHES_BRANCHES 
-- 
ALTER TABLE TQ_CRM.TQC_BANK_BRANCHES_BRANCHES ADD (
  CONSTRAINT TQC_BANK_BRANCHES_BRANCHES_PK
  PRIMARY KEY
  (BBB_CODE)
  USING INDEX TQ_CRM.TQC_BANK_BRANCHES_BRANCHES_PK
  ENABLE VALIDATE);