-- 
-- Non Foreign Key Constraints for Table TQC_MSG_TEMPLATES 
-- 
ALTER TABLE TQ_CRM.TQC_MSG_TEMPLATES ADD (
  CONSTRAINT MSGT_TYPE_CHK
  CHECK (MSGT_TYPE IN ('SMS','EMAIL','FAX'))
  ENABLE VALIDATE);