-- 
-- Non Foreign Key Constraints for Table TQC_LEADS_SOURCES 
-- 
ALTER TABLE TQ_CRM.TQC_LEADS_SOURCES ADD (
  CONSTRAINT LDSRC_PK
  PRIMARY KEY
  (LDSRC_CODE)
  USING INDEX TQ_CRM.LDSRC_PK
  ENABLE VALIDATE);