-- 
-- Foreign Key Constraints for Table TQC_WEB_PRODUCTS 
-- 
ALTER TABLE TQ_CRM.TQC_WEB_PRODUCTS ADD (
  CONSTRAINT TQC_AGENCY_ACCOUNTS_FK 
  FOREIGN KEY (TWP_AGA_CODE) 
  REFERENCES TQ_CRM.TQC_AGENCY_ACCOUNTS (AGA_CODE)
  ENABLE VALIDATE);