-- 
-- Non Foreign Key Constraints for Table TQC_ESCALATION_LEVELS 
-- 
ALTER TABLE TQ_CRM.TQC_ESCALATION_LEVELS ADD (
  CONSTRAINT TQC_ESCALATION_LEVELS_PK
  PRIMARY KEY
  (TQEL_ID)
  USING INDEX TQ_CRM.TQC_ESCALATION_LEVELS_PK
  ENABLE VALIDATE);