-- 
-- Non Foreign Key Constraints for Table TQC_CLIENT_ATTRIBUTES 
-- 
ALTER TABLE TQ_CRM.TQC_CLIENT_ATTRIBUTES ADD (
  CONSTRAINT TQC_CLIENT_ATTRIBUTES_PK
  PRIMARY KEY
  (TCA_CODE)
  USING INDEX TQ_CRM.TQC_CLIENT_ATTRIBUTES_PK
  ENABLE VALIDATE);