-- 
-- Non Foreign Key Constraints for Table TQC_STATUSES 
-- 
ALTER TABLE TQ_CRM.TQC_STATUSES ADD (
  CONSTRAINT TQC_STATUSES_PK
  PRIMARY KEY
  (STATUS_ID)
  USING INDEX TQ_CRM.TQC_STATUSES_PK
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_STATUSES ADD (
  CONSTRAINT TQC_STATUSES_U01
  UNIQUE (STATUS_CODE)
  USING INDEX TQ_CRM.TQC_STATUSES_U01
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_STATUSES ADD (
  CONSTRAINT TQC_STATUSES_U02
  UNIQUE (STATUS_DESC)
  USING INDEX TQ_CRM.TQC_STATUSES_U02
  ENABLE VALIDATE);