-- 
-- Non Foreign Key Constraints for Table TQC_AGENCY_ACCOUNTS 
-- 
ALTER TABLE TQ_CRM.TQC_AGENCY_ACCOUNTS ADD (
  CONSTRAINT AGA_STATUS_CK
  CHECK (aga_status IN ('ACTIVE','INACTIVE','SUSPENDED'))
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_AGENCY_ACCOUNTS ADD (
  CONSTRAINT AGA_CODE_PK
  PRIMARY KEY
  (AGA_CODE)
  USING INDEX TQ_CRM.AGA_CODE_PK
  ENABLE VALIDATE);