-- 
-- Non Foreign Key Constraints for Table TQC_QRTZ_FIRED_TRIGGERS 
-- 
ALTER TABLE TQ_CRM.TQC_QRTZ_FIRED_TRIGGERS ADD (
  CONSTRAINT TQC_QRTZ_FIRED_TRIGGER_PK
  PRIMARY KEY
  (SCHED_NAME, ENTRY_ID)
  USING INDEX TQ_CRM.TQC_QRTZ_FIRED_TRIGGER_PK
  ENABLE VALIDATE);