-- 
-- Non Foreign Key Constraints for Table TQC_CAMP_TARGETS 
-- 
ALTER TABLE TQ_CRM.TQC_CAMP_TARGETS ADD (
  CONSTRAINT TQC_CAMP_TARGET_PK
  PRIMARY KEY
  (CMT_CODE)
  USING INDEX TQ_CRM.TQC_CAMP_TARGET_PK
  ENABLE VALIDATE);