-- 
-- Non Foreign Key Constraints for Table TQC_CLIENT_EMPLOYERS 
-- 
ALTER TABLE TQ_CRM.TQC_CLIENT_EMPLOYERS ADD (
  CONSTRAINT CLIENT_EMPLOYER_CODE_PK
  PRIMARY KEY
  (CODE)
  USING INDEX TQ_CRM.CLIENT_EMPLOYER_CODE_PK
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_CLIENT_EMPLOYERS ADD (
  CONSTRAINT CLIENT_EMPLOYER_NAME_UK
  UNIQUE (CLNT_CODE, EMPLOYER_NAME)
  USING INDEX TQ_CRM.CLIENT_EMPLOYER_NAME_UK
  ENABLE VALIDATE);