-- 
-- Non Foreign Key Constraints for Table TQC_QRTZ_PAUSED_TRIGGER_GRPS 
-- 
ALTER TABLE TQ_CRM.TQC_QRTZ_PAUSED_TRIGGER_GRPS ADD (
  CONSTRAINT TQC_QRTZ_PAUSED_TRIG_GRPS_PK
  PRIMARY KEY
  (SCHED_NAME, TRIGGER_GROUP)
  USING INDEX TQ_CRM.TQC_QRTZ_PAUSED_TRIG_GRPS_PK
  ENABLE VALIDATE);