-- 
-- Foreign Key Constraints for Table TQC_ACTIVITIES 
-- 
ALTER TABLE TQ_CRM.TQC_ACTIVITIES ADD (
  CONSTRAINT ACT_ACTY_CODE_FK 
  FOREIGN KEY (ACT_ACTY_CODE) 
  REFERENCES TQ_CRM.TQC_ACTIVITY_TYPES (ACTY_CODE)
  ENABLE VALIDATE);

ALTER TABLE TQ_CRM.TQC_ACTIVITIES ADD (
  CONSTRAINT ACT_STATUS_ID_FK 
  FOREIGN KEY (ACT_STATUS_ID) 
  REFERENCES TQ_CRM.TQC_STATUSES (STATUS_ID)
  ENABLE VALIDATE);