--
-- AIICO_LOAD_AGENTS  (Table) 
--
CREATE TABLE TQ_CRM.AIICO_LOAD_AGENTS
(
  AGENT_CODE       VARCHAR2(30 BYTE),
  AGENT_UNIT_CODE  VARCHAR2(30 BYTE),
  AGENCY_CODE      VARCHAR2(30 BYTE),
  JOINING_DATE     VARCHAR2(30 BYTE),
  AGENT_NAME       VARCHAR2(30 BYTE),
  AGENT_ADDRESS    VARCHAR2(300 BYTE),
  TELEPHONE        VARCHAR2(30 BYTE),
  FAX              VARCHAR2(30 BYTE),
  GENDER           VARCHAR2(30 BYTE),
  LICENSE          VARCHAR2(30 BYTE),
  TERMINATED       VARCHAR2(30 BYTE),
  TERMINATED_DATE  VARCHAR2(30 BYTE),
  AGENT_STATUS     VARCHAR2(30 BYTE),
  PORTED           VARCHAR2(5 BYTE),
  PORTED_ERR_MSG   VARCHAR2(1000 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;