--
-- CAL_EVENTS  (Table) 
--
CREATE TABLE TQ_CRM.CAL_EVENTS
(
  CAL_ID                     VARCHAR2(200 BYTE),
  CAL_SUMMARY                VARCHAR2(4000 BYTE),
  CAL_START_TIME             DATE,
  CAL_END_TIME               DATE,
  CAL_IS_ALL_DAY_EVENT       NUMBER             DEFAULT 0,
  CAL_LOCATION               VARCHAR2(4000 BYTE),
  CAL_DESCRIPTION            VARCHAR2(4000 BYTE),
  CAL_CATEGORY_ID            VARCHAR2(200 BYTE),
  CAL_PRIORITY               NUMBER,
  CAL_COMMUNITY_ID           VARCHAR2(256 BYTE),
  CAL_PARENT_EVENT_ID        VARCHAR2(200 BYTE),
  CAL_IS_RECURRING           NUMBER             DEFAULT 0,
  CAL_OPT_ATTRIBUTE          NUMBER,
  CAL_OPT_ATTRIBUTE1         VARCHAR2(4000 BYTE),
  CAL_OPT_ATTRIBUTE2         VARCHAR2(4000 BYTE),
  CAL_CREATE_DATE            TIMESTAMP(6),
  CAL_LAST_UPDATE_DATE       TIMESTAMP(6),
  CAL_CREATE_USER_NAME       VARCHAR2(256 BYTE),
  CAL_LAST_UPDATE_USER_NAME  VARCHAR2(256 BYTE),
  CAL_VERSION                INTEGER
)
TABLESPACE GISDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;