--
-- GIN_POLICY_INSURED_LIMITSBKP  (Table) 
--
CREATE TABLE TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP
(
  PIL_CODE                   NUMBER(22)         NOT NULL,
  PIL_IPU_CODE               NUMBER(22)         NOT NULL,
  PIL_SECT_CODE              NUMBER(22)         NOT NULL,
  PIL_SECT_SHT_DESC          VARCHAR2(15 BYTE)  NOT NULL,
  PIL_ROW_NUM                NUMBER(22)         NOT NULL,
  PIL_CALC_GROUP             NUMBER(22)         NOT NULL,
  PIL_LIMIT_AMT              NUMBER(25,5),
  PIL_PREM_RATE              NUMBER(30,10),
  PIL_PREM_AMT               NUMBER(25,5),
  PIL_RATE_TYPE              VARCHAR2(3 BYTE),
  PIL_RATE_DESC              VARCHAR2(20 BYTE),
  PIL_SECT_TYPE              VARCHAR2(2 BYTE),
  PIL_SECT_EXCESS_DETAIL     VARCHAR2(255 BYTE),
  PIL_ORIGINAL_PREM_RATE     NUMBER(22,5),
  PIL_RATE_CHANGE_REMARKS    VARCHAR2(50 BYTE),
  PIL_CHANGE_DONE_BY         VARCHAR2(20 BYTE),
  PIL_MIN_PREMIUM            NUMBER(23,5),
  PIL_COMMENT                VARCHAR2(2000 BYTE),
  PIL_MULTIPLIER_RATE        NUMBER(22,5),
  PIL_MULTIPLIER_DIV_FACTOR  NUMBER(22,5),
  PIL_ANNUAL_PREMIUM         NUMBER(25,5),
  PIL_RATE_DIV_FACT          NUMBER(22,5),
  PIL_DESC                   VARCHAR2(60 BYTE),
  PIL_USED_LIMIT             NUMBER(30,5),
  PIL_COMPUTE                VARCHAR2(1 BYTE)   DEFAULT 'Y',
  PIL_INDEM_PRD              NUMBER(22,5),
  PIL_PRD_TYPE               VARCHAR2(1 BYTE),
  PIL_INDEM_FSTPRD           NUMBER(22,5),
  PIL_INDEM_FSTPRD_PCT       NUMBER(22,5),
  PIL_INDEM_REMPRD_PCT       NUMBER(22,5),
  PIL_DUAL_BASIS             VARCHAR2(5 BYTE),
  PIL_PREM_ACCUMULATION      NUMBER(30,5),
  PIL_PREM_PRORATA           NUMBER(30,5),
  PIL_PREV_PREM              NUMBER(30,5),
  PIL_DECLARATION_SECTION    VARCHAR2(1 BYTE),
  PIL_PREV_LIMIT             NUMBER(25,5),
  PIL_ACTUAL_PREM            NUMBER(25,5),
  PIL_PREV_PREM_PRORATA      NUMBER(25,5),
  PIL_ANNUAL_ACTUAL_PREM     NUMBER(25,5)       DEFAULT 0,
  PIL_EML_PCT                NUMBER(22),
  PIL_TOP_LOC_RATE           NUMBER(22),
  PIL_TOP_LOC_DIV_FACT       NUMBER(22),
  PIL_FREE_LIMIT_AMT         NUMBER(22,5),
  PIL_LIMIT_PRD              NUMBER(22),
  PIL_ACTUAL_RATE_PREM       NUMBER(15,2),
  PIL_FREE_LIMIT             NUMBER(22,5),
  PIL_PRORATA_FULL           VARCHAR2(1 BYTE)   DEFAULT 'F'                   NOT NULL,
  PIL_EXPIRED                VARCHAR2(1 BYTE)   DEFAULT 'N',
  PIL_SI_LIMIT_TYPE          VARCHAR2(1 BYTE),
  PIL_SI_RATE                NUMBER(23,5),
  PIL_COVER_TYPE             VARCHAR2(1 BYTE),
  PIL_PRR_MAX_RATE           NUMBER(22,2),
  PIL_PRR_MIN_RATE           NUMBER(22,2)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    30
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          22M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_CODE IS 'table primary key';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_IPU_CODE IS 'Foreign Key reference to table GIN_INSURED_PROPERTY_UNDS';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_SECT_CODE IS 'Foreign Key Referencing table GIN_SECTIONS';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_SECT_SHT_DESC IS 'Section ID';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_ROW_NUM IS 'Row number used in ordering premium items during premium computation';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_CALC_GROUP IS 'Calculation grouping field used to facilitated premium computation espicial when applying discounts and loadings';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_LIMIT_AMT IS 'Premium item limit amount (SI)';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_PREM_RATE IS 'Premium rate';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_PREM_AMT IS 'Computed premium amount';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_RATE_TYPE IS 'Rate type applied';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_RATE_DESC IS 'Rate description';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_SECT_TYPE IS 'ES-extension si, EL-extension limit,SS - section si,SL Section limit,DS - discount, LO - Loading ,EC - escalation';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_SECT_EXCESS_DETAIL IS 'Section excess details';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_ORIGINAL_PREM_RATE IS 'Original premium rate from the setup, if the premium rate used in the computation was changed';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_RATE_CHANGE_REMARKS IS 'Reasons for changing premium rate at computation';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_CHANGE_DONE_BY IS 'audit trail of who changed the premium rate';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_MIN_PREMIUM IS 'Minimum premium amount for the premium item';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_COMMENT IS 'General comments for the premium item';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_MULTIPLIER_RATE IS 'Multiplier rate appied';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_MULTIPLIER_DIV_FACTOR IS 'Multiplier rate division factor applied';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_ANNUAL_PREMIUM IS 'Computed annual premium amount';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_RATE_DIV_FACT IS 'Rate division Factor';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_DESC IS 'Premium item description';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_USED_LIMIT IS 'Used limit';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_COMPUTE IS 'Indicated if the premium item will be used in the premium computation';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_INDEM_PRD IS 'Indeminty period';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_PRD_TYPE IS 'Indeminty period type';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_INDEM_FSTPRD IS 'Indeminty first period';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_INDEM_FSTPRD_PCT IS 'Indeminty first period percentage';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_INDEM_REMPRD_PCT IS 'Indeminty Remaining period percentage';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_DUAL_BASIS IS 'Apply dual basis or not';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_PREM_ACCUMULATION IS 'Premium accumulation used in reinsurance';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_PREM_PRORATA IS 'prorata premiun';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_PREV_PREM IS 'previous endorsement premium';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_DECLARATION_SECTION IS 'Indicates if its a declaration section';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_PREV_LIMIT IS 'Previous endorsement section limit';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_ACTUAL_PREM IS 'Actual premium';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_PREV_PREM_PRORATA IS 'Prev endorsment prorata premium';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_ANNUAL_ACTUAL_PREM IS 'Annual actual premium';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_EML_PCT IS 'EML percentage';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_TOP_LOC_RATE IS 'Top Location rate';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_TOP_LOC_DIV_FACT IS 'Top location Division factor';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_FREE_LIMIT_AMT IS 'Free limit premium amount';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_LIMIT_PRD IS 'Limit period';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_ACTUAL_RATE_PREM IS 'Actual premium rate';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_FREE_LIMIT IS 'Free limit SI limit';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_PRORATA_FULL IS 'Indicates if its On prorata basis or full basis';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_EXPIRED IS 'Indicate if the section has expired on the endorsement or not';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_SI_LIMIT_TYPE IS 'Used for loading and discount where a rate is applied on the SI to determine the discount or loading on the transction';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_SI_RATE IS 'Used for loading and discount where a rate is applied on the SI to determine the discount or loading on the transction - rate applied';

COMMENT ON COLUMN TQ_CRM.GIN_POLICY_INSURED_LIMITSBKP.PIL_COVER_TYPE IS 'Cover type field used for medical section';