--
-- GIN_CLAIM_REVISIONS27032014  (Table) 
--
CREATE TABLE TQ_CRM.GIN_CLAIM_REVISIONS27032014
(
  CLMREV_CODE                  NUMBER(22)       NOT NULL,
  CLMREV_DATE                  DATE             NOT NULL,
  CLMREV_GGT_TRANS_NO          NUMBER(22)       NOT NULL,
  CLMREV_CMB_CLAIM_NO          VARCHAR2(40 BYTE) NOT NULL,
  CLMREV_AMT                   NUMBER(23,5)     NOT NULL,
  CLMREV_POL_BATCH_NO          NUMBER(22)       NOT NULL,
  CLMREV_REMARKS               VARCHAR2(100 BYTE),
  CLMREV_GGT_TRAN_TYPE         VARCHAR2(4 BYTE) NOT NULL,
  CLMREV_ACPR_CODE             NUMBER(22),
  CLMREV_ACPR_SHT_DESC         VARCHAR2(20 BYTE),
  CLMREV_COMP_RETENTION        NUMBER(22,5),
  CLMREV_MAN_AMOUNT            NUMBER(22,5),
  CLMREV_QUOTA_AMOUNT          NUMBER(22,5),
  CLMREV_FSTSUP_AMOUNT         NUMBER(22,5),
  CLMREV_SECSUP_AMOUNT         NUMBER(22,5),
  CLMREV_FACRE_AMOUNT          NUMBER(22,5),
  CLMREV_COIN_AMT              NUMBER(30,5),
  CLMREV_AMT_BCUR              NUMBER(23,5),
  CLMREV_MAN_AMOUNT_BCUR       NUMBER(22,5),
  CLMREV_QUOTA_AMOUNT_BCUR     NUMBER(22,5),
  CLMREV_FSTSUP_AMOUNT_BCUR    NUMBER(22,5),
  CLMREV_SECSUP_AMOUNT_BCUR    NUMBER(22,5),
  CLMREV_FACRE_AMOUNT_BCUR     NUMBER(22,5),
  CLMREV_COIN_AMT_BCUR         NUMBER(30,5),
  CLMREV_RESERVE               NUMBER(20,5),
  CLMREV_RESERVE_BCUR          NUMBER(20,5),
  CLMREV_AUTHORISED            VARCHAR2(1 BYTE),
  CLMREV_DATE_AUTHORISED       DATE,
  CLMREV_AUTHORISED_BY         VARCHAR2(20 BYTE),
  CLMREV_CUR_CODE              NUMBER(15)       NOT NULL,
  CLMREV_CUR_SYMBOL            VARCHAR2(25 BYTE),
  CLMREV_CUR_RATE              NUMBER(15,5),
  HFMS_STATUS                  NUMBER(1),
  HFMS_UPD_DT                  DATE,
  HFMS_GAU_ID                  NUMBER,
  CLMREV_BOC_TRANS             VARCHAR2(1 BYTE) NOT NULL,
  CLMREV_GROSS_AMT             NUMBER(23,2),
  CLMREV_GROSS_COIN_AMT        NUMBER(23,2),
  CLMREV_CLM_REF_NO            VARCHAR2(30 BYTE),
  CLMREV_REIN_POOL_APPL        CHAR(1 BYTE),
  CLMREV_REIN_POOL_RATE        NUMBER(23,2),
  CLMREV_REIN_POOL_AMT         NUMBER(23,2),
  CLMREV_REIN_POOL_BAMT        NUMBER(23,2),
  CLMREV_RPOOL_COMP_RETEN      NUMBER(23,2),
  CLMREV_GGT_BTR_TRANS_CODE    VARCHAR2(20 BYTE),
  CLMREV_FACRE_OB_AMOUNT       NUMBER(23,5),
  CLMREV_FACRE_OB_AMOUNT_BCUR  NUMBER(23,5),
  CLMREV_COMP_RETENTION_RATE   NUMBER(23,5),
  CLMREV_XOL_AMOUNT            NUMBER(23,5),
  CLMREV_XOL_AMOUNT_BCUR       NUMBER(23,5)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;