--
-- GIN_PRINT_CERT_QUEUE_BAK  (Table) 
--
CREATE TABLE TQ_CRM.GIN_PRINT_CERT_QUEUE_BAK
(
  PCQ_POL_POLICY_NO     VARCHAR2(30 BYTE)       NOT NULL,
  PCQ_POL_REN_ENDOS_NO  VARCHAR2(30 BYTE)       NOT NULL,
  PCQ_POL_BATCH_NO      NUMBER(22),
  PCQ_IPU_CODE          NUMBER(22)              NOT NULL,
  PCQ_CT_CODE           NUMBER(22)              NOT NULL,
  PCQ_CT_SHT_DESC       VARCHAR2(8 BYTE),
  PCQ_IPU_PROPERTY_ID   VARCHAR2(60 BYTE),
  PCQ_DATE_TIME         DATE,
  PCQ_STATUS            VARCHAR2(15 BYTE),
  PCQ_CERT_NO           NUMBER(22),
  PCQ_GOOD_FOR_PRINT    VARCHAR2(1 BYTE),
  PCQ_CER_LOT_ID        VARCHAR2(20 BYTE),
  PCQ_AGNT_AGENT_CODE   NUMBER(22)              NOT NULL,
  PCQ_AGNT_SHT_DESC     VARCHAR2(15 BYTE)       NOT NULL,
  PCQ_PREFIX            VARCHAR2(15 BYTE),
  PCQ_POSTFIX           VARCHAR2(15 BYTE),
  PCQ_WET               DATE,
  PCQ_POLC_CODE         NUMBER(22)              NOT NULL,
  PCQ_CLIENT_POLICY_NO  VARCHAR2(30 BYTE)       NOT NULL,
  PCQ_CERT_YEAR         NUMBER(22),
  PCQ_CODE              NUMBER(22)              NOT NULL,
  PCQ_CERT_WEF_TIME     VARCHAR2(12 BYTE),
  PCQ_CLIENT_NAME       VARCHAR2(500 BYTE),
  PCQ_ISSUED_BY         VARCHAR2(100 BYTE),
  PCQ_COVT_SHT_DESC     VARCHAR2(15 BYTE),
  PCQ_SCL_CODE          NUMBER(22),
  PCQ_CAPACITY          NUMBER(22),
  PCQ_AGC_CODE          NUMBER(22),
  PCQ_BRN_CODE          NUMBER(22)              NOT NULL,
  PCQ_DONE_BY           VARCHAR2(22 BYTE),
  PCQ_TONNAGE           VARCHAR2(8 BYTE),
  PCQ_PASSENGER_NO      NUMBER(8),
  PCQ_PRINT_BY          VARCHAR2(30 BYTE),
  PCQ_ALLOC_BY          VARCHAR2(30 BYTE),
  PQC_BRN_CODE          NUMBER
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;