--
-- GIN_POLICY_RISK_R27032014  (Table) 
--
CREATE TABLE TQ_CRM.GIN_POLICY_RISK_R27032014
(
  PRRD_CODE                    NUMBER(22)       NOT NULL,
  PRRD_IPU_CODE                NUMBER(22)       NOT NULL,
  PRRD_IDX                     NUMBER(22)       NOT NULL,
  PRRD_TRAN_NO                 NUMBER(22)       NOT NULL,
  PRRD_WEF                     DATE,
  PRRD_WET                     DATE,
  PRRD_CURRENT                 VARCHAR2(1 BYTE),
  PRRD_COMP_RETENTION          NUMBER(35,5),
  PRRD_AVAIL_FULC_BAL          NUMBER(30,5),
  PRRD_GROSS_COMP_RETENTION    NUMBER(35,5),
  PRRD_FACRE_AMOUNT            NUMBER(30,5),
  PRRD_COM_RETENTION_RATE      NUMBER(35,5),
  PRRD_GRP_SI_RISK_PCT         NUMBER(35,5),
  PRRD_GRP_TOP_LOC             NUMBER(35,5),
  PRRD_GRP_COMP_GROSS_RET      NUMBER(30,5),
  PRRD_GRP_COMP_NET_RET        NUMBER(35,5),
  PRRD_RI_PREM                 NUMBER(35,5),
  PRRD_EXCESS_PCT              NUMBER(22,5),
  PRRD_COMP_NET_RATE           NUMBER(35,5),
  PRRD_PRORATA_DAYS            NUMBER(22),
  PRRD_PREV_FACRE_RATE         NUMBER(22,5),
  PRRD_REFUND_PREM             NUMBER(22,5),
  PRRD_PREV_RET_RATE           NUMBER(22,5),
  PRRD_PREV_NET_RATE           NUMBER(22,5),
  PRRD_AUTH_DT                 DATE,
  PRRD_FACRE_RATE              NUMBER(25,5),
  PRRD_ALLOWED_GRS_COMP_RET    NUMBER(35,5),
  PRRD_AS_UWYR                 NUMBER(5),
  PRRD_ANNUAL_PREM             NUMBER(22,5),
  PRRD_COVER_DAYS              NUMBER(5),
  PRRD_PRORATA_PREM            NUMBER(22,5),
  PRRD_PREV_NET_RETENTION      NUMBER(22,5),
  PRRD_REFUND_NET_PREM         NUMBER(22,5),
  PRRD_REFUND_FACRE_PREM       NUMBER(22,5),
  PRRD_NET_PREM                NUMBER(22,5),
  PRRD_PREV_PRRD_CODE          NUMBER(22),
  PRRD_AS_CODE                 NUMBER,
  PRRD_EARTHQUAKE_PREM         NUMBER(35,5),
  PRRD_RI_NET_LESS_EQ_PREM     NUMBER(35,5),
  PRRD_TA_CODE                 NUMBER(22),
  PRRD_NET_PREV_PREM           NUMBER(22,5),
  PRRD_RI_PREV_PREM            NUMBER(22,5),
  PRRD_RI_SI                   NUMBER(23,5),
  PRRD_PREV_RI_SI              NUMBER(23,5),
  PRRD_FACOBLIG_EXCESS         NUMBER(22,5),
  PRRD_FACOBLIG_LIMIT          NUMBER(22,5),
  PRRD_FACOBLIG_USER_EXCESS    NUMBER(23,5),
  PRRD_SPECIAL_COMP_RETENTION  NUMBER,
  PRRD_PREM_DIFF               NUMBER(23,2),
  PRRD_FACOBLIG_ALLOC_CHK      VARCHAR2(1 BYTE),
  PRRD_CEDE_POOL               VARCHAR2(1 BYTE),
  PRRD_EFFECTIVE_DATE          DATE,
  PRRD_GROSS_CMP_RET_TYPE      VARCHAR2(1 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;