--
-- JBPM4_HIST_TASK  (Table) 
--
CREATE TABLE TQ_CRM.JBPM4_HIST_TASK
(
  DBID_       NUMBER(19)                        NOT NULL,
  DBVERSION_  NUMBER(10)                        NOT NULL,
  EXECUTION_  VARCHAR2(255 BYTE),
  OUTCOME_    VARCHAR2(255 BYTE),
  ASSIGNEE_   VARCHAR2(255 BYTE),
  PRIORITY_   NUMBER(10),
  STATE_      VARCHAR2(255 BYTE),
  CREATE_     DATE,
  END_        DATE,
  DURATION_   NUMBER(19),
  NEXTIDX_    NUMBER(10),
  SUPERTASK_  NUMBER(19)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          2M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;