--
-- JBPM4_SYS_DEPLOYMENTS  (Table) 
--
CREATE TABLE TQ_CRM.JBPM4_SYS_DEPLOYMENTS
(
  JSD_SYS_CODE        NUMBER,
  JSD_JPDL_NAME       VARCHAR2(50 BYTE),
  JSD_JPDL_FILE_NAME  VARCHAR2(50 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;