--
-- LOAD_COUNTRIES2  (Table) 
--
CREATE TABLE TQ_CRM.LOAD_COUNTRIES2
(
  DESCRIPTION   VARCHAR2(20 BYTE),
  COUNTRYNAME   VARCHAR2(100 BYTE),
  NATIONALITY   VARCHAR2(100 BYTE),
  SCHEGEN       VARCHAR2(1 BYTE),
  BASECURRENCY  VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;