--
-- MICROSOFTDTPROPERTIES  (Table) 
--
CREATE TABLE TQ_CRM.MICROSOFTDTPROPERTIES
(
  ID        NUMBER CONSTRAINT MICROSOFT_NN_ID   NOT NULL,
  OBJECTID  NUMBER,
  PROPERTY  VARCHAR2(64 BYTE) CONSTRAINT MICROSOFT_NN_PROPERTY NOT NULL,
  VALUE     VARCHAR2(255 BYTE),
  LVALUE    LONG RAW,
  VERSION   NUMBER                              DEFAULT (0) CONSTRAINT MICROSOFT_NN_VERSION NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;