--
-- PRODUCT_INFORMATION  (Table) 
--
CREATE TABLE TQ_CRM.PRODUCT_INFORMATION
(
  PRODUCT_ID           NUMBER(6),
  PRODUCT_NAME         NVARCHAR2(100),
  PRODUCT_DESCRIPTION  VARCHAR2(1000 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;