--
-- QRTZ_TRIGGERS  (Table) 
--
CREATE TABLE TQ_CRM.QRTZ_TRIGGERS
(
  QT_JOB_NAME              VARCHAR2(80 BYTE)    NOT NULL,
  QT_DESCRIPTION           VARCHAR2(120 BYTE),
  QT_NEXT_FIRE_TIME        DATE,
  QT_PREV_FIRE_TIME        DATE,
  QT_START_TIME            DATE                 NOT NULL,
  QT_END_TIME              DATE,
  QT_CODE                  NUMBER               NOT NULL,
  QT_SYS_CODE              NUMBER,
  QT_RECURRENCE            VARCHAR2(1 BYTE)     DEFAULT 'Y',
  QT_RECURRENCE_TYPE       VARCHAR2(100 BYTE),
  QT_JOB_ASSIGNEE          NUMBER,
  QT_NOTIFIED_FAIL_USER    NUMBER,
  QT_NOTIFIED_SUCC_USER    NUMBER,
  QT_RECCURENCE_INTERVAL   VARCHAR2(50 BYTE),
  QT_JOB_TYPE              VARCHAR2(20 BYTE),
  QT_JOB_TEMPLATE          NUMBER,
  QT_FAIL_NOTIFY_TEMPLATE  NUMBER,
  QT_SUCC_NOTIFY_TEMPLATE  NUMBER,
  QT_CRON_EXPRESSION       VARCHAR2(100 BYTE),
  QT_STATUS                VARCHAR2(1 BYTE),
  QT_THRESHOLD_VALUE       NUMBER(22),
  QT_THRESHOLD_TYPE        VARCHAR2(20 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;