--
-- TQC_DOCUMENT_INBOX  (Table) 
--
CREATE TABLE TQ_CRM.TQC_DOCUMENT_INBOX
(
  DBOX_ID          INTEGER,
  DBOX_DOC_NAME    VARCHAR2(50 BYTE),
  DBOX_DOC_URL     VARCHAR2(300 BYTE),
  DBOX_DOC_AUTHOR  VARCHAR2(50 BYTE),
  DBOX_DOC_DESC    VARCHAR2(50 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;