--
-- TQC_MEMO_HEADER_DTLS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_MEMO_HEADER_DTLS
(
  MEMDTLS_MEMH_CODE    NUMBER(22)               NOT NULL,
  MEMDTLS_MEMDET_CODE  NUMBER(22),
  MEMDTLS_DETAIL       VARCHAR2(4000 BYTE),
  MEMDTLS_CODE         NUMBER(15),
  MEMDTLS_FOOTER       VARCHAR2(1000 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;