--
-- TQC_REQUIRED_DOCS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_REQUIRED_DOCS
(
  RQD_CODE       NUMBER,
  RQD_SPT_CODE   NUMBER,
  RQD_SPTA_CODE  NUMBER,
  RQD_SYS_CODE   NUMBER,
  RQC_RDOC_ID    NUMBER
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;