--
-- TQC_SYS_RPT_TEMPLATES  (Table) 
--
CREATE TABLE TQ_CRM.TQC_SYS_RPT_TEMPLATES
(
  RPT_TMPL_CODE         NUMBER                  NOT NULL,
  RPT_TMPL_RPT_CODE     NUMBER                  NOT NULL,
  RPT_TMPL_FILE         VARCHAR2(50 BYTE)       NOT NULL,
  RPT_TMPL_NAME         VARCHAR2(50 BYTE)       NOT NULL,
  RPT_TMPL_DESCRIPTION  VARCHAR2(250 BYTE),
  RPT_TMPL_STYLE_FILE   VARCHAR2(50 BYTE)       NOT NULL,
  RPT_TMPL_ORG_CODE     NUMBER,
  RPT_TMPL_ACTIVE       VARCHAR2(1 BYTE)        DEFAULT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;