--
-- TQC_INS_NO_FORMATS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_INS_NO_FORMATS
(
  INF_AGN_CODE                NUMBER(12)        NOT NULL,
  INF_AGN_POLNOFORMAT         VARCHAR2(200 BYTE),
  INF_AGN_POLNOSERIAL         VARCHAR2(200 BYTE),
  INF_AGN_POLNOSRLENGTH       VARCHAR2(200 BYTE),
  INF_AGN_POLFACRENOFORMAT    VARCHAR2(200 BYTE),
  INF_AGN_POLFACRENOSERIAL    VARCHAR2(200 BYTE),
  INF_AGN_POLFACRESRLENGTH    VARCHAR2(200 BYTE),
  INF_AGN_ENDOSNOFORMAT       VARCHAR2(200 BYTE),
  INF_AGN_ENDOSSERIAL         VARCHAR2(200 BYTE),
  INF_AGN_ENDOSSRLENGTH       VARCHAR2(200 BYTE),
  INF_AGN_ENDOSFACREFORMAT    VARCHAR2(200 BYTE),
  INF_AGN_ENDOSFACRESERIAL    VARCHAR2(200 BYTE),
  INF_AGN_ENDOSFACRESRLENGTH  VARCHAR2(200 BYTE),
  INF_AGN_MARINENOFORMAT      VARCHAR2(200 BYTE),
  INF_AGN_MARINESERIAL        VARCHAR2(200 BYTE),
  INF_AGN_MARINESRLENGTH      VARCHAR2(200 BYTE),
  INF_AGN_CLAIMNOFORMAT       VARCHAR2(200 BYTE),
  INF_AGN_CLAIMSERIAL         VARCHAR2(200 BYTE),
  INF_AGN_CLAIMSRLENGTH       VARCHAR2(200 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

COMMENT ON COLUMN TQ_CRM.TQC_INS_NO_FORMATS.INF_AGN_CLAIMNOFORMAT IS 'CLAIM NO FORMAT';

COMMENT ON COLUMN TQ_CRM.TQC_INS_NO_FORMATS.INF_AGN_CLAIMSERIAL IS 'CLAIM SERIAL NO FORMAT';

COMMENT ON COLUMN TQ_CRM.TQC_INS_NO_FORMATS.INF_AGN_CLAIMSRLENGTH IS 'CLAIM SERIAL LENGTH';