--
-- TQC_DIRECT_DEBIT_HEADER  (Table) 
--
CREATE TABLE TQ_CRM.TQC_DIRECT_DEBIT_HEADER
(
  DDH_CODE                NUMBER(8)             NOT NULL,
  DDH_DD_CODE             NUMBER(8)             NOT NULL,
  DDH_CLNT_CODE           NUMBER(8)             NOT NULL,
  DDH_CLNT_BBR_CODE       NUMBER(8)             NOT NULL,
  DDH_BBR_BNK_CODE        NUMBER(8)             NOT NULL,
  DDH_CLNT_SHT_DESC       VARCHAR2(25 BYTE)     NOT NULL,
  DDH_CLNT_NAME           VARCHAR2(300 BYTE),
  DDH_CLNT_BANK_ACC_NO    NUMBER(20)            NOT NULL,
  DDH_BBR_BRANCH_NAME     VARCHAR2(100 BYTE),
  DDH_BBR_SHT_DESC        VARCHAR2(15 BYTE),
  DDH_BBR_REF_CODE        VARCHAR2(20 BYTE),
  DDH_TOT_AMT             NUMBER(22,5),
  DDH_STATUS              VARCHAR2(5 BYTE),
  DDH_RECEIPTED           VARCHAR2(3 BYTE),
  DDH_FAIL_DATE           DATE,
  DDH_FAIL_UPDATED_BY     VARCHAR2(30 BYTE),
  DDH_FAIL_UPDATE_DATE    DATE,
  DDH_FAIL_REMARKS        VARCHAR2(200 BYTE),
  DDH_RELAUNCH_DATE       DATE,
  DDH_RELAUNCH_STOP_DATE  DATE,
  DDH_RELAUNCHED_BY       VARCHAR2(30 BYTE),
  DDH_RELAUNCH_STOPED_BY  VARCHAR2(30 BYTE),
  DDH_INITIAL_BOOK_DATE   DATE,
  DDH_PREV_DDH_CODE       NUMBER(8),
  DDH_ACC_HOLDER          VARCHAR2(50 BYTE),
  DDH_AMOUNT              NUMBER
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;