--
-- TQC_PROSPECTS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_PROSPECTS
(
  PRS_CODE            NUMBER(22)                NOT NULL,
  PRS_SURNAME         VARCHAR2(100 BYTE)        NOT NULL,
  PRS_PHYSICAL_ADDRS  VARCHAR2(100 BYTE),
  PRS_POSTAL_ADDRS    VARCHAR2(100 BYTE),
  PRS_OTHER_NAMES     VARCHAR2(100 BYTE),
  PRS_TEL_NO          VARCHAR2(50 BYTE),
  PRS_MOBILE_NO       VARCHAR2(50 BYTE),
  PRS_EMAIL_ADDRS     VARCHAR2(75 BYTE),
  PRS_ID_REG_NO       VARCHAR2(15 BYTE),
  PRS_DOB             DATE,
  PRS_PIN             VARCHAR2(25 BYTE),
  PRS_TWN_CODE        NUMBER(8),
  PRS_COU_CODE        NUMBER(8),
  PRS_POSTAL_CODE     NUMBER(8),
  PRS_CLNT_TYPE       VARCHAR2(100 BYTE),
  PRS_TYPE            VARCHAR2(15 BYTE)         DEFAULT 'I',
  PRS_CONTACT         VARCHAR2(250 BYTE),
  PRS_CONTACT_TEL     VARCHAR2(250 BYTE),
  PRS_LDS_CODE        NUMBER(23,5)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;