--
-- TQC_CLIENT_COMPLAINTS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_CLIENT_COMPLAINTS
(
  COMP_CODE       NUMBER                        NOT NULL,
  COMP_CLNT_CODE  NUMBER,
  COMP_SUBJECT    VARCHAR2(300 BYTE),
  COMP_MESSAGE    VARCHAR2(1000 BYTE), 
  CONSTRAINT TQC_CLIENT_COMPLAINTS_PK
  PRIMARY KEY
  (COMP_CODE)
  ENABLE VALIDATE
)
ORGANIZATION INDEX
PCTTHRESHOLD 50
TABLESPACE CRMDATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );