--
-- TQC_BANCASSURANCE_BRANCHES  (Table) 
--
CREATE TABLE TQ_CRM.TQC_BANCASSURANCE_BRANCHES
(
  BBB_CODE             NUMBER(8)                NOT NULL,
  BBB_BBR_CODE         NUMBER(8)                NOT NULL,
  BBB_BRANCH_NAME      VARCHAR2(100 BYTE),
  BBB_REMARKS          VARCHAR2(250 BYTE),
  BBB_SHT_DESC         VARCHAR2(15 BYTE)        NOT NULL,
  BBB_DATE_CREATED     DATE,
  BBB_CREATED_BY       VARCHAR2(15 BYTE)        NOT NULL,
  BBB_PHYSICAL_ADDRS   VARCHAR2(200 BYTE),
  BBB_POSTAL_ADDRS     VARCHAR2(100 BYTE),
  BBB_KBA_CODE         NUMBER(3),
  BBB_BNKT_CODE        NUMBER(20),
  BBB_BNKT_SHT_DESC    VARCHAR2(100 BYTE),
  BBB_EMAIL            VARCHAR2(100 BYTE),
  BBB_PERSON_NAME      VARCHAR2(100 BYTE),
  BBB_PERSON_EMAIL     VARCHAR2(100 BYTE),
  BBB_PERSON_COU_CODE  VARCHAR2(100 BYTE),
  BBB_PERSON_PHONE     VARCHAR2(100 BYTE),
  BBB_TER_CODE         NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;