--
-- TQC_BANK_BRANCHES_BRANCHES  (Table) 
--
CREATE TABLE TQ_CRM.TQC_BANK_BRANCHES_BRANCHES
(
  BBB_CODE                NUMBER(38,30)         NOT NULL,
  BBB_BRN_CODE            NUMBER(38,30)         NOT NULL,
  BBB_BRN_SHT_DESC        VARCHAR2(300 CHAR),
  BBB_BRN_REG_CODE        VARCHAR2(200 CHAR),
  BBB_BRN_NAME            VARCHAR2(300 CHAR),
  BBB_BRN_PHY_ADDRS       VARCHAR2(300 CHAR),
  BBB_BBR_CODE            NUMBER(38,30),
  BBB_BBR_BNK_CODE        NUMBER(38,30)         NOT NULL,
  BBB_BBR_BRANCH_NAME     VARCHAR2(300 CHAR),
  BBB_BBR_SHT_DESC        VARCHAR2(300 CHAR),
  BBB_BBR_PHYSICAL_ADDRS  VARCHAR2(300 CHAR)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;