--
-- TQC_CLIENTS_LOADING  (Table) 
--
CREATE TABLE TQ_CRM.TQC_CLIENTS_LOADING
(
  CLNT_CODE           VARCHAR2(200 BYTE),
  CLNT_INSURED        VARCHAR2(200 BYTE),
  CLNT_ADDRESS1       VARCHAR2(200 BYTE),
  CLNT_ADDRESS2       VARCHAR2(200 BYTE),
  CLNT_TOWN           VARCHAR2(200 BYTE),
  CLNT_PHONE1         VARCHAR2(200 BYTE),
  CLNT_PHONE2         VARCHAR2(200 BYTE),
  CLNT_FAX            VARCHAR2(200 BYTE),
  CLNT_EMAIL          VARCHAR2(200 BYTE),
  CLNT_GENDER         VARCHAR2(200 BYTE),
  CLNT_TITLE          VARCHAR2(200 BYTE),
  CLNT_POLICY_NUMBER  VARCHAR2(200 BYTE),
  CLNT_AGN_CODE       VARCHAR2(200 BYTE),
  CLNT_POSTED_BY      VARCHAR2(200 BYTE),
  CLNT_POSTED_ON      VARCHAR2(200 BYTE),
  CLNT_BRANCH         VARCHAR2(200 BYTE),
  CLNT_ID             NUMBER
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;