--
-- TQC_ALERTS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_ALERTS
(
  ALRTS_CODE           NUMBER(15)               NOT NULL,
  ALRTS_ALRT_CODE      NUMBER(15)               NOT NULL,
  ALRTS_SYS_CODE       NUMBER(15)               NOT NULL,
  ALRTS_AGN_CODE       NUMBER(15),
  ALRTS_CLNT_CODE      NUMBER(15),
  ALRTS_DESCRIPTION    VARCHAR2(500 BYTE),
  ALRTS_DATE           DATE,
  ALRTS_PERIOD         NUMBER,
  ALRTS_USER_CODE      NUMBER,
  ALRTS_DEST_CODE      NUMBER,
  ALRTS_DEST_TYPE      VARCHAR2(10 BYTE),
  ALRTS_SHT_DESC       VARCHAR2(100 BYTE),
  ALRTS_STATUS         VARCHAR2(2 BYTE),
  ALRTS_MSGT_CODE      NUMBER,
  ALRTS_SCREEN         VARCHAR2(1 BYTE)         DEFAULT 'Y',
  ALRTS_PREPARED_BY    VARCHAR2(35 BYTE),
  ALRTS_PREPARE_DATE   DATE,
  ALRTS_QUOT_CODE      NUMBER(22),
  ALRTS_QUOT_NO        VARCHAR2(30 BYTE),
  ALRTS_POL_BATCH_NO   NUMBER(22),
  ALRTS_POL_POLICY_NO  VARCHAR2(35 BYTE),
  ALRTS_CLAIM_NO       VARCHAR2(30 BYTE),
  ALRTS_TO_SEND_DATE   DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

COMMENT ON TABLE TQ_CRM.TQC_ALERTS IS 'Meant to store all the alerts to clients and agents to be displayed on the clients portal and the agents portals respectively. If the Alert Type defined in [TQC_ALERT_TYPES]';

COMMENT ON COLUMN TQ_CRM.TQC_ALERTS.ALRTS_CODE IS 'Primary key';

COMMENT ON COLUMN TQ_CRM.TQC_ALERTS.ALRTS_ALRT_CODE IS 'Foreign key from TQC_ALERT_TYPES';

COMMENT ON COLUMN TQ_CRM.TQC_ALERTS.ALRTS_AGN_CODE IS 'Foreign key from  TQC_AGENCIES';

COMMENT ON COLUMN TQ_CRM.TQC_ALERTS.ALRTS_CLNT_CODE IS 'Foreign key from TQC_CLIENTS';

COMMENT ON COLUMN TQ_CRM.TQC_ALERTS.ALRTS_DESCRIPTION IS 'Description to be displayed to the Agent/Client';

COMMENT ON COLUMN TQ_CRM.TQC_ALERTS.ALRTS_DATE IS 'Date of Alert';