--
-- TQC_SERV_REQ_IND_DTLS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_SERV_REQ_IND_DTLS
(
  SRID_CODE              NUMBER                 NOT NULL,
  SRID_NAME              VARCHAR2(200 BYTE),
  SRID_TELEPHONE         VARCHAR2(200 BYTE),
  SRID_EMAIL_ADDRESS     VARCHAR2(200 BYTE),
  SRID_PHYSICAL_ADDRESS  VARCHAR2(200 BYTE),
  SRID_ID_NUMBER         VARCHAR2(200 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;