--
-- TQC_BUSINESS_PERSONS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_BUSINESS_PERSONS
(
  BPN_CODE            NUMBER(8)                 NOT NULL,
  BPN_ID_NO           VARCHAR2(15 BYTE),
  BPN_ADDRESS         VARCHAR2(30 BYTE)         NOT NULL,
  BPN_TEL             NUMBER(10),
  BPN_MOBILE_NO       VARCHAR2(15 BYTE)         NOT NULL,
  BPN_EMAIL           VARCHAR2(30 BYTE),
  BPN_TYPE            VARCHAR2(3 BYTE)          NOT NULL,
  BPN_ZIP             VARCHAR2(10 BYTE),
  BPN_TOWN            VARCHAR2(15 BYTE),
  BPN_COU_CODE        NUMBER(8),
  BPN_NAME            VARCHAR2(70 BYTE)         NOT NULL,
  BPN_PIN             VARCHAR2(30 BYTE),
  BPN_BBR_CODE        NUMBER(22),
  BPN_BANK_ACC_NO     VARCHAR2(30 BYTE),
  BPN_BBR_SWIFT_CODE  NUMBER(22),
  BPN_CLD_CODE        NUMBER,
  BPN_REG_CLMT_CODE   NUMBER,
  BPN_CLNT_CODE       NUMBER,
  BPN_PAYEE_TYPE      VARCHAR2(1 BYTE)
)
TABLESPACE GISDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          512K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

COMMENT ON COLUMN TQ_CRM.TQC_BUSINESS_PERSONS.BPN_CODE IS 'PRIMARY KEY';

COMMENT ON COLUMN TQ_CRM.TQC_BUSINESS_PERSONS.BPN_ID_NO IS 'BUYER/PAYEE ID';

COMMENT ON COLUMN TQ_CRM.TQC_BUSINESS_PERSONS.BPN_ADDRESS IS 'BUYER/PAYEE ADDRESS';

COMMENT ON COLUMN TQ_CRM.TQC_BUSINESS_PERSONS.BPN_MOBILE_NO IS 'BUYER/PAYEE MOBILE PHONE NO.';

COMMENT ON COLUMN TQ_CRM.TQC_BUSINESS_PERSONS.BPN_EMAIL IS 'BUYER/PAYEE EMAIL ADDRESS';

COMMENT ON COLUMN TQ_CRM.TQC_BUSINESS_PERSONS.BPN_TYPE IS 'BUYER/PAYEE TYPE I.E IF BUYER OR PAYEE';

COMMENT ON COLUMN TQ_CRM.TQC_BUSINESS_PERSONS.BPN_ZIP IS 'BUYER/PAYEE ZIP';

COMMENT ON COLUMN TQ_CRM.TQC_BUSINESS_PERSONS.BPN_TOWN IS 'BUYER/PAYEE TOWN';

COMMENT ON COLUMN TQ_CRM.TQC_BUSINESS_PERSONS.BPN_COU_CODE IS 'BUYER/PAYEE COUNTRY';

COMMENT ON COLUMN TQ_CRM.TQC_BUSINESS_PERSONS.BPN_NAME IS 'BUYER/PAYEE NAME';