--
-- TQC_AGENCIES  (Table) 
--
CREATE TABLE TQ_CRM.TQC_AGENCIES
(
  AGN_CODE                 NUMBER(15)           NOT NULL,
  AGN_ACT_CODE             NUMBER(8),
  AGN_SHT_DESC             VARCHAR2(40 BYTE)    NOT NULL,
  AGN_NAME                 VARCHAR2(100 BYTE)   NOT NULL,
  AGN_PHYSICAL_ADDRESS     VARCHAR2(250 BYTE),
  AGN_POSTAL_ADDRESS       VARCHAR2(50 BYTE),
  AGN_TWN_CODE             NUMBER(8),
  AGN_COU_CODE             NUMBER(8),
  AGN_EMAIL_ADDRESS        VARCHAR2(250 BYTE),
  AGN_WEB_ADDRESS          VARCHAR2(50 BYTE),
  AGN_ZIP                  VARCHAR2(15 BYTE),
  AGN_CONTACT_PERSON       VARCHAR2(60 BYTE),
  AGN_CONTACT_TITLE        VARCHAR2(60 BYTE),
  AGN_TEL1                 VARCHAR2(100 BYTE),
  AGN_TEL2                 VARCHAR2(100 BYTE),
  AGN_FAX                  VARCHAR2(100 BYTE),
  AGN_ACC_NO               VARCHAR2(20 BYTE),
  AGN_PIN                  VARCHAR2(25 BYTE),
  AGN_AGENT_COMMISSION     NUMBER(22,5)         DEFAULT NULL,
  AGN_CREDIT_ALLOWED       CHAR(1 BYTE),
  AGN_AGENT_WHT_TAX        NUMBER(22,5),
  AGN_PRINT_DBNOTE         CHAR(1 BYTE)         DEFAULT 'Y',
  AGN_STATUS               VARCHAR2(10 BYTE),
  AGN_DATE_CREATED         DATE                 NOT NULL,
  AGN_CREATED_BY           VARCHAR2(40 BYTE),
  AGN_REG_CODE             VARCHAR2(100 BYTE),
  AGN_COMM_RESERVE_RATE    NUMBER(6),
  AGN_ANNUAL_BUDGET        NUMBER(15),
  AGN_STATUS_EFF_DATE      DATE                 NOT NULL,
  AGN_CREDIT_PERIOD        NUMBER(10),
  AGN_COMM_STAT_EFF_DT     DATE,
  AGN_COMM_STATUS_DT       DATE,
  AGN_COMM_ALLOWED         VARCHAR2(1 BYTE),
  AGN_CHECKED              VARCHAR2(1 BYTE),
  AGN_CHECKED_BY           VARCHAR2(30 BYTE),
  AGN_CHECK_DATE           DATE,
  AGN_COMP_COMM_ARREARS    VARCHAR2(1 BYTE),
  AGN_REINSURER            VARCHAR2(1 BYTE),
  AGN_BRN_CODE             NUMBER(8)            NOT NULL,
  AGN_TOWN                 VARCHAR2(50 BYTE),
  AGN_COUNTRY              VARCHAR2(30 BYTE),
  AGN_STATUS_DESC          VARCHAR2(50 BYTE),
  AGN_ID_NO                VARCHAR2(20 BYTE),
  AGN_CON_CODE             VARCHAR2(10 BYTE),
  AGN_SMS_TEL              VARCHAR2(35 BYTE),
  AGN_AHC_CODE             NUMBER(15),
  AGN_SEC_CODE             NUMBER(8),
  AGN_AGNC_CLASS_CODE      VARCHAR2(25 BYTE),
  AGN_EXPIRY_DATE          DATE,
  AGN_LICENSE_NO           VARCHAR2(25 BYTE),
  AGN_RUNOFF               CHAR(1 BYTE)         DEFAULT 'N'                   NOT NULL,
  AGN_LICENSED             VARCHAR2(1 BYTE)     DEFAULT 'Y',
  AGN_LICENSE_GRACE_PR     NUMBER(10),
  AGN_OLD_ACC_NO           VARCHAR2(20 BYTE),
  AGN_STATUS_REMARKS       VARCHAR2(20 BYTE),
  AGN_OSD_CODE             VARCHAR2(10 BYTE),
  AGN_BANK_ACC_NO          VARCHAR2(30 BYTE),
  AGN_UNIQUE_PREFIX        VARCHAR2(30 BYTE),
  AGN_BBR_CODE             NUMBER(22),
  AGN_INIQUE_PREFIX        VARCHAR2(30 BYTE),
  AGN_STATE_CODE           NUMBER(8),
  AGN_BBR_ACC_CODE         NUMBER,
  AGN_CRDT_RTING           VARCHAR2(10 BYTE),
  AGN_SUBAGENT             VARCHAR2(200 BYTE),
  AGN_MAIN_AGN_CODE        NUMBER,
  AGN_AGN_CODE             VARCHAR2(200 BYTE),
  AGN_CLNT_CODE            NUMBER(30),
  AGN_PAYEE                VARCHAR2(200 BYTE),
  AGN_ACCOUNT_MANAGER      NUMBER,
  AGN_ENABLE_WEB_EDIT      CHAR(1 BYTE)         DEFAULT 'N'                   NOT NULL,
  AGN_BIRTH_DATE           DATE,
  AGN_CREDIT_LIMIT         NUMBER,
  AGN_BRU_CODE             NUMBER(15),
  AGN_LOCAL_INTERNATIONAL  VARCHAR2(1 BYTE),
  AGN_REGULATOR_NUMBER     VARCHAR2(200 BYTE),
  AGN_AUTHORISED           VARCHAR2(1 BYTE)     DEFAULT 'N',
  AGN_AUTHORISED_BY        VARCHAR2(200 BYTE),
  AGN_AUTHORISED_DATE      DATE,
  AGN_ORS_CODE             NUMBER,
  AGN_RORG_CODE            NUMBER,
  AGN_ALLOCATE_CERT        VARCHAR2(1 BYTE),
  AGN_BOUNCED_CHQ          VARCHAR2(1 BYTE)     DEFAULT 'N',
  AGN_AGENT_TYPE           VARCHAR2(200 BYTE),
  AGN_BPN_CODE             NUMBER,
  AGN_GROUP                VARCHAR2(20 BYTE),
  AGN_FORGN                VARCHAR2(1 BYTE)     DEFAULT 'N'                   NOT NULL,
  AGN_WHTAX_APPLICABLE     VARCHAR2(50 BYTE),
  AGN_VAT_APPLICABLE       VARCHAR2(50 BYTE),
  AGN_DEFAULT_COMM_MODE    VARCHAR2(60 BYTE),
  AGN_TEL_PAY              VARCHAR2(35 BYTE),
  AGN_PAYMENT_FREQ         VARCHAR2(1 BYTE),
  AGN_DEFAULT_CPM_MODE     VARCHAR2(30 BYTE),
  AGN_GL_RCVBL_ACC_NO      VARCHAR2(30 BYTE),
  AGN_PAYDETAIL_VALIDATED  CHAR(1 BYTE),
  AGN_INST_COMM_ALLWD      VARCHAR2(2 BYTE)     DEFAULT 'N',
  AGN_AUTH_NAME            VARCHAR2(100 BYTE),
  AGN_BRR_NAME             VARCHAR2(100 BYTE),
  AGN_BRR_CODE             NUMBER(22),
  AGN_COMM_LEVY_RATE       NUMBER,
  AGN_COMM_LEVY_APP        VARCHAR2(1 BYTE),
  AGN_SBU_CODE             NUMBER,
  AGN_PYMT_VALIDATED       VARCHAR2(1 BYTE)     DEFAULT 'N',
  AGN_QUALIFICATION        VARCHAR2(100 BYTE),
  AGN_MARITAL_STATUS       VARCHAR2(5 BYTE),
  AGN_BENEFIT_START_DATE   DATE,
  AGN_ID_NO_DOC_USED       VARCHAR2(20 BYTE),
  AGN_AGNTY_CODE           NUMBER,
  AGN_ENT_CODE             NUMBER(22),
  AGN_IRA_REGNO            VARCHAR2(40 BYTE),
  AGN_IPRS_VALIDATED       VARCHAR2(1 BYTE),
  AGN_UPDATED_ON           DATE,
  AGN_UPDATED_BY           VARCHAR2(100 BYTE),
  AGN_PASSPORT_NO          VARCHAR2(80 BYTE),
  AGN_VALIDATION_SOURCE    VARCHAR2(80 BYTE),
  AGN_GENDER               VARCHAR2(6 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          3M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_CODE IS 'PRIMARY KEY';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_ACT_CODE IS 'ACCOUNT TYPE UNIQUE KEY';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_SHT_DESC IS 'ACCOUNT UNIQUE ID';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_NAME IS 'ACCOUNT NAME';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_PHYSICAL_ADDRESS IS 'PHYSICAL ADDRESS';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_POSTAL_ADDRESS IS 'POSTAL ADDRESS';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_TWN_CODE IS 'TOWN UNIQUE KEY';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_COU_CODE IS 'COUNTRY UNIQUE KEY';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_EMAIL_ADDRESS IS 'ACCOUNT EMAIL ADDRESS';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_ZIP IS 'ZIP CODE';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_CONTACT_PERSON IS 'ACCOUNT CONTACT PERSON';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_CONTACT_TITLE IS 'CONTACT PERSON TITLE';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_TEL1 IS 'ACCOUNT TELEPHONE NUMBER ONE';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_TEL2 IS 'ACCOUNT TELEPHONE NUMBER TWO';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_FAX IS 'ACCOUNT FAX NUMBER';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_ACC_NO IS 'GL ACCOUNT NUMBER';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_PIN IS 'PIN NUMBER';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_STATUS IS 'ACCOUNT STATUS(ACTIVE OR INACTIVE)';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_DATE_CREATED IS 'DATE ACCOUNT CREATED IN THE SYSTEM';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_CREATED_BY IS 'WHO CREATED THE ACCOUNT IN THE SYSTEM';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_REG_CODE IS 'REGION UNIQUE KEY';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_BRN_CODE IS 'BRANCH UNIQUE KEY';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_TOWN IS 'TOWN';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_COUNTRY IS 'COUNTRY';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_ID_NO IS 'REGISTRATION NUMBER';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_SMS_TEL IS 'MOBILE NUMBER';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_AHC_CODE IS 'CODE FOR THE HOLDING COMPANY';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_SEC_CODE IS 'SECTOR REFERENCE NUMBER';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_STATUS_REMARKS IS 'ACCOUNT STATUS(ACTIVE OR INACTIVE) REMARKS';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_BANK_ACC_NO IS 'BANK ACCOUNT NUMBER';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_BBR_CODE IS 'BANK ACCOUNT REFERENCE NUMBER';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCIES.AGN_INST_COMM_ALLWD IS 'AGENT TO FLAG IF COMMISSION PAYABLE VIA INSTANT COMMISSION FUNCIONALITY';