--
-- TQC_CLIENT_WEB_ACCOUNTS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_CLIENT_WEB_ACCOUNTS
(
  ACWA_CODE             NUMBER(15),
  ACWA_USERNAME         VARCHAR2(50 BYTE),
  ACWA_PWD              VARCHAR2(50 BYTE),
  ACWA_LOGIN_ALLOWED    VARCHAR2(1 BYTE)        DEFAULT 'N',
  ACWA_PWD_CHANGED      DATE,
  ACWA_PWD_RESET        VARCHAR2(2 BYTE),
  ACWA_LOGIN_ATTEMPTS   NUMBER(8),
  ACWA_PERSONEL_RANK    VARCHAR2(50 BYTE),
  ACWA_DT_CREATED       DATE,
  ACWA_STATUS           VARCHAR2(2 BYTE),
  ACWA_LAST_LOGIN_DATE  DATE,
  ACWA_CLNT_CODE        NUMBER(15),
  ACWA_CREATED_BY       VARCHAR2(50 BYTE),
  ACWA_NAME             VARCHAR2(100 BYTE),
  ACWA_EMAIL_ADDRS      VARCHAR2(50 BYTE),
  ACWA_RESET_CODE       VARCHAR2(100 BYTE),
  ACWA_TYPE             VARCHAR2(1 BYTE)        DEFAULT 'I',
  ACWA_COUNTRY          VARCHAR2(34 BYTE),
  ACWA_ID_REG_NO        VARCHAR2(23 BYTE),
  V_SMS_TOKEN           VARCHAR2(45 BYTE),
  ACWA_SMS_CODE         VARCHAR2(45 BYTE),
  ACWA_MOBILE_NUMBER    VARCHAR2(900 BYTE),
  ACWA_ANSWER2          VARCHAR2(30 BYTE),
  ACWA_ANSWER1          VARCHAR2(30 BYTE),
  ACWA_SECQ_SHT_DESC_2  VARCHAR2(30 BYTE),
  ACWA_SECQ_SHT_DESC_1  VARCHAR2(30 BYTE),
  ACWA_PASSPORT_NO      VARCHAR2(20 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;