--
-- TQC_USER_RIGHTS_LOG  (Table) 
--
CREATE TABLE TQ_CRM.TQC_USER_RIGHTS_LOG
(
  URL_CODE            NUMBER,
  URL_USR_CODE        NUMBER,
  URL_USR_USERNAME    VARCHAR2(30 BYTE),
  URL_SPRC_PROCESS    VARCHAR2(100 BYTE),
  URL_SPRCA_SHT_DESC  VARCHAR2(50 BYTE),
  URL_SPRSA_SUB_AREA  VARCHAR2(100 BYTE),
  URL_PRCS_AREA       VARCHAR2(100 BYTE),
  URL_PRSC_SUB_AREA   VARCHAR2(100 BYTE),
  URL_SYS_CODE        VARCHAR2(5 BYTE),
  URL_SRLS_CODE       VARCHAR2(10 BYTE),
  URL_AMOUNT          NUMBER,
  URL_DR_CR           VARCHAR2(10 BYTE),
  URL_USR_NAME        VARCHAR2(100 BYTE),
  URL_LOG_DATE        DATE                      DEFAULT SYSDATE               NOT NULL
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;