--
-- TQC_AGNT_CREATED_CLNTS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_AGNT_CREATED_CLNTS
(
  AGNTCC_PRP_CODE  NUMBER,
  AGNTCC_AGN_CODE  NUMBER
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;