--
-- TQC_CLIENT_EMPLOYERS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_CLIENT_EMPLOYERS
(
  CODE             NUMBER                       NOT NULL,
  CLNT_CODE        NUMBER,
  COU_CODE         NUMBER,
  TOWN_CODE        NUMBER,
  PST_ZIP_CODE     NUMBER,
  SECTOR_CODE      NUMBER,
  EMPLOYER_TYPE    VARCHAR2(50 BYTE),
  EMPLOYER_NAME    VARCHAR2(50 BYTE)            NOT NULL,
  PAYROLL_NO       VARCHAR2(50 BYTE),
  MIN_SALARY       NUMBER,
  MAX_SALARY       NUMBER,
  MONTHLY_INCOME   NUMBER,
  EMPLOYMENT_DATE  DATE,
  EMPLOYER_NOS     VARCHAR2(200 BYTE),
  EMPLOYER_CELLS   VARCHAR2(200 BYTE),
  EMPLOYER_FAX     VARCHAR2(50 BYTE),
  STATE_CODE       NUMBER
)
TABLESPACE CRMDATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;