--
-- TQC_REQUIRED_DOCUMENTS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_REQUIRED_DOCUMENTS
(
  RDOC_CODE         NUMBER(15),
  RDOC_SHT_DESC     VARCHAR2(50 BYTE),
  ROC_DESC          VARCHAR2(50 BYTE),
  ROC_MANDATORY     VARCHAR2(1 BYTE),
  ROC_DATE_ADDED    DATE,
  ROC_EXEMPTED      VARCHAR2(10 BYTE),
  ROC_ACCOUNT_TYPE  VARCHAR2(20 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;