--
-- TQC_SYS_RPT_PARAMETERS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_SYS_RPT_PARAMETERS
(
  RPTP_CODE           NUMBER                    NOT NULL,
  RPTP_RPT_CODE       NUMBER,
  RPTP_PARAM_NAME     VARCHAR2(20 BYTE),
  RPTP_PARAM_DESC     VARCHAR2(100 BYTE),
  RPTP_PARAM_PROMPT   VARCHAR2(30 BYTE),
  RPTP_PARAM_TYPE     VARCHAR2(10 BYTE),
  RPTP_PARENT_CODE    NUMBER,
  RPTP_QUERY          VARCHAR2(2000 BYTE),
  RPTP_PARAM_CLAUSE   VARCHAR2(100 BYTE),
  RPTP_USER_REQUIRED  VARCHAR2(1 BYTE)          DEFAULT 'N',
  RPTP_CHILD_CODE     NUMBER,
  RPTP_PARAM_ACTIVE   VARCHAR2(50 BYTE)         DEFAULT NULL
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;