--
-- TQC_ACTIVITY_NOTES  (Table) 
--
CREATE TABLE TQ_CRM.TQC_ACTIVITY_NOTES
(
  ANT_CODE             NUMBER(8),
  ANT_ACC_CODE         NUMBER(8),
  ANT_CONTACT_CODE     NUMBER(8),
  ANT_SUBJECT          VARCHAR2(50 BYTE),
  ANT_NOTES            VARCHAR2(300 BYTE),
  ANT_ATTACHMENT       BLOB,
  ANT_ACT_CODE         NUMBER(8)                NOT NULL,
  ANT_ATTACHMENT_TYPE  VARCHAR2(50 BYTE),
  ANT_FILE_NAME        VARCHAR2(100 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;