--
-- TQC_ORG_DIVISION_LEVELS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_ORG_DIVISION_LEVELS
(
  ODL_CODE      VARCHAR2(10 BYTE)               NOT NULL,
  ODL_DLT_CODE  VARCHAR2(5 BYTE)                NOT NULL,
  ODL_DESC      VARCHAR2(50 BYTE)               NOT NULL,
  ODL_RANKING   NUMBER(2)                       NOT NULL,
  ODL_TYPE      VARCHAR2(1 BYTE)                DEFAULT 'O'
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

COMMENT ON TABLE TQ_CRM.TQC_ORG_DIVISION_LEVELS IS 'For defining organization subdivision Level';

COMMENT ON COLUMN TQ_CRM.TQC_ORG_DIVISION_LEVELS.ODL_CODE IS 'Short Description';

COMMENT ON COLUMN TQ_CRM.TQC_ORG_DIVISION_LEVELS.ODL_DLT_CODE IS 'Foreign key from heirarchy types';

COMMENT ON COLUMN TQ_CRM.TQC_ORG_DIVISION_LEVELS.ODL_DESC IS 'Description';

COMMENT ON COLUMN TQ_CRM.TQC_ORG_DIVISION_LEVELS.ODL_RANKING IS 'Ranking';