--
-- TQC_AGENCY_HOLDING_COMPANY  (Table) 
--
CREATE TABLE TQ_CRM.TQC_AGENCY_HOLDING_COMPANY
(
  AHC_CODE              NUMBER(15),
  AHC_NAME              VARCHAR2(254 BYTE),
  AHC_POSTAL_ADDRESS    VARCHAR2(300 BYTE),
  AHC_PHYSICAL_ADDRESS  VARCHAR2(300 BYTE),
  AHC_TELEPHONE_NUMBER  VARCHAR2(50 BYTE),
  AHC_MOBILE_NUMBER     VARCHAR2(50 BYTE),
  AHC_CONTACT_PERSON    VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

COMMENT ON COLUMN TQ_CRM.TQC_AGENCY_HOLDING_COMPANY.AHC_CODE IS 'UNIQUE CODE FOR EACH HOLDING COMPANY';

COMMENT ON COLUMN TQ_CRM.TQC_AGENCY_HOLDING_COMPANY.AHC_NAME IS 'NAME OF THE HOLDING COMPANY THAT HAS DIVISIONS E.G AON MINET BROKERS';