--
-- TQC_WEB_CLIENTS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_WEB_CLIENTS
(
  WCLNT_CODE         NUMBER(22),
  WCLNT_POL_ID       NUMBER(22,5),
  WCLNT_SURNAME      VARCHAR2(200 BYTE),
  WCLNT_OTHERNAMES   VARCHAR2(100 BYTE),
  WCLNT_TOWN         VARCHAR2(30 BYTE),
  WCLNT_ADDRESS      VARCHAR2(300 BYTE),
  WCLNT_POSTAL_CODE  VARCHAR2(200 BYTE),
  WCLNT_TEL          VARCHAR2(35 BYTE),
  WCLNT_TEL2         VARCHAR2(35 BYTE),
  WCLNT_FAX          VARCHAR2(35 BYTE),
  WCLNT_SHT_DESC     VARCHAR2(35 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;