--
-- TQC_PORTS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_PORTS
(
  PORT_CODE          NUMBER,
  PORT_COUNTRY_ISO3  VARCHAR2(15 BYTE),
  PORT_NAME          VARCHAR2(50 BYTE),
  PORT_COUNTRY_ISO   VARCHAR2(60 BYTE),
  PORT_TYPE          VARCHAR2(10 BYTE),
  PORT_SHT_DESC      VARCHAR2(10 BYTE),
  PORT_COUNTRY_ID    NUMBER
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;