--
-- TQC_COMPANY_MEMOS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_COMPANY_MEMOS
(
  COMEM_CODE              NUMBER(15)            NOT NULL,
  COMEM_SYS_CODE          NUMBER(8)             NOT NULL,
  COMEM_DESC              VARCHAR2(100 BYTE),
  COMEM_DATE              DATE,
  COMEM_CMB_CLAIM_NO      VARCHAR2(30 BYTE),
  COMEM_SUBJECT           VARCHAR2(300 BYTE),
  COMEM_REG_CLMT_CODE     NUMBER(22),
  COMEM_ADDRESS           VARCHAR2(200 BYTE),
  COMEM_COMMENTS          VARCHAR2(300 BYTE),
  COMEM_POL_POLICY_NO     VARCHAR2(30 BYTE),
  COMEM_APPL_LVL          VARCHAR2(2 BYTE),
  COMEM_DONE_BY           VARCHAR2(100 BYTE),
  COMEM_AUTHORIZED        VARCHAR2(1 BYTE),
  COMEM_YOUR_REF          VARCHAR2(40 BYTE)     DEFAULT 'Dear Sir/Madam,',
  COMEM_ADDRESSEE         VARCHAR2(500 BYTE),
  COMEM_SIGNATORY         VARCHAR2(200 BYTE),
  COMEM_CC_LIST           VARCHAR2(300 BYTE),
  COMEM_MTYP_CODE         NUMBER(15),
  COMEM_POL_REN_ENDOS_NO  VARCHAR2(20 BYTE),
  COMEM_BRN_CODE          NUMBER(10),
  COMEM_PREPARED_BY       VARCHAR2(30 BYTE),
  COMEM_CORR_CODE         NUMBER(5),
  COMEM_REF               VARCHAR2(100 BYTE),
  COMEM_POL_BATCH_NO      NUMBER(20),
  COMEM_AUTHORIZED_DATE   DATE,
  COMEM_FILE_NO           VARCHAR2(40 BYTE),
  COMEM_AUTHORIZED_BY     VARCHAR2(40 BYTE),
  COMEM_SIGN_RANK         VARCHAR2(100 BYTE)    DEFAULT 'FOR THE COMPANY',
  COMEM_INSURED           VARCHAR2(500 BYTE),
  COMEM_RPT_TYPE          VARCHAR2(1 BYTE)      DEFAULT 'L',
  COMEM_ADDRESSEE_TYPE    NUMBER(5)             DEFAULT 3,
  COMEM_EDITS             NUMBER                DEFAULT 0,
  COMEM_REMINDERS         NUMBER                DEFAULT 0,
  COMEM_PRP_CODE          NUMBER,
  COMEM_STATUS            VARCHAR2(5 BYTE)      DEFAULT 'L',
  COMEM_CANCEL_DATE       DATE,
  COMEM_CANCEL_BY         VARCHAR2(30 BYTE),
  COMEM_CODETOWN          VARCHAR2(45 BYTE),
  COMEM_PRO_DESC          VARCHAR2(50 BYTE),
  COMEM_COURT_CASE_NO     VARCHAR2(20 BYTE),
  COMEM_GCC_CODE          NUMBER(22),
  COMEM_QUOT_CODE         NUMBER(22),
  COMEM_QUOT_NO           VARCHAR2(30 BYTE),
  COMEM_EMAIL_ADDR        VARCHAR2(200 BYTE),
  COMEM_SHOW_END_CLS      VARCHAR2(1 BYTE),
  COMEM_ISSUED            VARCHAR2(1 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

COMMENT ON COLUMN TQ_CRM.TQC_COMPANY_MEMOS.COMEM_STATUS IS '''L - LIVE T -TESTING  D - DELETED  C - CANCELLED''';