--
-- TQC_BANK_BRANCHES  (Table) 
--
CREATE TABLE TQ_CRM.TQC_BANK_BRANCHES
(
  BBR_CODE             NUMBER(8)                NOT NULL,
  BBR_BNK_CODE         NUMBER(8)                NOT NULL,
  BBR_BRANCH_NAME      VARCHAR2(100 BYTE),
  BBR_REMARKS          VARCHAR2(250 BYTE),
  BBR_SHT_DESC         VARCHAR2(15 BYTE)        NOT NULL,
  BBR_REF_CODE         VARCHAR2(20 BYTE),
  BBR_EFT_SUPPORTED    VARCHAR2(1 BYTE)         DEFAULT 'N',
  BBR_DD_SUPPORTED     VARCHAR2(25 BYTE),
  BBR_DATE_CREATED     DATE,
  BBR_CREATED_BY       VARCHAR2(15 BYTE)        NOT NULL,
  BBR_PHYSICAL_ADDRS   VARCHAR2(200 BYTE),
  BBR_POSTAL_ADDRS     VARCHAR2(100 BYTE),
  BBR_KBA_CODE         NUMBER(3),
  BBR_BNKT_SHT_DESC    VARCHAR2(100 BYTE),
  BBR_EMAIL            VARCHAR2(100 BYTE),
  BBR_PERSON_NAME      VARCHAR2(100 BYTE),
  BBR_PERSON_EMAIL     VARCHAR2(100 BYTE),
  BBR_PERSON_COU_CODE  VARCHAR2(100 BYTE),
  BBR_PERSON_PHONE     VARCHAR2(100 BYTE),
  BBR_TER_CODE         NUMBER,
  BBR_BNKT_CODE        NUMBER(20)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          384K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

COMMENT ON COLUMN TQ_CRM.TQC_BANK_BRANCHES.BBR_DD_SUPPORTED IS 'DIRECT DEBIT ENABLED (Y/N)';