--
-- TQC_ACCOUNT_TYPES  (Table) 
--
CREATE TABLE TQ_CRM.TQC_ACCOUNT_TYPES
(
  ACT_CODE                 NUMBER(8)            NOT NULL,
  ACT_ACCOUNT_TYPE         VARCHAR2(50 BYTE),
  ACT_TYPE_SHT_DESC        VARCHAR2(60 BYTE),
  ACT_WTHTX_RATE           NUMBER(25,5),
  ACT_TYPE_ID              VARCHAR2(2 BYTE)     NOT NULL,
  ACT_COMM_RESERVE_RATE    NUMBER(5,2),
  ACT_MAX_ADV_AMT          NUMBER(23,5),
  ACT_MAX_ADV_RPYMT_PRD    NUMBER(5),
  ACT_RCPTS_INCLUDE_COMM   VARCHAR2(1 BYTE)     DEFAULT 'N',
  ACT_OVERIDE_RATE         NUMBER(10,5),
  ACT_ID_SERIAL_FORMAT     VARCHAR2(60 BYTE),
  ACT_VAT_RATE             NUMBER(23,5),
  ACT_FORMAT               VARCHAR2(100 BYTE),
  ACT_ODL_CODE             VARCHAR2(10 BYTE),
  ACT_NO_GEN_CODE          VARCHAR2(15 BYTE),
  ACT_LTA_WHTX_RATE        NUMBER(23,5),
  ACT_COMMISION_LEVY_RATE  NUMBER,
  ACT_NEXT_NO              NUMBER(22),
  ACT_SUFFIX               VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

COMMENT ON COLUMN TQ_CRM.TQC_ACCOUNT_TYPES.ACT_ODL_CODE IS 'Foreign Key to TQC_ORG_DIVISION_LEVELS. It should not be enforced.';

COMMENT ON COLUMN TQ_CRM.TQC_ACCOUNT_TYPES.ACT_NO_GEN_CODE IS 'Used in the generation of Agent Nos.';