--
-- TQC_MSG_TEMPLATES  (Table) 
--
CREATE TABLE TQ_CRM.TQC_MSG_TEMPLATES
(
  MSGT_CODE           NUMBER(5)                 NOT NULL,
  MSGT_SHT_DESC       VARCHAR2(15 BYTE),
  MSGT_MSG            VARCHAR2(4000 BYTE),
  MSGT_SYS_CODE       NUMBER(8)                 NOT NULL,
  MSGT_SYS_MODULE     VARCHAR2(2 BYTE),
  MSGT_TYPE           VARCHAR2(5 BYTE)          NOT NULL,
  MSGT_DEFAULT        VARCHAR2(1 BYTE)          DEFAULT 'N',
  MSGT_CREATED_BY     VARCHAR2(100 BYTE),
  MSGT_UPDATED_BY     VARCHAR2(100 BYTE),
  MSGT_MSG_SUBJECT    VARCHAR2(60 BYTE),
  MSGT_PROD_CODE      VARCHAR2(100 BYTE),
  MSGT_SYS_PROD       VARCHAR2(60 BYTE),
  MSGT_SYS_PROD_NAME  VARCHAR2(60 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          128K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;