--
-- TQC_ACCOUNT_CONTACTS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_ACCOUNT_CONTACTS
(
  ACCC_CODE             NUMBER(15),
  ACCC_NAME             VARCHAR2(75 BYTE),
  ACCC_OTHER_NAMES      VARCHAR2(100 BYTE),
  ACCC_DOB              DATE,
  ACCC_TEL              VARCHAR2(35 BYTE),
  ACCC_EMAIL_ADDR       VARCHAR2(100 BYTE),
  ACCC_SMS_TEL          VARCHAR2(35 BYTE),
  ACCC_USERNAME         VARCHAR2(15 BYTE),
  ACCC_PWD              VARCHAR2(50 BYTE),
  ACCC_LOGIN_ALLOWED    VARCHAR2(1 BYTE)        DEFAULT 'N'                   NOT NULL,
  ACCC_PWD_CHANGED      DATE                    NOT NULL,
  ACCC_PWD_RESET        VARCHAR2(2 BYTE),
  ACCC_DT_CREATED       DATE,
  ACCC_STATUS           VARCHAR2(2 BYTE),
  ACCC_LOGIN_ATTEMPTS   NUMBER(8),
  ACCC_PERSONEL_RANK    VARCHAR2(50 BYTE),
  ACCC_LAST_LOGIN_DATE  DATE,
  ACCC_CREATED_BY       VARCHAR2(50 BYTE),
  ACCC_ACC_TYPE         VARCHAR2(1 BYTE)        DEFAULT 'A',
  ACCC_ACC_CODE         NUMBER(25),
  ACCC_AGN_CODE         NUMBER,
  ACCC_SYS_CODE         NUMBER,
  ACCC_GSP_CODE         NUMBER,
  ACCC_TSP_CODE         NUMBER,
  ACCC_TSA_CODE         NUMBER,
  ACCC_USR_CODE         NUMBER,
  ACCC_RESET_CODE       NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;