--
-- TQC_IPRS_DATA  (Table) 
--
CREATE TABLE TQ_CRM.TQC_IPRS_DATA
(
  IPRS_CODE          NUMBER,
  IPRS_IDNO          VARCHAR2(80 BYTE),
  IPRS_PINNO         VARCHAR2(80 BYTE),
  IPRS_PASSPORT      VARCHAR2(80 BYTE),
  IPRS_DOB           DATE,
  IPRS_FIRSTNAME     VARCHAR2(80 BYTE),
  IPRS_SURNAME       VARCHAR2(80 BYTE),
  IPRS_OTHERNAMES    VARCHAR2(80 BYTE),
  IPRS_GENDER        VARCHAR2(80 BYTE),
  IPRS_FETCH_TYPE    VARCHAR2(1 BYTE),
  IPRS_VALIDATED_BY  VARCHAR2(100 BYTE),
  IPRS_VALIDATED_DT  DATE
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;