--
-- TQC_MEMO_DETAILS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_MEMO_DETAILS
(
  MEMDET_CODE       NUMBER(22)                  NOT NULL,
  MEMDET_CONTENT    VARCHAR2(4000 BYTE),
  MEMDET_MEMO_CODE  NUMBER(22)                  NOT NULL,
  MEMDET_FOOTER     VARCHAR2(1000 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;