--
-- TQC_SYS_POST_LEVELS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_SYS_POST_LEVELS
(
  SYSPL_SYS_CODE  NUMBER(8)                     NOT NULL,
  SYSPL_CODE      NUMBER(8)                     NOT NULL,
  SYSPL_SHT_DESC  VARCHAR2(10 BYTE)             NOT NULL,
  SYSPL_DESC      VARCHAR2(50 BYTE)             NOT NULL,
  SYSPL_RANKING   NUMBER(3)                     NOT NULL,
  SYSPL_WEF       DATE                          NOT NULL
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

COMMENT ON TABLE TQ_CRM.TQC_SYS_POST_LEVELS IS 'For storing system Post Levels';

COMMENT ON COLUMN TQ_CRM.TQC_SYS_POST_LEVELS.SYSPL_SYS_CODE IS 'System FK';

COMMENT ON COLUMN TQ_CRM.TQC_SYS_POST_LEVELS.SYSPL_CODE IS 'PK';

COMMENT ON COLUMN TQ_CRM.TQC_SYS_POST_LEVELS.SYSPL_SHT_DESC IS 'Short Description';

COMMENT ON COLUMN TQ_CRM.TQC_SYS_POST_LEVELS.SYSPL_DESC IS 'Description';

COMMENT ON COLUMN TQ_CRM.TQC_SYS_POST_LEVELS.SYSPL_RANKING IS 'Ranking';

COMMENT ON COLUMN TQ_CRM.TQC_SYS_POST_LEVELS.SYSPL_WEF IS 'With Effect From Date';