--
-- TQC_DEP_INCIDENT_TYPES  (Table) 
--
CREATE TABLE TQ_CRM.TQC_DEP_INCIDENT_TYPES
(
  DEPICT_CODE              NUMBER(8)            NOT NULL,
  DEPICT_INCT_CODE         NUMBER(8)            NOT NULL,
  DEPICT_INCT_SHT_DESC     VARCHAR2(15 BYTE)    NOT NULL,
  DEPICT_DEP_CODE          NUMBER(8),
  DEPICT_IDEP_CODE         NUMBER(8),
  DEPICT_PRIORITY_LVL      VARCHAR2(1 BYTE)     DEFAULT 'N'                   NOT NULL,
  DEPICT_ESC_DAYS          NUMBER(10,5),
  DEPICT_CLOSE_DAYS        NUMBER(10,5),
  DEPICT_ESCALATE          VARCHAR2(1 BYTE)     DEFAULT 'N',
  DEPICT_SEND_EMAIL        VARCHAR2(1 BYTE)     DEFAULT 'N',
  DEPICT_DEFAULT_USR_CODE  NUMBER(15)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;