--
-- TQC_C2BM_TRANSACTIONS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_C2BM_TRANSACTIONS
(
  C2BM_TRANS_CODE               NUMBER,
  C2BM_TRANS_ID                 VARCHAR2(100 BYTE),
  C2BM_TRANS_TYPE               VARCHAR2(50 BYTE),
  C2BM_TRANS_TIME               DATE,
  C2BM_TRANS_AMT                NUMBER,
  C2BM_TRANS_BUSSINES_SHT_CODE  VARCHAR2(100 BYTE),
  C2BM_TRANS_BILLREF_NO         VARCHAR2(100 BYTE),
  C2BM_TRANS_INVOICE_NO         VARCHAR2(100 BYTE),
  C2BM_TRANS_MSISDN             VARCHAR2(100 BYTE),
  C2BM_TRANS_ORGACCOUNTBAL      NUMBER,
  C2BM_TRANS_VALIDATED          VARCHAR2(1 BYTE),
  C2BM_TRANS_CONFIRMED          VARCHAR2(1 BYTE),
  C2BM_TRANS_KYC_FIRSTNAME      VARCHAR2(100 BYTE),
  C2BM_TRANS_KYC_MIDDLENAME     VARCHAR2(100 BYTE),
  C2BM_TRANS_KYC_LASTNAME       VARCHAR2(100 BYTE),
  C2BM_TRANS_STATUS             VARCHAR2(1 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;