--
-- TQC_BRANCH_CONTACTS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_BRANCH_CONTACTS
(
  TBC_CODE              NUMBER,
  TBC_NAME              VARCHAR2(200 BYTE),
  TBC_DESIGNATION       VARCHAR2(100 BYTE),
  TBC_MOBILE_NUMBER     VARCHAR2(100 BYTE),
  TBC_TELEPHONE         VARCHAR2(100 BYTE),
  TBC_ID_NUMBER         VARCHAR2(50 BYTE),
  TBC_PHYSICAL_ADDRESS  VARCHAR2(200 BYTE),
  TBC_EMAIL_ADDRESS     VARCHAR2(100 BYTE),
  TBC_BRN_CODE          NUMBER
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;