--
-- TQC_WEB_PROD_OPTIONS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_WEB_PROD_OPTIONS
(
  TWPO_CODE       NUMBER,
  TWPO_POP_CODE   NUMBER,
  TWPO_DESC       VARCHAR2(4000 BYTE),
  TWPO_BIND_CODE  NUMBER,
  TWPO_TWP_CODE   NUMBER
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;