--
-- TQC_BANK_IMP_TMPLT  (Table) 
--
CREATE TABLE TQ_CRM.TQC_BANK_IMP_TMPLT
(
  LPIT_CODE            NUMBER(25),
  LPIT_BNK_CODE        NUMBER(22),
  LPIT_TABLE_NAME      VARCHAR2(50 BYTE),
  LPIT_COL1_NAME       VARCHAR2(20 BYTE),
  LPIT_COL1_POSITION   NUMBER(5),
  LPIT_COL1_MAPPING    VARCHAR2(50 BYTE),
  LPIT_COL2_NAME       VARCHAR2(50 BYTE),
  LPIT_COL2_POSITION   NUMBER(5),
  LPIT_COL2_MAPPING    VARCHAR2(50 BYTE),
  LPIT_COL3_NAME       VARCHAR2(20 BYTE),
  LPIT_COL3_POSITION   NUMBER(5),
  LPIT_COL3_MAPPING    VARCHAR2(50 BYTE),
  LPIT_COL4_NAME       VARCHAR2(20 BYTE),
  LPIT_COL4_POSITION   NUMBER(5),
  LPIT_COL4_MAPPING    VARCHAR2(50 BYTE),
  LPIT_COL5_NAME       VARCHAR2(20 BYTE),
  LPIT_COL5_POSITION   NUMBER(5),
  LPIT_COL5_MAPPING    VARCHAR2(50 BYTE),
  LPIT_COL6_NAME       VARCHAR2(20 BYTE),
  LPIT_COL6_POSITION   NUMBER(5),
  LPIT_COL6_MAPPING    VARCHAR2(50 BYTE),
  LPIT_COL7_NAME       VARCHAR2(20 BYTE),
  LPIT_COL7_POSITION   NUMBER(5),
  LPIT_COL7_MAPPING    VARCHAR2(50 BYTE),
  LPIT_COL8_NAME       VARCHAR2(20 BYTE),
  LPIT_COL8_POSITION   NUMBER(5),
  LPIT_COL8_MAPPING    VARCHAR2(50 BYTE),
  LPIT_COL9_NAME       VARCHAR2(20 BYTE),
  LPIT_COL9_POSITION   NUMBER(5),
  LPIT_COL9_MAPPING    VARCHAR2(50 BYTE),
  LPIT_COL10_NAME      VARCHAR2(20 BYTE),
  LPIT_COL10_POSITION  NUMBER(5),
  LPIT_COL10_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL11_NAME      VARCHAR2(20 BYTE),
  LPIT_COL11_POSITION  NUMBER(5),
  LPIT_COL11_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL12_NAME      VARCHAR2(20 BYTE),
  LPIT_COL12_POSITION  NUMBER(5),
  LPIT_COL12_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL13_NAME      VARCHAR2(20 BYTE),
  LPIT_COL13_POSITION  NUMBER(5),
  LPIT_COL13_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL14_NAME      VARCHAR2(20 BYTE),
  LPIT_COL14_POSITION  NUMBER(5),
  LPIT_COL14_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL15_NAME      VARCHAR2(20 BYTE),
  LPIT_COL15_POSITION  NUMBER(5),
  LPIT_COL15_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL16_NAME      VARCHAR2(50 BYTE),
  LPIT_COL16_POSITION  NUMBER(5),
  LPIT_COL16_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL17_NAME      VARCHAR2(20 BYTE),
  LPIT_COL17_POSITION  NUMBER(5),
  LPIT_COL17_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL18_NAME      VARCHAR2(20 BYTE),
  LPIT_COL18_POSITION  NUMBER(5),
  LPIT_COL18_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL19_NAME      VARCHAR2(20 BYTE),
  LPIT_COL19_POSITION  NUMBER(5),
  LPIT_COL19_MAPPING   VARCHAR2(50 BYTE),
  LPIT_COL20_NAME      VARCHAR2(20 BYTE),
  LPIT_COL20_POSITION  NUMBER(5),
  LPIT_COL20_MAPPING   VARCHAR2(50 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;