--
-- TQC_CALENDAR_ACTIVITIES  (Table) 
--
CREATE TABLE TQ_CRM.TQC_CALENDAR_ACTIVITIES
(
  CALA_CODE          NUMBER(25),
  CALA_LOCATION      VARCHAR2(50 BYTE),
  CALA_TITLE         VARCHAR2(50 BYTE),
  CALA_STARTADDDAYS  NUMBER(15),
  CALA_STARTHOUR     NUMBER(15),
  CALA_STARTMIN      NUMBER(15),
  CALA_ENDADDDAYS    NUMBER(15),
  CALA_ENDADDHOURS   NUMBER(15),
  CALA_ENDADDMIN     NUMBER(15),
  CALA_USER          VARCHAR2(50 BYTE)          NOT NULL,
  CALA_CREATE_DATE   DATE
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;