--
-- TQC_SYS_DOC_TYPES  (Table) 
--
CREATE TABLE TQ_CRM.TQC_SYS_DOC_TYPES
(
  SDT_CODE             NUMBER,
  SDT_CONTENT_NAME     VARCHAR2(30 BYTE)        NOT NULL,
  SDT_CONTENT_DESC     VARCHAR2(100 BYTE),
  SDT_CONTENT_TYPE     VARCHAR2(100 BYTE),
  SDT_CONTENT_MAPPING  VARCHAR2(30 BYTE),
  SDT_TYPE_MAPPING     VARCHAR2(30 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;