--
-- TQC_FORM_FIELDS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_FORM_FIELDS
(
  FM_CODE            NUMBER                     NOT NULL,
  FM_MODULE          VARCHAR2(50 BYTE)          NOT NULL,
  FM_FIELD_NAME      VARCHAR2(50 BYTE)          NOT NULL,
  FM_MANDATORY       VARCHAR2(1 BYTE)           DEFAULT 'N',
  FM_FIELD_LABEL     VARCHAR2(200 BYTE),
  FM_VISIBLE         VARCHAR2(1 BYTE),
  FM_SCREEN_NAME     VARCHAR2(100 BYTE),
  FM_DISABLED        VARCHAR2(1 BYTE)           DEFAULT 'N',
  FM_LMS_MANDATORY   VARCHAR2(1 BYTE)           DEFAULT 'N',
  FM_GIS_MANDATORY   VARCHAR2(1 BYTE)           DEFAULT 'N',
  FM_UI_ID           VARCHAR2(40 BYTE),
  FM_VALIDATE        VARCHAR2(1 BYTE),
  FM_GROUP_ID        VARCHAR2(100 BYTE),
  FM_SESSION_ID      VARCHAR2(100 BYTE),
  FM_GROUP_ORDERING  NUMBER(22)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;