--
-- TQC_INCIDENT_STATUS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_INCIDENT_STATUS
(
  INCS_CODE               NUMBER(15)            NOT NULL,
  INCS_INC_CODE           NUMBER(15)            NOT NULL,
  INCS_ICTY_CODE          NUMBER(8)             NOT NULL,
  INCS_ICTY_SHT_DESC      VARCHAR2(30 BYTE)     NOT NULL,
  INCS_ICTY_DATE          DATE                  NOT NULL,
  INCS_ICTY_BY            VARCHAR2(30 BYTE)     NOT NULL,
  INCS_ALLOC_TO           VARCHAR2(30 BYTE),
  INCS_ALLOC_DATE         DATE,
  INCS_REFERAL_INCS_CODE  NUMBER(15),
  INCS_ACKNOWLEDGED       VARCHAR2(2 BYTE)      DEFAULT 'N',
  INCS_EXP_ACT_DATE       DATE                  NOT NULL,
  INCS_ESCALATION_DATE    DATE,
  INCS_PRIORITY           VARCHAR2(2 BYTE)      NOT NULL,
  INCS_STATUS             VARCHAR2(15 BYTE)     NOT NULL,
  INCS_STATUS_DATE        DATE                  NOT NULL,
  INCS_COMMENTS           VARCHAR2(1000 BYTE),
  INCS_DEP_CODE           NUMBER(8),
  INCS_IDEP_CODE          NUMBER(8),
  INCS_SYS_CODE           NUMBER,
  INCS_DISP_DATE          DATE,
  INCS_CHEQUE_NO          VARCHAR2(20 BYTE),
  INCS_DESTINATION        VARCHAR2(30 BYTE),
  INCS_DISP_BY            VARCHAR2(30 BYTE),
  INCS_CHEQUE_AMT         NUMBER(23,5),
  INCS_CHEQUE_PAYEE       VARCHAR2(80 BYTE),
  INCS_FROM_TRANS         VARCHAR2(30 BYTE),
  INCS_ESCALATE           VARCHAR2(1 BYTE)      DEFAULT 'N'                   NOT NULL,
  INCS_CURRENT_STATUS     VARCHAR2(1 BYTE)      DEFAULT 'N',
  INCS_CHEQUE_DATE        DATE,
  INCS_CHEQUE_UPDT_DATE   DATE,
  INCS_CHEQUE_UPDTD_BY    VARCHAR2(30 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          5M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;