--
-- TQC_BPM_TICKETS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_BPM_TICKETS
(
  TCKT_CODE             NUMBER(15),
  TCKT_SYS_CODE         NUMBER(8)               NOT NULL,
  TCKT_SYS_MODULE       VARCHAR2(50 BYTE)       DEFAULT 'U'                   NOT NULL,
  TCKT_CLNT_CODE        NUMBER(15),
  TCKT_AGN_CODE         NUMBER(15),
  TCKT_POL_CODE         NUMBER(15),
  TCKT_POL_NO           VARCHAR2(35 BYTE),
  TCKT_CLM_NO           VARCHAR2(35 BYTE),
  TCKT_QUOT_CODE        NUMBER(15),
  TCKT_BY               VARCHAR2(35 BYTE),
  TCKT_DATE             DATE,
  TCKT_PROCESS_ID       VARCHAR2(50 BYTE),
  TCKT_QUO_NO           VARCHAR2(100 BYTE),
  TCKT_SPRSA_CODE       NUMBER(15),
  TCKT_ENDR_CODE        NUMBER(15),
  TCKT_PROD_TYPE        VARCHAR2(20 BYTE),
  TCKT_TO               VARCHAR2(100 BYTE),
  TCKT_REMARKS          VARCHAR2(300 BYTE),
  TCKT_ENDORSEMENT      VARCHAR2(25 BYTE),
  TCKT_TRANSNO          NUMBER(15),
  TCKT_ACTIVE           VARCHAR2(10 BYTE)       DEFAULT 'Y',
  TCKT_PRP_CODE         NUMBER,
  TCKT_EXTERN_REF_NO    VARCHAR2(100 BYTE),
  TCKT_TYPE             VARCHAR2(1 BYTE)        DEFAULT 'S',
  TCKT_CLA_TYPE         VARCHAR2(5 BYTE),
  TCKT_ADHOC_NAME       VARCHAR2(100 BYTE),
  TCKT_TRAN_EFF_DATE    DATE,
  TCKT_GGT_NO           NUMBER,
  TCKT_CQR_NO           NUMBER(15),
  TCKT_ASSIGNED_BY      VARCHAR2(50 BYTE),
  TCKT_ASSIGNMENT_DATE  DATE,
  TCKT_ENTITY_CODE      NUMBER(22),
  TCKT_SPRC_SHT_DESC    VARCHAR2(64 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          1M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;