--
-- TQC_DIRECT_DEBIT_DETAIL  (Table) 
--
CREATE TABLE TQ_CRM.TQC_DIRECT_DEBIT_DETAIL
(
  DDD_CODE                NUMBER(8)             NOT NULL,
  DDD_DDH_CODE            NUMBER(8)             NOT NULL,
  DDD_DD_CODE             NUMBER(8)             NOT NULL,
  DDD_SYS_CODE            NUMBER(8)             NOT NULL,
  DDD_POL_CODE            NUMBER(15),
  DDD_POL_PRP_CODE        NUMBER(15),
  DDD_POL_PROPOSAL_NO     VARCHAR2(15 BYTE),
  DDD_POL_POLICY_NO       VARCHAR2(30 BYTE),
  DDD_OTHER_IDENTIFIER    VARCHAR2(30 BYTE),
  DDD_AMOUNT              NUMBER,
  DDD_REMARKS             VARCHAR2(2000 BYTE),
  DDD_START_DT            DATE,
  DDD_STOP_DATE           DATE,
  DDD_STATUS              VARCHAR2(1 BYTE)      DEFAULT 'D'                   NOT NULL,
  DDD_FAIL_DATE           DATE,
  DDD_RECEIPTED           VARCHAR2(1 BYTE)      DEFAULT 'N'                   NOT NULL,
  DDD_FAIL_UPDATED_BY     VARCHAR2(30 BYTE),
  DDD_FAIL_UPDATE_DATE    DATE,
  DDD_PPR_CODE            NUMBER(15),
  DDD_POL_TYPE            VARCHAR2(5 BYTE),
  DDD_RECEIPTED_BY        VARCHAR2(50 BYTE),
  DDD_RECEIPT_NO          VARCHAR2(50 BYTE),
  DDD_RECEIPT_DATE        DATE,
  DDD_RECEIPTED_DATE      DATE,
  DDD_FAIL_REMARKS        VARCHAR2(100 BYTE),
  DDD_RELAUNCH_DATE       DATE,
  DDD_RELAUNCH_STOP_DATE  DATE,
  DDD_RELAUNCHED_BY       VARCHAR2(30 BYTE),
  DDD_RELAUNCH_STOPED_BY  VARCHAR2(30 BYTE),
  DDD_TYPE                VARCHAR2(5 BYTE),
  DDD_POL_FREQ_PYMNT      VARCHAR2(5 BYTE),
  DDD_PREM_DUE_DATE       DATE,
  DDD_REC_NO              NUMBER,
  DDD_BANK_AMOUNT         NUMBER
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

COMMENT ON COLUMN TQ_CRM.TQC_DIRECT_DEBIT_DETAIL.DDD_STATUS IS '(D)RAFT; (A)UTHORIZED; (F)AILED';

COMMENT ON COLUMN TQ_CRM.TQC_DIRECT_DEBIT_DETAIL.DDD_RECEIPTED IS '(N)O; (Y)ES';