--
-- TQC_INCIDENTS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_INCIDENTS
(
  INC_CODE              NUMBER(15)              NOT NULL,
  INC_BRN_CODE          NUMBER(8)               NOT NULL,
  INC_DEP_CODE          VARCHAR2(8 BYTE),
  INC_INCT_CODE         NUMBER(8)               NOT NULL,
  INC_INCT_SHT_DESC     VARCHAR2(30 BYTE)       NOT NULL,
  INC_DATE              DATE                    NOT NULL,
  INC_ORIGIN            VARCHAR2(100 BYTE),
  INC_ADDRESSED_TO      VARCHAR2(30 BYTE),
  INC_RECEIVED_BY       VARCHAR2(30 BYTE),
  INC_REMARKS           VARCHAR2(200 BYTE),
  INC_POL_CODE          NUMBER(15),
  INC_POL_POLICY_NO     VARCHAR2(26 BYTE),
  INC_POL_REN_ENDOS_NO  VARCHAR2(26 BYTE),
  INC_CLM_NO            VARCHAR2(25 BYTE),
  INC_PPR_CODE          NUMBER(15),
  INC_MKT_PROP_NO       VARCHAR2(22 BYTE),
  INCC_MAILED           VARCHAR2(2 BYTE),
  INC_IDEP_CODE         NUMBER(8)               NOT NULL,
  INC_RECEIPT_DT        DATE,
  INC_BRN_FROM          VARCHAR2(25 BYTE),
  INC_PROPOSAL_NO       VARCHAR2(20 BYTE),
  INC_QUOT_NO           VARCHAR2(100 BYTE),
  INC_SHT_DESC          VARCHAR2(75 BYTE)       NOT NULL,
  INC_EMAIL_CODE        NUMBER(15),
  INC_SMS_CODE          NUMBER(15),
  INC_EDOCS_CODE        NUMBER(15),
  INC_DEPICT_CODE       NUMBER(10),
  INC_IDEP_SHT_DESC     VARCHAR2(35 BYTE),
  INC_SEND_EMAIL        VARCHAR2(1 BYTE)        DEFAULT 'N'
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          4M
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;