--
-- TQC_SYSTEM_ROUTINES  (Table) 
--
CREATE TABLE TQ_CRM.TQC_SYSTEM_ROUTINES
(
  TSR_CODE          NUMBER,
  TSR_SYS_CODE      NUMBER,
  TSR_SHT_DESC      VARCHAR2(50 BYTE),
  TSR_FUNCTION      VARCHAR2(100 BYTE),
  TSR_DESCRIPTIONS  VARCHAR2(2500 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;