--
-- TQC_AGENTS_TO_LOAD  (Table) 
--
CREATE TABLE TQ_CRM.TQC_AGENTS_TO_LOAD
(
  ACCOUNTCODE    VARCHAR2(30 BYTE),
  ACCOUNTTYPE    NUMBER,
  ACCOUNTNAME    VARCHAR2(300 BYTE),
  AGENTADDRESS1  VARCHAR2(300 BYTE),
  AGENTADDRESS2  VARCHAR2(300 BYTE),
  CITYTOWNCODE   VARCHAR2(30 BYTE),
  IDNUMBER       VARCHAR2(30 BYTE),
  CONTACTPERSON  VARCHAR2(30 BYTE),
  PHONENO        VARCHAR2(30 BYTE),
  FAXNUMBER      VARCHAR2(30 BYTE),
  EMAILADDRESS   VARCHAR2(100 BYTE),
  JOININGDATE    VARCHAR2(30 BYTE),
  TOTALBALANCE   NUMBER,
  POSTEDON       VARCHAR2(30 BYTE),
  LOADED         VARCHAR2(1 BYTE)               DEFAULT 'N'                   NOT NULL,
  GIS_AGN_CODE   NUMBER,
  CREATEDBY      VARCHAR2(100 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          384K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;