--
-- TQC_PRIORITY_LEVELS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_PRIORITY_LEVELS
(
  PRL_CODE             NUMBER(8),
  PRL_DESCRIPTION      VARCHAR2(30 BYTE),
  PRL_SHT_DESCRIPTION  VARCHAR2(10 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;