--
-- TQC_TRANSFERS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_TRANSFERS
(
  TT_CODE             NUMBER(8)                 NOT NULL,
  TT_TRANS_TYPE       VARCHAR2(3 BYTE)          NOT NULL,
  TT_TRANS_DATE       DATE,
  TT_TRANS_TO_CODE    NUMBER,
  TT_TRANS_TO_NAME    VARCHAR2(80 BYTE),
  TT_TRANS_FROM_CODE  NUMBER,
  TT_TRANS_FROM_NAME  VARCHAR2(80 BYTE),
  TT_DONE_BY          VARCHAR2(80 BYTE),
  TT_DONE_DATE        DATE,
  TT_AUTHORIZED       VARCHAR2(80 BYTE),
  TT_AUTHORIZED_BY    VARCHAR2(80 BYTE),
  TT_AUTHORIZED_DATE  DATE
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;