--
-- TQC_CLIENT_ATTRIBUTES  (Table) 
--
CREATE TABLE TQ_CRM.TQC_CLIENT_ATTRIBUTES
(
  TCA_CODE            NUMBER,
  TCA_ATTRIBUTE_NAME  VARCHAR2(100 BYTE),
  TCA_ATT_DESC        VARCHAR2(300 BYTE),
  TCA_PROMPT          VARCHAR2(100 BYTE),
  TCA_ATT_RANGE       VARCHAR2(2 BYTE)          DEFAULT 'N',
  TCA_ATT_TYPE_INPUT  VARCHAR2(100 BYTE),
  TCA_COL_NAME        VARCHAR2(50 BYTE)         NOT NULL,
  TCA_TABLE_NAME      VARCHAR2(50 BYTE)         NOT NULL
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;