--
-- TQC_CLIENTS_TRACKING  (Table) 
--
CREATE TABLE TQ_CRM.TQC_CLIENTS_TRACKING
(
  CLNTT_CODE            NUMBER(15)              NOT NULL,
  CLNTT_UPDATED_FIELDS  VARCHAR2(2000 BYTE)     NOT NULL,
  CLNTT_PREV_VALUES     VARCHAR2(2000 BYTE)     NOT NULL,
  CLNTT_UPDATED_VALUES  VARCHAR2(2000 BYTE)     NOT NULL,
  CLNTT_DATE_UPDATED    DATE                    NOT NULL,
  CLNTT_UPDATED_BY      VARCHAR2(50 BYTE)       NOT NULL,
  CLNTT_CLNT_CODE       NUMBER                  NOT NULL
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;