--
-- TQC_PRINT_SERVERS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_PRINT_SERVERS
(
  SERV_CODE               NUMBER                NOT NULL,
  SERV_NAME               VARCHAR2(300 BYTE),
  SERV_FILTER             VARCHAR2(300 BYTE),
  SERV_URI                VARCHAR2(300 BYTE),
  SERV_FILTER_COMMAND     VARCHAR2(300 BYTE),
  SERV_SEC_USERNAME       VARCHAR2(300 BYTE),
  SERV_SEC_PASSWORD       VARCHAR2(300 BYTE),
  SERV_SEC_AUTH_TYPE      VARCHAR2(300 BYTE),
  SERV_SEC_ENCRPT_TYPE    VARCHAR2(300 BYTE),
  SERV_PROXY_HOST         VARCHAR2(300 BYTE),
  SERV_PROXY_PORT         VARCHAR2(300 BYTE),
  SERV_PROXY_USERNAME     VARCHAR2(300 BYTE),
  SERV_PROXY_PASWORD      VARCHAR2(300 BYTE),
  SERV_PROXY_AUTHEN_TYPE  VARCHAR2(300 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;