--
-- TQC_ENTITIES  (Table) 
--
CREATE TABLE TQ_CRM.TQC_ENTITIES
(
  ENT_CODE              NUMBER                  NOT NULL,
  ENT_SHT_DESC          VARCHAR2(200 BYTE),
  ENT_NAME              VARCHAR2(200 BYTE),
  ENT_PHYSICAL_ADDRESS  VARCHAR2(200 BYTE),
  ENT_POSTAL_ADDRESS    VARCHAR2(200 BYTE),
  ENT_TWN_CODE          NUMBER,
  ENT_COU_CODE          NUMBER,
  ENT_EMAIL_ADDRESS     VARCHAR2(200 BYTE),
  ENT_FAX               VARCHAR2(200 BYTE),
  ENT_STATUS            VARCHAR2(200 BYTE),
  ENT_BBR_CODE          NUMBER,
  ENT_BANK_ACC_NO       VARCHAR2(200 BYTE),
  ENT_ZIP               VARCHAR2(200 BYTE),
  ENT_SMS_TEL           VARCHAR2(200 BYTE),
  ENT_CREATED_BY        VARCHAR2(200 BYTE),
  ENT_DATE_CREATED      DATE,
  ENT_PIN               VARCHAR2(200 BYTE),
  ENT_TEL1              VARCHAR2(200 BYTE),
  ENT_ACC_NO            VARCHAR2(200 BYTE),
  ENT_STATUS_REMARKS    VARCHAR2(200 BYTE),
  ENT_BRN_CODE          NUMBER,
  ENT_ID_NO             VARCHAR2(200 BYTE),
  ENT_TEL2              VARCHAR2(200 BYTE),
  ENT_SEC_CODE          NUMBER,
  ENT_RUNOFF            VARCHAR2(1 BYTE),
  ENT_OLD_ACC_NO        VARCHAR2(200 BYTE),
  ENT_TITLE             VARCHAR2(200 BYTE),
  ENT_WEF               DATE,
  ENT_WET               DATE,
  ENT_CONTACT_PERSON    VARCHAR2(200 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;