--
-- TQC_CLIENT_WEB_PWD_HIST  (Table) 
--
CREATE TABLE TQ_CRM.TQC_CLIENT_WEB_PWD_HIST
(
  CWWPH_CODE           NUMBER(20),
  CWWPH_ACWA_CODE      NUMBER(8),
  CWWPH_ACWA_USERNAME  VARCHAR2(50 BYTE),
  CWWPH_PWD            VARCHAR2(65 BYTE),
  CWWPH_PWD_CHANGE_DT  DATE,
  ACWA_PWD_CHANGE_BY   VARCHAR2(50 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;