--
-- TQC_ECM_SETUPS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_ECM_SETUPS
(
  EST_CODE          NUMBER,
  EST_ECM_URL       VARCHAR2(50 BYTE),
  EST_ECM_USERNAME  VARCHAR2(50 BYTE),
  EST_ECM_PASSWORD  VARCHAR2(50 BYTE),
  EST_SYS_CODE      NUMBER,
  EST_ROOT_FOLDER   VARCHAR2(50 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;