--
-- TQC_MEMO_TYPES  (Table) 
--
CREATE TABLE TQ_CRM.TQC_MEMO_TYPES
(
  MTYP_CODE            NUMBER(15)               NOT NULL,
  MTYP_SYS_CODE        NUMBER(8)                NOT NULL,
  MTYP_MEMO_TYPE       VARCHAR2(60 BYTE)        NOT NULL,
  MTYP_APPL_LVL        VARCHAR2(2 BYTE),
  MTYP_STATUS          VARCHAR2(2 BYTE)         DEFAULT 'A',
  MTYP_SUB_CODE        VARCHAR2(10 BYTE),
  MTYP_SAA_CODE        NUMBER(8),
  MEMDET_FOOTER        VARCHAR2(100 BYTE),
  MTYP_MEMO_TYPE_CODE  VARCHAR2(60 BYTE),
  MTYP_MEMO_SEQ_TYPE   VARCHAR2(10 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;

COMMENT ON COLUMN TQ_CRM.TQC_MEMO_TYPES.MTYP_STATUS IS '''A -ACTIVE I-INACTIVE''';