--
-- TQC_BRANCH_NAMES  (Table) 
--
CREATE TABLE TQ_CRM.TQC_BRANCH_NAMES
(
  BNS_CODE         NUMBER(8)                    NOT NULL,
  BNS_SHT_DESC     VARCHAR2(15 BYTE)            NOT NULL,
  BNS_NAME         VARCHAR2(50 BYTE)            NOT NULL,
  BNS_PHY_ADDRS    VARCHAR2(100 BYTE),
  BNS_EMAIL_ADDRS  VARCHAR2(30 BYTE),
  BNS_POST_ADDRS   VARCHAR2(35 BYTE),
  BNS_TWN_CODE     NUMBER(8),
  BNS_COU_CODE     NUMBER(8),
  BNS_CONTACT      VARCHAR2(30 BYTE),
  BNS_MANAGER      VARCHAR2(30 BYTE),
  BNS_TEL          VARCHAR2(50 BYTE),
  BNS_FAX          VARCHAR2(15 BYTE),
  BNS_STATE_CODE   NUMBER,
  BNS_ACC_TYPE     VARCHAR2(50 BYTE),
  BNS_REGION       VARCHAR2(50 BYTE),
  BNS_POST_CODE    VARCHAR2(30 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;