--
-- TQC_LABELS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_LABELS
(
  LABEL_CODE    NUMBER(22),
  LABEL_NAME    VARCHAR2(30 BYTE),
  LABEL_VALUE   VARCHAR2(200 BYTE),
  LABEL_STATUS  VARCHAR2(15 BYTE),
  LABEL_DESC    VARCHAR2(200 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;