--
-- TQC_ACC_CONTACTS_PWD_HIST  (Table) 
--
CREATE TABLE TQ_CRM.TQC_ACC_CONTACTS_PWD_HIST
(
  ACCPH_CODE           NUMBER(20),
  ACCPH_ACCC_CODE      NUMBER(8),
  ACCPH_ACCC_USERNAME  VARCHAR2(15 BYTE),
  ACCPH_PWD            VARCHAR2(65 BYTE),
  ACCPH_PWD_CHANGE_DT  DATE,
  ACCC_PWD_CHANGE_BY   VARCHAR2(15 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;