--
-- TQC_SYSTEM_BPM_TICKETS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_SYSTEM_BPM_TICKETS
(
  TQSBT_ID             NUMBER,
  TQSBT_SYS_CODE       NUMBER                   NOT NULL,
  TQSBT_SYS_MODULE     VARCHAR2(5 BYTE)         NOT NULL,
  TQSBT_EXECUTION_ID   VARCHAR2(30 BYTE)        NOT NULL,
  TQSBT_TICKET_NO      VARCHAR2(50 BYTE)        NOT NULL,
  TQSBT_TICKET_CODE    NUMBER,
  TQSBT_TICKET_DESC    VARCHAR2(50 BYTE)        NOT NULL,
  TQSBT_TICKET_ACTIVE  VARCHAR2(1 BYTE)         DEFAULT 'Y'
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;