--
-- TQC_SYS_PROCESS_SUB_AREAS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_SYS_PROCESS_SUB_AREAS
(
  SPRSA_CODE              NUMBER(15),
  SPRSA_SPRCA_CODE        NUMBER(15),
  SPRSA_SPRC_CODE         NUMBER(15),
  SPRSA_SUB_AREA          VARCHAR2(75 BYTE),
  SPRSA_TYPE              VARCHAR2(1 BYTE)      NOT NULL,
  SPRSA_SHT_DESC          VARCHAR2(25 BYTE),
  SPRSA_DEFAULT_USR_CODE  NUMBER(8),
  SPRSA_VISIBLE           VARCHAR2(1 BYTE)      DEFAULT 'Y'
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;