--
-- TQC_SYSTEM_RPT_TMPLATES  (Table) 
--
CREATE TABLE TQ_CRM.TQC_SYSTEM_RPT_TMPLATES
(
  SRPT_CODE           NUMBER,
  SRPT_SYS_CODE       NUMBER                    NOT NULL,
  SRPT_NAME           VARCHAR2(50 BYTE)         NOT NULL,
  SRPT_DESCRIPTION    VARCHAR2(250 BYTE),
  SRPT_DATA_FILE      VARCHAR2(50 BYTE)         NOT NULL,
  SRPT_APPLCTN_LEVEL  VARCHAR2(5 BYTE),
  SRPT_ACTIVE         VARCHAR2(1 BYTE),
  SRPT_SYS_XML        VARCHAR2(30 BYTE),
  SRPT_SYS_TMP        VARCHAR2(30 BYTE),
  SRPT_CUS_XML        VARCHAR2(30 BYTE),
  SRPT_CUS_TMP        VARCHAR2(30 BYTE)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;