--
-- TQC_LEADS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_LEADS
(
  LDS_CODE              NUMBER(15)              NOT NULL,
  LDS_TITLE             VARCHAR2(30 BYTE)       DEFAULT 'M',
  LDS_SURNNAME          VARCHAR2(50 BYTE),
  LDS_OTHERNAMES        VARCHAR2(100 BYTE),
  LDS_CAMP_TEL          VARCHAR2(50 BYTE),
  LDS_MOB_TEL           VARCHAR2(50 BYTE),
  LDS_CAMP_NAME         VARCHAR2(100 BYTE),
  LDS_FAX               VARCHAR2(50 BYTE),
  LDS_DESIGN            VARCHAR2(50 BYTE),
  LDS_EMAIL_ADDRS       VARCHAR2(150 BYTE),
  LDS_LDSRC_CODE        NUMBER(8),
  LDS_STATUS            VARCHAR2(1 BYTE)        DEFAULT 'N',
  LDS_RATE_TYPE         VARCHAR2(2 BYTE)        DEFAULT 'N',
  LDS_USR               VARCHAR2(30 BYTE),
  LDS_PHYSICAL_ADDRS    VARCHAR2(30 BYTE),
  LDS_POSTAL_ADDRS      VARCHAR2(30 BYTE),
  LDS_COUNTRY           VARCHAR2(30 BYTE),
  LDS_CITY              VARCHAR2(30 BYTE),
  LDS_POSTAL_CODE       VARCHAR2(30 BYTE),
  LDS_STATE             VARCHAR2(30 BYTE),
  LDS_TWN_CODE          NUMBER(15),
  LDS_COU_CODE          NUMBER(15),
  LDS_DATE              DATE,
  LDS_DESC              VARCHAR2(500 BYTE),
  LDS_USR_CODE          NUMBER(15),
  LDS_ORG_CODE          NUMBER(15),
  LDS_SYS_CODE          NUMBER(15),
  LDS_CONVERTED         VARCHAR2(1 BYTE)        DEFAULT 'N',
  LDS_PONT_NAME         VARCHAR2(100 BYTE),
  LDS_PONT_CONRT        VARCHAR2(2 BYTE)        DEFAULT 'N',
  LDS_PONT_AMOUNT       NUMBER(22,5),
  LDS_CUR_CODE          NUMBER(8),
  LDS_PONT_CLOSE_DATE   DATE,
  LDS_PONT_SALE_STAGE   VARCHAR2(2 BYTE),
  LDS_INDUSTRY          VARCHAR2(50 BYTE),
  LDS_ANN_REVENUE       NUMBER(22,5),
  LDS_NO_EMPYEE         NUMBER(15),
  LDS_WEB_SITE          VARCHAR2(150 BYTE),
  LDS_TEAM_USR_CODE     NUMBER(8),
  LDS_ACC_CODE          NUMBER(8),
  LDS_LSTS_CODE         NUMBER(8),
  LDS_STATE_CODE        NUMBER(8),
  LDS_DIV_CODE          NUMBER(22),
  LDS_CAMP_CODE         NUMBER(8),
  LDS_PROD_CODE         NUMBER(8),
  LDS_OCCUPATION        VARCHAR2(230 BYTE),
  LDS_COMP_NAME         VARCHAR2(200 BYTE),
  LDS_CONVERT_PROSPECT  VARCHAR2(50 BYTE),
  LDS_CLNT_SHT_DESC     VARCHAR2(50 BYTE),
  LDS_CLNT_CODE         NUMBER(23,5)
)
TABLESPACE CRMDATA
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;