--
-- TQC_CLIENT_AUDITORS  (Table) 
--
CREATE TABLE TQ_CRM.TQC_CLIENT_AUDITORS
(
  CLNTAUD_CODE            NUMBER(8),
  CLNTAUD_CLNT_CODE       NUMBER(15)            NOT NULL,
  CLNTAUD_YEAR            NUMBER(4)             NOT NULL,
  CLNTAUD_NAME            VARCHAR2(100 BYTE)    NOT NULL,
  CLNTAUD_QUALIFICATIONS  VARCHAR2(300 BYTE),
  CLNTAUD_TELEPHONE       VARCHAR2(300 BYTE),
  CLNTAUD_DESIGNATION     VARCHAR2(20 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MAXSIZE          UNLIMITED
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOCOMPRESS ;