--
-- TQC_PRODUCTS_VIEW  (View) 
--
CREATE OR REPLACE FORCE VIEW TQ_CRM.TQC_PRODUCTS_VIEW
(PROD_CODE, PROD_DESC, PROD_SHT_DESC, PROD_TYPE, SYS_CODE, 
 CLA_TYPE)
AS 
SELECT PROD_CODE,PROD_DESC,PROD_SHT_DESC,PROD_TYPE,27 SYS_CODE,CLA_TYPE
FROM LMS_PRODUCTS,LMS_CLASSES
WHERE PROD_CLA_CODE = CLA_CODE
AND NOT NVL(PROD_WET,TRUNC(SYSDATE)) < TRUNC(SYSDATE);