--Run the script backend
--Creates the column SPT_SUFFIXES  and constraint for it

ALTER TABLE TQC_SERVICE_PROVIDER_TYPES
    ADD SPT_SUFFIXES NUMBER;
    
ALTER TABLE TQC_SERVICE_PROVIDER_TYPES
    ADD CONSTRAINT TQC_SUFFIXES_UK UNIQUE(SPT_SUFFIXES);