CREATE OR REPLACE TYPE TQ_GIS."JVOUCHER_OBJ"                                          AS OBJECT
(
KEY NUMBER(20),
PARENT_KEY NUMBER(20),
CLIENTCODE NUMBER(20),
JV_ACCOUNT VARCHAR2(30),
ACCOUNT_NAME VARCHAR2(300),
ACCT_TYPE VARCHAR2(30),
OTHER_REF VARCHAR2(30),
NARRATION VARCHAR2(300),
AMOUNT NUMBER(20),
BRN_CODE NUMBER(30),
BRN_SHT_DESC VARCHAR2(30),
MTRAN_NO number(30),
MTRAN_CUR_CODE NUMBER,
MTRAN_ALLOC_MTRAN_NO NUMBER,
JV_TRANS_TYPE   VARCHAR2(30),   
JV_EXCHANGERATE NUMBER
);

CREATE OR REPLACE TYPE TQ_GIS."JVOUCHER_TAB"                                          AS TABLE OF JVOUCHER_OBJ;
GRANT EXECUTE, DEBUG ON TQ_GIS.JVOUCHER_TAB TO PUBLIC WITH GRANT OPTION;

