--
-- TQC_COMPANY_MEMO_CC_OBJ  (Type) 
--
CREATE OR REPLACE TYPE TQ_CRM."TQC_COMPANY_MEMO_CC_OBJ"                                          AS OBJECT 
(
  CC_CODE        NUMBER,
  CC_COMEM_CODE  NUMBER,
  CC_NAME        VARCHAR2(100 BYTE),
  CC_ADDRESS     VARCHAR2(102 BYTE),
  CC_EMAIL_ADDR   VARCHAR2(100),
  CC_REMARKS     VARCHAR2(200 BYTE),
  CC_TYPE        VARCHAR2(4 BYTE),
  CC_ADDRESSEE_TYPE NUMBER(1),
  CC_ADDRESSEE_CODE NUMBER(20),
  CC_CODETOWN VARCHAR2(100 BYTE)
); 
/