--
-- TQC_ALERT_TYPES_OBJ  (Type) 
--
CREATE OR REPLACE TYPE TQ_CRM."TQC_ALERT_TYPES_OBJ"                                          as object (
  ALRT_CODE      NUMBER(15),
  ALRT_TYPE      VARCHAR2(35 BYTE),
  ALRT_SYS_CODE  NUMBER(15),
  ALRT_EMAIL     VARCHAR2(1 BYTE),
  ALRT_SMS       VARCHAR2(1 BYTE),
    ALRT_SCREEN  VARCHAR2(1 BYTE),
    ALRT_EMAIL_MSGT_CODE NUMBER(5),
    ALRT_SMS_MSGT_CODE NUMBER(5),
    ALRT_GRP_USR_CODE NUMBER(8)
  ); 
/