--
-- TQC_CLIENT_ATTRIBUTES_OBJ  (Type) 
--
CREATE OR REPLACE TYPE TQ_CRM."TQC_CLIENT_ATTRIBUTES_OBJ"                                          AS OBJECT
(
  TCA_CODE NUMBER,
  TCA_ATTRIBUTE_NAME VARCHAR2(100),
  TCA_ATT_DESC VARCHAR2(300),
  TCA_PROMPT VARCHAR2(100),
  TCA_ATT_RANGE VARCHAR2(300),
  TCA_ATT_TYPE_INPUT VARCHAR2(100),
  TCA_TABLE_NAME VARCHAR2(50),
  TCA_COL_NAME VARCHAR2(50)
); 
/